### PR TITLE
updates for backport-assistant [For CRT main] 

### PR DESCRIPTION
**Pull request by claire-labry**
These are the updates done to backport-assistant that I believe need to be updated in order to work to backport to the release branches!

### CODE REVIEW

**Review by thiskevinwang — APPROVED** [review]
LGTM!

(Just for reference: [a marginally different `BACKPORT_LABEL_REGEXP`](https://github.com/hashicorp/waypoint/blob/main/.github/workflows/backport.yml#L47))

**Comment by thiskevinwang** [comment]
Just 1 callout relating to the regex — it matches labels like `release/1.0.x`, which is what most product teams use, but nomad has existing labels like `release/1.0` with no `.x` (see all [backport labels](https://github.com/hashicorp/nomad/labels?q=backport))

We'll want to address this 1 way or another:
- move to newer, standardized backport labels (recommended)
- **or** update the regex (less favorable)
...ultimately up to the Nomad team, since this is their workflow

One more callout [No action needed]: We'll want to delete existing labels like
- `backport/1.2.1`, `backport/1.2.0`, etc...

And there might be a be small bit of reconciling: updating of labels for existing PRs that have any.

**Review by alvin-huang — APPROVED** [review]
LGTM!

**Review by lgfa29 — APPROVED** [review]
Thanks @claire-labry!

@thiskevinwang thanks for the callout, we'll transition to using the new standard `backport/A.B.x` labels and apply it to the existing PRs.

**Pull request merged**
