### PR TITLE
vendor: explicit use of hashicorp/go-msgpack

### PR DESCRIPTION
**Pull request by greut**
ugorji/go is pointing to hashicorp/go-msgpack. The later says in its go.mod that it's is an independant module. This situation make it impossible to use nomad as is using go modules because you cannot use `replace` if the destination has a different name.

Also, why is Nomad using a branch? https://github.com/ugorji/go/compare/master...hashicorp:b-fix-gomod

A simpler solution would be for `go-msgpack@b-fix-gomod` to state `module github.com/ugorji/go` in its `go.mod`.

### CODE REVIEW

**Comment by notnoop** [comment]
To ease this, I can tag `hashicorp/go-msgpack` branch with something appropriate.

As for context - we use `hashicorp/go-msgpack` fork in some hashicorp projects to lock our dependency and protect against regressions in the upstream repo.  `hashicorp/go-msgpack` `master` is a very old fork that few hashicorp projects use and ugorji/go has added some breaking changes since.  master is effectively locked at this time.

The latest change fork is get nomad to latest upstream version but avoid the regression in captured in https://github.com/ugorji/go/issues/329 .

**Comment by greut** [comment]
My confinement exercice is to use Nomad via the go modules, https://github.com/greut/nomad-driver-docker/ 

With the recent changes, Nomad is closer than ever to be able to abandon _govendor_. This is set of changes is a step closer to that goal. I let you judge how best handle this as you know that why things are the way they are much better than I could. Also, when to handle this best. Cheers,

**Comment by tgross** [comment]
@notnoop should this be closed by https://github.com/hashicorp/nomad/pull/7560?

**Comment by notnoop** [comment]
Yes!  I cherry-picked the commits here and updated it to use the tag - Thanks @greut as always.

**Pull request closed without merging**
