### PR TITLE
Use Dockerhub Mirror.

### PR DESCRIPTION
**Pull request by RussellRollins**
Dockerhub is going to rate limit unauthenticated pulls.

Use our HashiCorp internal mirror for builds run through CircleCI.

### CODE REVIEW

**Comment by tgross** [comment]
@RussellRollins we have a Windows container that gets pulled as part of this test suite, which is failing when going thru the proxy

https://app.circleci.com/pipelines/github/hashicorp/nomad/12797/workflows/09e22173-3edd-484b-a7db-836dbc794c97/jobs/113828

```
docker pull docker.mirror.hashicorp.services/hashicorpnomad/busybox-windows:server2016-0.1
docker tag docker.mirror.hashicorp.services/hashicorpnomad/busybox-windows:server2016-0.1 hashicorpnomad/busybox-windows:server2016-0.1q
Error response from daemon: manifest for docker.mirror.hashicorp.services/hashicorpnomad/busybox-windows:server2016-0.1 not found: manifest unknown: The named manifest is not known to the registry.
```

**Comment by RussellRollins** [comment]
@tgross

Sorry, I got my PRs a bit out of order, needed to allow that hashicorpnomad image before I cut this PR:

https://github.com/hashicorp/docker-registry-sync/pull/13

Should pass now.

**Comment by tgross** [comment]
After the fix above, we're now getting test failures like this:

```
2020-10-29T18:19:00.863Z [DEBUG] docker/coordinator.go:336: docker: unable to cleanup image, still in use: image_id=sha256:445abbdad79aa9fc5826bb4ce447135637b9df410be17e5a0fc637f43e2e9074
    driver_test.go:1740: 
        	Error Trace:	driver_test.go:1740
        	            				wait.go:33
        	            				wait.go:19
        	            				driver_test.go:1733
        	Error:      	Received unexpected error:
        	            	image exists but should have been removed. Does another hashicorpnomad/busybox-windows:server2016-0.1 container exist?
        	Test:       	TestDockerDriver_EnableImageGC
--- FAIL: TestDockerDriver_EnableImageGC (25.25s)
```

@notnoop is there some kind of caching layer we might be running into on the CircleCI side that's breaking this test?

**Review by notnoop — APPROVED** [review]
thank you so much for the fix!  I have updated the tests themselves to use the mirror, so the tests still use the docker mirror if the image isn't cached (or if image was deleted by a test and follow up test needs to pull the image).

The failure was because we had two image references/tags for the same image ID: one with the docker mirror domain and one without. Docker image cache removal uses the underlying image ID and fails to remove if the canonical ID is associated with multiple image tags.  The error message was confusing :(.

**Comment by RussellRollins** [comment]
@notnoop figured my retagging solution might be causing something nasty. Thanks for ferrying this through!

**Comment by notnoop** [comment]
No problem!  THANK YOU for getting the mirror up and ready with such a short notice!

**Pull request merged**
