### PR TITLE
UI: Show message for when log collection is disabled

### PR DESCRIPTION
**Pull request by Sanskar531**
#16986
This is how it looks now:
https://imgur.com/a/i7XNgpY

### CODE REVIEW

**Review by tgross — COMMENTED** [review]
Hi @Sanskar531! The approach you're using here looks good to me in terms of what scenario we're responding to. I'm going to tag in @juliezzhou to get her feedback on the visual design of this warning dialog.

Thanks for the PR!

**Comment by juliezzhou** [comment]
looks like there are 2 options based on https://imgur.com/a/i7XNgpY? I prefer the option that shows the alert on top of the code block. i think it is more consistent with the notification on other pages

**Comment by tgross** [comment]
Tagging in @philrenaud for any thoughts

**Review by philrenaud — APPROVED** [review]
This looks good! Thanks, @Sanskar531 !

**Comment by Sanskar531** [comment]
> This looks good! Thanks, @Sanskar531 !

All good! Do you need me to do anything else?

**Comment by philrenaud** [comment]
Nope! Checks all passed on this, so merging it to main now.

Thanks again for your work on this, and look for it in an upcoming release!

**Pull request merged**
