### PR TITLE
Support "local file" download scheme for artifacts

### PR DESCRIPTION
**Pull request by dkong**

### CODE REVIEW

**Comment by dadgar** [comment]
Hey,

I am going to close this PR because as it is now this allows any task to have access to the data of all other tasks on the machine, breaking any FS isolation.

A work around is that you can run an HTTP server hosting a directory in which you have local files you'd like to serve and then have task download using localhost.

Thanks,
Alex

**Comment by parasyte** [comment]
Hi @dadgar! What are your thoughts on running the go-getter with cgroups restrictions to fix that FS isolation concern?

**Comment by dadgar** [comment]
Hey @parasyte. Unfortunately cgroups do not fix the FS isolation problem. Cgroups are used to enforce CPU/Memory and device access.

The problem with local file go-getter support is task "foo" could have an artifact block like this:
```
artifact {
   source = /nomad/data_dir/allocs/
}
```
And then it would go ahead and download the data of every other allocation.

My suggestion to @dkong is to create a web server such that:
```
/admin_created/data
  ...
  file_a
  folder_b/...
```
So that any data in that folder can be accessed by the artifact block

**Comment by parasyte** [comment]
If that's the case, where is the FS isolation actually occurring? I know it's possible to configure JVM security policies for file access, but that's completely outside of the scope of nomad. So what's actually preventing the jar itself from behaving similarly inappropriately with the file system?

**Pull request closed without merging**
