### PR TITLE
rkt: implemented "hostname" option. (#2629)

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by onlyjob** [comment]
I can't implement unit tests: no time, no skills... :(

Hopefully it would be an easy task for someone with more experience in Golang.

I've thoroughly tested this change.

**Comment by preetapan** [comment]
drivers are plugins and were refactored significantly so closing this due to age. 

@onlyjob we can take a redo of this work, new location for the rkt driver is https://github.com/hashicorp/nomad/tree/master/drivers/rkt

**Comment by onlyjob** [comment]
Perhaps this change should have been merged long time ago so redo wouldn't be necessary?
I think Nomad team should "redo" this change... Why would I bother redoing if this trivial change couldn't get merged for so long and now closed? Why would I have better luck now?

**Comment by onlyjob** [comment]
Now I'm working on current release 0.9.6 and I am very disappointed to find that my merge requests were not been taken for re-factored _rkt_ driver. Somebody on Nomad team was working on _rkt_ driver yet neglected to take my _essential_ commits that are crucial to practically use _rkt_ driver... :(

My commits are so straightforward I can hardly think of an easier exercise to incorporate a trivial improvement. It took me about 30 minutes to rebase _rkt_ improvements for 0.9.6 and I'm not even fluent in Golang. I don't know whether it is neglect or laziness but regardless, the outcome is frustrating.

Seriously, even for deprecated driver which was part of Nomad for years, not being able to pass `hostname` is a serious limitation that needs no justification to implement...  

I expect Nomad team to be much more efficient when it comes to working with community.

**Pull request closed without merging**
