### PR TITLE
Code Highlighting Improvements

### PR DESCRIPTION
**Pull request by jescalan**
Switches from highlight.js to prism, which has much better `hcl` support

### CODE REVIEW

**Comment by DingoEatingFuzz** [comment]
I'm not sure I fully understand how the switch is happening though. I'd expect to see a change to package.json or something to update the nextjs/remark/whatever-it-is-that-does-it package that switches us from highlight.js to prism.

Looking at the markup in the preview site, everything appears to still be hljs too.

**Comment by DingoEatingFuzz** [comment]
Hi @jescalan!

I did some poking and I'm mostly +1 to the changes. I'm a fan of Prism and the rationale to switch to it makes sense. Given that, I did a quick audit of various code samples on the site and have a few things to point out.

**1. JSON coloring changes seem worse**

Worse is of course subjective, but I have a few specifics. First, the colons are purple which makes them standout more than the old neutral gray color. Second, the keys are "uncolored". The white color does standout and is technically distinct from the grayer syntactic marks, but there isn't a lot of separation imo.

**2. Shell coloring is worse for how we use it**

`=` marks are now colored, and the preceding `$` is no longer subdued. This is also true on the Learn site and I believe the way they get around it is by using "plaintext" instead of "shell". Dunno what the correct path forward is, but I figure it's worth bringing up. 

image

**3. Named vs. Unnamed block declarations probably shouldn't be colored differently.**

I'm not the authority on HCL, but it seems that blocks like `group "api" {` and `network {` should be colored the same. Or they at least shouldn't be colored so differently.

Generally speaking, this is definitely an improvement in highlighting over hljs!

image

**4. The deep blue bg color should be preserved**

This change makes the code blocks have a flat gray background instead of a dark gray with a blue tint. I think the blue tint is more harmonious with the general green color of Nomad and is also consistent with code blocks elsewhere on HashiCorp web properties.

**5. Code blocks outside of API and Docs are still using Highlightjs**

This might be out of scope for your PR, but I figured you'd want it on your radar. We use code blocks on some of the marketing/use case pages. They must be using a separate component that isn't affected by the `nextjs-scripts` update.

image

**Comment by jescalan** [comment]
@DingoEatingFuzz Thank you for this fantastic feedback -- agreed on all counts. I think I have most of this resolved, hopefully this is at a point where it's worth shipping out now!

- **JSON code block coloring** - I agree here - I overrode the defaults and added some custom coloring to get back to a better spot. Here's how it looks now:

Screen Shot 2020-05-01 at 3 56 31 PM

- **Shell coloring** - dug deeper into this and found that within prism, there are separate languages for "shell session" and "shell", which makes perfect sense. I did a find-and-replace for all blocks with `'''shell\n$` and replaced with `'''shell-session` which fixed the highlighting for this block style 🎉

- **HCL named block coloring** - unfortunately this is an issue with the syntax highlighter rather than the coloration. I will queue up a task to get one of us to look into contributing this change to prism, but for now given that its already an improvement over using `ruby` as the highlighter I feel like this shouldn't hold us back from :shipit: 

- **Preserving blue background** - changed this back to a blue-toned gray!

- **Code blocks outside docs still using highlight.js** - yep, out of scope for this PR but we have a ticket to handle this and push in upgrades as soon as we have alignment around getting prism shipped in general, which your review has been a huge step toward.

**Comment by jescalan** [comment]
Ok, so this feels ready to roll for me, but it touches a lot of files and I want to make sure I'm not accidentally releasing things early. I guess the move is to merge but not push to `stable-website` and let it sync the next release. Is that ok with you @DingoEatingFuzz?

**Pull request merged**
