### PR TITLE
update imports

### PR DESCRIPTION
**Pull request by xtrntr**
Update imports as per https://github.com/hashicorp/consul/pull/5517

### CODE REVIEW

**Comment by endocrimes** [comment]
@xtrntr We currently depend on a fairly old version of Consul in Nomad, from before the switch to Go Modules, although we may upgrade in the near future - I'm curious as to what you're trying to accomplish here?

**Comment by xtrntr** [comment]
@endocrimes i get this error when i try to import `github.com/hashicorp/nomad/testutil`

```go: finding github.com/hashicorp/consul/lib/freeport latest
go: finding github.com/hashicorp/consul/lib latest
build $MY_PROJECT_NAME: cannot find module for path github.com/hashicorp/consul/lib/freeport
```

**Comment by endocrimes** [comment]
@xtrntr Ah. We currently only support using the `/api` package as a module I believe. @notnoop might have some ideas to help however.

**Comment by xtrntr** [comment]
Thanks @endocrimes. I would love to know if there's a good way to mock and test Nomad on my services.

**Pull request closed without merging**
