### PR TITLE
[ui] Simplify times in task events

### PR DESCRIPTION
**Pull request by philrenaud**
Resolves https://github.com/hashicorp/nomad/issues/18507

Task restarts (and possibly other events) use more time specificity than is needed (for example, "task restarting in 10.01934802s").

This simplifies and rounds times to simple second, minute, or hour strings where relevant.

### CODE REVIEW

**Comment by philrenaud** [comment]
Q for @DingoEatingFuzz : Is the most appropriate place for me to handle this in the TaskEvent model, or in the TaskEvent Serializer?

There's already a 
```
  attrs = {
    message: 'DisplayMessage',
  };
```

aliasing happening in the serializer which I think can probably be removed with this change, but wanted to double check.

**Review by tgross — APPROVED** [review]
LGTM

**Comment by DingoEatingFuzz** [comment]
> is the most appropriate place for me to handle this in the TaskEvent model, or in the TaskEvent Serializer?

Personally I see this as presentation logic vs. data logic, so I like it in the model. I could also see it as a helper (though that's also a little odd since it operates on a whole string that happens to have a duration in it, not just a duration).

**Review by DingoEatingFuzz — APPROVED** [review]
Great time to use unit tests, you love to see it!

**Pull request merged**
