### PR TITLE
vault: eliminate vaultclient test import cycle

### PR DESCRIPTION
**Pull request by pkazmierczak**
This PR eliminates the vaultclient test import cycle by putting the test file into a separate package and making vaultclient objects public. 

Ref https://github.com/hashicorp/team-nomad/issues/404

### CODE REVIEW

**Review by tgross — COMMENTED** [review]
Having a test file with a different package name in the same directory as the package under test feels a little weird to me. Can we lift this test file up into the `client` package maybe? I'm not sure which import creates the cycle.

Also, we didn't catch this originally because this package was in the list of ["uninteresting"](https://github.com/hashicorp/nomad/blob/main/tools/missing/main.go#L159) packages for the linter that verifies we're testing all packages, and it was left out of [`test-core.json`](https://github.com/hashicorp/nomad/blob/main/ci/test-core.json) that feeds packages to a matrix of GHA runners. Wherever the test lands, we should make sure we're running it. We can probably add this package to the `client` group? Maybe check how long that currently takes vs the `quick` group.

**Comment by pkazmierczak** [comment]
> Having a test file with a different package name in the same directory as the package under test feels a little weird to me. 

That's because it is! But there's [a precedent](https://github.com/hashicorp/nomad/blob/main/client/widmgr/widmgr_test.go) and I thought that perhaps this is the way we usually handle import cycles in tests. 

> Can we lift this test file up into the `client` package maybe? I'm not sure which import creates the cycle.

I'm completely fine moving it to the `client` package, and yes, the `client` import causes the cycle.

**Comment by tgross** [comment]
> But there's a precedent and I thought that perhaps this is the way we usually handle import cycles in tests.

Hm, I bet we're not testing that package either as a result. We should double-check that works with the way the GHA tooling is configured.

**Comment by pkazmierczak** [comment]
@tgross I moved the tests to `client/`

**Review by tgross — APPROVED** [review]
LGTM!

**Pull request merged**
