### PR TITLE
WIP: Start tasks in alloc in config order for container networking.

### PR DESCRIPTION
**Pull request by dmwilcox**
This is a rough pass at adding the ability to order task start-up.

Would appreciate guidance on how a change like this would best fit into the existing Nomad client architecture and properly testing it.

Intended purpose is for starting containers in the same network namespace, e.g.
`network_mode: "container:mytask-${NOMAD_ALLOC_ID}"`

### CODE REVIEW

**Comment by dmwilcox** [comment]
PR is relevant to open issues: #419 #899 #4447

**Comment by notnoop** [comment]
@dmwilcox Thank you so much for this contribution.  The team has been thinking about task dependencies as part of 0.10.x as well.  We are establishing product requirement and researching configuration knobs we want to expose for this.  Mind if we put this PR on hold while we do our thinking as well and update you?

**Comment by dmwilcox** [comment]
Thanks @notnoop happy to wait a little bit but my concern is this feature has languished undone for literally years.

Given the increasing need of pod-like functionality to use Consul Connect -- a simple but functioning feature soon (tasks start in config order if you set var=true) is better than a complex feature later (per-task declared dependencies).

Happy to hear what you guys come up with.  I'll check back in a week.  Thank you!

**Comment by nickethier** [comment]
Hey @dmwilcox I'm happy to let you know shared network namespace is coming in 0.10. I did a demo of it at HashiconfEU a few weeks ago. We would love your feedback on it and if it satisfies your requirements here. https://www.hashicorp.com/resources/service-mesh-with-consul-connect-and-nomad-0-10

**Comment by dmwilcox** [comment]
Thanks @nickethier your presentation shows most of what I need.  I'm yet to get the 0.10 preview working however (compiled the CNI plugins and placed them in /opt/cni/bin but there are some issues with the arguments to the plugins at task start-up).

The above link mentions a guide on nomadproject.io we could refer to for the 0.10 preview -- is that still available?  I wasn't able to find it under 'Guides'.  Thank you

**Comment by dmwilcox** [comment]
I'm using the shared netns in 0.10.0-beta1 to great affect and do not need this hack anymore.  Closing the PR.  Thanks @nickethier for your work on this!

**Pull request closed without merging**
