### PR TITLE
vendor: update gopsutil to v2.19.6

### LINKED ISSUE #6483: update gopsutil
The library we used for stats collection has changed how windows stats collection works: 
https://github.com/shirou/gopsutil/pull/611

This will affect this code:
https://github.com/hashicorp/nomad/blob/master/client/stats/cpu_windows.go#L12

This issue captures updating gopsutil, as well as testing windows specific changes.

### PR DESCRIPTION
**Pull request by greut**
The `Stolen` field has been removed, https://github.com/shirou/gopsutil/pull/677 as it wasn't used. This pull request upgrade that dependency and corrects the code accordingly.

gopsutil 2.19.7 introduce breaking changes with the vendored version of docker; pretty please update docker.

Closes #6483, #6957

### CODE REVIEW

**Comment by notnoop** [comment]
Thank you so much for your contribution.  I'm afraid upgrading gopsutil is a bit more complicated. 

2.18.12 introduced a backward compatible change to windows cpu handling in https://github.com/shirou/gopsutil/commit/eead265362a2c459593fc24d74aef92858d67835 .

We aim to upgrade docker and gopsutil to the latest, at least so we can pick up a panic fix in 2.20.1 https://github.com/shirou/gopsutil/commit/3964e5b57942b45396df794baa03df27a667f895 .

We'd appreciate any PR that upgrades docker/gopsutil to the latest, though I'm also aiming to get the packages upgraded for 0.11.

**Comment by greut** [comment]
@notnoop I see, this issue is way harder that I thought. Should I try again that one? https://github.com/hashicorp/nomad/pull/5807

**Comment by notnoop** [comment]
That'd be wonderful indeed.  fwiw, I had a WIP PR in https://github.com/hashicorp/nomad/commits/b-update-gopsutil-20200127 but I haven't gotten it across the line.  Two commits are fixes to changes in gopsutil and docker types, but I assume we need more govendor magic incantations to get this working :(.

**Comment by greut** [comment]
@notnoop Great... IIRC I had to battle quite a lot with govendor. I'm closing this then.

**Pull request closed without merging**
