### PR TITLE
ui: fix long loading times on `/jobs/:jobId` page

### PR DESCRIPTION
**Pull request by ChaiWithJai**
This PR is part of resolving [14787]( https://github.com/hashicorp/nomad/issues/14787).

This PR does not solve long loading times on the `jobs.index` route. I believe we can and should use pagination and we can also patch [10555](https://github.com/hashicorp/nomad/issues/10555) while we do that to keep PRs small.

### CODE REVIEW

**Review by philrenaud — APPROVED** [review]

**Comment by djenriquez** [comment]
> > Hi @ChaiWithJai, I'm looking at creating a local branch where I merge `v1.5.3` into this branch (since thats the release we're on internally). Do you foresee any incompatibilities with that?
> 
> Merging this branch might not be suitable for your needs as it does not solve the problem for the `jobs.index` page (The main Jobs list page). And I think that @philrenaud solves this same from this PR in his current block of work which we'll be out soon.

Ok, just to confirm, theres a PR that exists which we think will handle the problems in GH-14787?

**Comment by philrenaud** [comment]
Hi @djenriquez — the PR that Jai is referring to is https://github.com/hashicorp/nomad/pull/17214 but that doesn't solve for the slow index page issue of https://github.com/hashicorp/nomad/issues/14787 — it's meant to make child jobs specifically less painful to use within the UI, but won't impact the /jobs index page.

The correct solution for that is for us to paginate `jobs` index requests; we're working on setting that up but have some plans to depend on the unpaginated "all jobs" request for some upcoming features. As of now, the plan is to set up a new "all jobs' summaries" request, and to use a paginated jobs request otherwise.

This seems like something worth prioritizing, so we'll kick off work related to it soon. We appreciate your patience on this!

**Comment by djenriquez** [comment]
Completely understood @philrenaud , thank you for the reply.

**Comment by philrenaud** [comment]
Made less necessary with the work in https://github.com/hashicorp/nomad/pull/20452

**Pull request closed without merging**
