### PR TITLE
logmon: add log_extension configuration to logs config

### PR DESCRIPTION
**Pull request by ilyaiqoqo**
for convenience allow configuring log files extension from job stanza

### CODE REVIEW

**Comment by ilyaiqoqo** [comment]
Thanks @schmichael! 

Added file_extension property to logs config in the job stanza, by default its "".
file_exteension configuration is enforced bt [A-Za-z0-9_-].


log.file_extension would probably be a good config key in the client options stanza. Then we could enforce is only contains [A-Za-z0-9_-] and avoid path traversal / shell escaping issues (I don't think there are any today, but they're the sort of thing that should be defended against in depth).

**Comment by ilyaiqoqo** [comment]
@schmichael can you please review this patch

**Comment by schmichael** [comment]
Would automatically appending `.txt` to log files on Windows be a simpler approach?

If that's not sufficient would this be better suited for a client config than a job file?

I just want to make sure I understand the use case as it seems rare that you would want to vary the log extension between jobs. It seems more common to vary it between host operating systems?

**Comment by schmichael** [comment]
I'm going to go ahead and close this until we hear back from @ilyaiqoqo about their use case (see above comment).

**Pull request closed without merging**
