### PR TITLE
Follow symlinks that escape chroot folders via hardlink/copy

### PR DESCRIPTION
**Pull request by dadgar**
Executor: Solves the problem of files within the configured chroot folders having symlinks that are unreachable in the chroot not existing.

### CODE REVIEW

**Comment by dadgar** [comment]
Closing this for now. Discussed with team and we want to stick with the whitelist approach so the operator actually can reason about what is being added to the chroot.

**Comment by parasyte** [comment]
@dadgar How can we prevent nomad creating broken chroot environments? E.g. `resolv.conf` is inaccessible on Ubuntu 14.04.

**Comment by dadgar** [comment]
@parasyte if you build off master that should be fixed. The reason we closed this is because we want to ensure that only directories included in the whitelist are put in the chroot. We will add a way for operators to extend/override the whitelisted directories but I think we want to find a more comprehensive solution for Nomad 0.4

**Comment by parasyte** [comment]
Ok!

**Pull request closed without merging**
