### PR TITLE
Log adding of servers at INFO level

### PR DESCRIPTION
**Pull request by neumayer**
I'm definitely not getting the whole picture here, but for me it would certainly help just to see this in the logs.

### CODE REVIEW

**Comment by schmichael** [comment]
I was just working in this code while investigating #1641 -- any chance you could hop into https://gitter.im/hashicorp-nomad/Lobby someday between 9am-5pm PDT and let me know what you're diagnosing?

**Comment by schmichael** [comment]
This code will most likely change before 0.5, but I'll make sure to maintain an INFO log level for this information.

Thanks!

**Comment by neumayer** [comment]
I was looking at this and then I realised that I had the same "issue," just that there's no confirmation of having auto discovered other instances. So the confirmation in the logs (when on info level) was to *not* find errors.

https://github.com/hashicorp/nomad/issues/1692

I do think that this issue can be closed by just having some kind of confirmation that the bootstrapping worked in the logs (at info level).

I'll try to take a look at the issue you linked and tell you if I have anything to say about it :-)

**Comment by schmichael** [comment]
@neumayer Oh fantastic. I'm new on the nomad team and missed #1692 -- definitely related to what I'm working on. I'll make sure it gets closed.

Thanks!

**Pull request merged**
