### PR TITLE
Add handling for license requests in OSS

### LINKED ISSUE #9827: OSS Nomad spam Enterprise-only related errors in logs
### Nomad version
`Nomad v1.0.2 (4c1d4fc6a5823ebc8c3e748daec7b4fda3f11037)`

### Operating system and Environment details
Centos 7.6 x64

### Issue
Nomad logs are spammed by:
```
2021-01-15T14:52:09.436Z [ERROR] http: request failed: method=GET path=/v1/operator/license error="Nomad Enterprise only endpoint" code=501
```

We use OSS version so not sure why it does it.

Maybe related to the fact that we have telemetry enabled?

### Reproduction steps

1. Run OSS version
2. Wait

Kinda related to https://github.com/hashicorp/nomad/issues/4567

### PR DESCRIPTION
**Pull request by backspace**
This changes the OSS response for `GET /v1/operator/license` from 501 to 204 to close #9827. It preserves the `1` status code when running `nomad operator license`. Here’s me interacting with it locally:

image

This means people won’t see what appears to be an error in their logs for a known situation, as the UI checks this endpoint to decide whether to show enterprise features.

### CODE REVIEW

**Review by tgross — COMMENTED** [review]
This mostly looks like a solid approach.

> `command/license_get_test.go `is where a test for this happens, but it’s expecting an error code, should it still?

It should be changed to expect the new success code but it should probably still report that same message to the user.

> I couldn’t find a test for API endpoint vs the command

Typically we don't have separate HTTP API tests; most of the logic is either in the RPC that the HTTP API calls, or in the CLI. So it's not a lot of payoff for the effort. This endpoint has so little logic it's probably safe to leave out a test so long as it compiles.

> is 204 really the answer? with an empty string response?

Should it be an empty JSON body instead? Not sure what the UI typically expects.

> will it break when enterprise tries to handle the endpoint instead?

Yeah, this isn't _quite_ going to work. But if you move the new `LicenseRequest` method into a `operator_endpoint_oss.go` file with the directive `// +build !ent` at the top, that will work. Take a look at `operator_endpoint_ent.go` in the enterprise repo for an example of the opposite.

**Comment by backspace** [comment]
Thanks for the input, @tgross!

re the error code, I believe the test is looking for the exit code vs the HTTP status code. So to preserve expectations around that maybe it should still be 1? CLI on enterprise vs free:

image

But I don’t know about whether keeping `Error getting license: EOF` is necessary 🤔


Because of this line in [204 documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)

> Although this status code is intended to describe a response with no body, servers may erroneously include data following the headers.

I’m now leaning toward just 200 with `{}` as the body. In this case the UI doesn’t care what’s returned but an empty object seems clear to me.

**Comment by tgross** [comment]
> re the error code, I believe the test is looking for the exit code vs the HTTP status code. So to preserve expectations around that maybe it should still be 1?

Ah yes it should just check for exit code 1.

> But I don’t know about whether keeping Error getting license: EOF is necessary

I _think_ the EOF is only going to show if it's not getting a body in the response. It's probably worth special-casing getting the 204 back to return a friendly message and then if we do get an EOF to return the existing message so that we're handling actual errors communicating with the server.

**Review by tgross — APPROVED** [review]
LGTM 👍  Thanks @backspace!

**Pull request merged**
