### PR TITLE
Allow `.` in Environment Variable Names

### PR DESCRIPTION
**Pull request by angrycub**
From [https://github.com/appc/spec/blob/master/spec/aci.md](https://github.com/appc/spec/blob/master/spec/aci.md):

>environment (list of objects, optional) represents the app's environment variables (ACE can append). The listed objects must have two key-value pairs: name and value. The name must consist solely of letters, digits, and underscores '_' as outlined in IEEE Std 1003.1-2008, 2016 Edition, with practical considerations dictating that the name may also include periods '.' and hyphens '-'. The value is an arbitrary string. These values are not evaluated in any way, and no substitutions are made.

Dotted environment variables are frequently used as a part of the Spring Boot pattern. (re: ZD-6116)

This PR specifically doesn't address the conversion of hyphens (`-`) due to an issue with rkt [[Nomad GH # 2358]](https://github.com/hashicorp/nomad/issues/2358).

### CODE REVIEW

**Comment by schmichael** [comment]
Can you also fix our environment variable parsing library? https://github.com/hashicorp/go-envparse/blob/master/envparse.go#L116-L144

**Comment by angrycub** [comment]
@schmichael, upon further reflection, based on the ask to adjust go-envparse, I ended up thinking that this might not be the best course of action.  In the case of shell environment variables, dots have mixed support, tending to the unsupported.  So for drivers like exec and raw_exec this type of change could allow for unreadable variables.  I was able to find what appears to be the Spring Boot workaround using the [`SPRING_APPLICATION_JSON`](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) environment variable to work around the naming situation there.  

Docker seems to happily allow the creation of a dotted environment variable via their `-e` parameter, so perhaps a solution is to create a strict and relaxed version of the check?

**Comment by angrycub** [comment]
An additional comment I have received on this issue for further discussion. 

> [This process] is not a shell script and . is certainly legal for ENV vars passed to processes. Perhaps this should be handled in the driver layer and then drivers can override any default behavior. Because docker is constrained because of [other drivers'] limitations.

**Comment by schmichael** [comment]
So [this sample job](https://gist.github.com/schmichael/44532ef834df6e28d63e39d2a5764a31) outputs:

```
foo
foo.BAR
foo.bar
```

Meaning `${FOO.BAR}` is a valid env var for dash (Debian/Ubuntu's version of `/bin/sh`).

Switching to `/bin/bash` still works as well.

**Comment by angrycub** [comment]
@schmichael -  Made PR for go-envparse https://github.com/hashicorp/go-envparse/pull/2

**Comment by schmichael** [comment]
Mind updating go-envparse in this PR? Should be:

```sh
go get -u github.com/hashicorp/go-envparse
govendor update github.com/hashicorp/go-envparse
# git commit + push
```

**Pull request merged**
