### PR TITLE
Bump up github.com/hashicorp/go-syslog for better BSD support

### PR DESCRIPTION
**Pull request by dwagin**
Bump up github.com/hashicorp/go-syslog for better BSD support

### CODE REVIEW

**Comment by cgbaker** [comment]
@dwagin , do you mind modifying this to explicitly reference the version of hashicorp/go-syslog? that is, `v1.0.0`

**Comment by dwagin** [comment]
Yes, good idea.20:55, 19 августа 2019 г., Chris Baker <notifications@github.com>:@cgbaker requested changes on this pull request.

@dwagin ,do you mind modifying this to explicitly reference the version of hashicorp/go-syslog? that is, v1.0.0?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- /Dmitry

**Comment by dwagin** [comment]
> @dwagin ,do you mind modifying this to explicitly reference the version of hashicorp/go-syslog? that is, `v1.0.0`?

@cgbaker, done.

**Comment by cgbaker** [comment]
thanks, @dwagin .

**Pull request merged**
