### PR TITLE
Update ugorji/go to latest

### LINKED ISSUE #4454: Still uses "go-msgpack/codec" - unmaintained fork of "ugorji/go/codec"
[nomad/structs/structs.go](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L40) uses [hashicorp/go-msgpack/codec](https://github.com/hashicorp/go-msgpack) which appears to be an obsolete (no commits since 2015) fork of actively maintained [github.com/ugorji/go](https://github.com/ugorji/go), [imported from the same file](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L36).

Needless forking is harmful. Please consider using the original project.

### PR DESCRIPTION
**Pull request by notnoop**
fixes #4454 

Our testing so far indicates that ugorji/go/codec maintains backward
compatiblity with the version we are using now, for purposes of Nomad
serialization.

Using latest ugorji/go allows us to get back to using upstream library,
get get the optimizations benefits in RPC paths (including code
generation optimizations).

ugorji/go introduced two significant changes:
* time binary format in https://github.com/ugorji/go/commit/debb8e2d2e8bd8cf1e9b6d806cf5e58df86b970c.  Setting `h.BasicHandle.TimeNotBuiltin = true` restores old behavior
* ugorji/go started honoring `json` tag as well:

v1.1.4 is the latest but has a bug in handling RawString that's fixed in
https://github.com/ugorji/go/commit/d09a80c1e0c3162e022a114ab0f037e2596969e6
.

### CODE REVIEW

**Comment by towe75** [comment]
I worked on #5312 and noticed a dependency problem because both libpod and nomad depend on ugorji/go
So i tried to build against this branch but could not manage to get a working environment. 

Here is a simple test using go 1.12 and a go module:

in go.mod

```
module github.com/pascomnet/justatest

go 1.12

require (
	github.com/hashicorp/nomad v0.9.1-0.20190509233558-a8a6515e9f73
	github.com/ugorji/go v1.1.5-pre 
)
```

in main.go

```
package main

import (
	"github.com/hashicorp/nomad/plugins"
)

func main() {
	d := plugins.PluginDevice
	if (d.DoneContext.Err() == nil) {
		// just a test
	}
}
```

go build says then:

```
# github.com/hashicorp/nomad/nomad/structs
/root/go/pkg/mod/github.com/hashicorp/nomad@v0.9.1-0.20190509233558-a8a6515e9f73/nomad/structs/structs.go:8778:15: h.BasicHandle.TimeNotBuiltin undefined (type "github.com/hashicorp/go-msgpack/codec".BasicHandle has no field or method TimeNotBuiltin)
```

Building against nomad v0.9.2 (release) yields much more errors, though. 
Can you please check or clearify if i am doing something wrong here?

**Comment by notnoop** [comment]
I've tested with latest ugorji/go version (v.1.1.7) and discovered that it handles `nil` in map values differently, where it deserializes a nil reference as a reference of zero value.  The regression seems to be due to https://github.com/ugorji/go/commit/ffda9d4fbaa7bbfc7cec00b0dde60b223c70ad3c .

Merging this as-is for this to soak in while we run testing and do a write up and follow up with ugorji/go library.

**Comment by notnoop** [comment]
@towe75, I'm afraid I don't have much experience with go mod. The dependency on ugorji/go seems very brittle right now.  I'd suggest testing with using the exact version of ugorji/go as used by nomad and specified in [`vendor/vendor.json`](https://github.com/hashicorp/nomad/blob/master/vendor/vendor.json) file for the version you depend on.

**Comment by onlyjob** [comment]
"latest" should only ever mean formal, tagged [semantic](https://semver.org) release: https://github.com/ugorji/go/releases

It is a bad practice to vendor by some random commit in-between releases.

Please vendor properly.

**Pull request merged**
