### PR TITLE
Using cgo dependencies to look up users

### PR DESCRIPTION
**Pull request by diptanu**
This fixes https://github.com/hashicorp/nomad/issues/573

### CODE REVIEW

**Comment by dadgar** [comment]
LGTM

**Comment by c4milo** [comment]
:hankey: sad but it doesn't seem like there is an easy way of not using CGO here, especially for people using nss-altfiles to place this information in alternative paths like CoreOS is doing.

**Comment by pires** [comment]
@diptanu will a 0.2.3-rc1 release get out?

**Comment by c4milo** [comment]
FYI, eventually, we should be able to remove CGO for this specific use case: https://github.com/aperezdc/nss-altfiles/issues/4

**Comment by diptanu** [comment]
@pires Working on it at the moment

**Comment by diptanu** [comment]
@pires The 0.2.3-rc1 has been released here - https://releases.hashicorp.com/nomad/0.2.3-rc1/

**Comment by pires** [comment]
@diptanu you're the best! Will report on the discussion group.

**Pull request merged**
