### PR TITLE
Add 'nomad.advertise.address' to client meta via NomadFingerPrint

### LINKED ISSUE #4381: Feature - add the local clients advertise address to interpolation env vars
In some situations, Nomad tasks need to communicate to the Nomad API. Currently there is no interpolation environment variable which allows the local Nomad clients advertise address to be passed to the task for use making calls. It would be super helpful if `NOMAD_ADVERTISE_ADDR` or similar could be added for this task.

### PR DESCRIPTION
**Pull request by jrasell**
This commit adds the Nomad local client advertise address in the form host:port to the client attributes. This is helpful in situation where the task is making Nomad API calls as the current alternative is to use hardcoded IPs, DNS LB names or create dummy ports and use the env vars resulting from this.

Once this is merged, I will raise a PR for doc updates to reflect the change.

Tested locally with job:
```
driver = "raw_exec"
      config {
        command = "echo"
        args = ["${attr.nomad.advertise.address}"]
      }
```
Result:
```
$ nomad logs 1e4148e2
127.0.0.1:4646
```

Nomad status output
```
$ nomad node status -verbose 0817b9ac |grep 'nomad.advertise.address'
nomad.advertise.address       = 127.0.0.1:4646
```

Tests pass locally:
```
$ /usr/local/bin/go test -timeout 30s github.com/hashicorp/nomad/client/fingerprint -run ^TestNomadFingerprint$

ok  	github.com/hashicorp/nomad/client/fingerprint
Success: Tests passed.
```

Closes #4381

### CODE REVIEW

**Comment by jrasell** [comment]
@dadgar makes perfect sense; i'll work on updating to make the change in that manner.

**Comment by jrasell** [comment]
@dadgar updated as per your advice

**Comment by preetapan** [comment]
@jrasell the most recent update looks good but there is a merge conflict, could you rebase your branch against master?

**Comment by jrasell** [comment]
@preetapan merge conflict has been resolved

**Pull request merged**
