### PR TITLE
Update percent based max parallel #2810

### LINKED ISSUE #2810: Allow percent for update -> max_parallel rolling upgrade
On top of a normal `update -> max_parallel` static value

```hcl
update {
  max_parallel     = 3
  min_healthy_time = "30s"
  healthy_deadline = "2m"
}
```

It would be nice to have `update -> max_parallel` as a percent of the Task Group count 

```hcl
update {
  max_parallel     = "10%"
  min_healthy_time = "30s"
  healthy_deadline = "2m"
}
```

Slightly refs #2806

### PR DESCRIPTION
**Pull request by lovwal**
This resolves #2810 

I made an attempt to implement it without using the new field. (needs cleanup) https://gist.github.com/lovwal/7aefcc1ef505b1d17c061b0903e8a892
I can clean the code I wrote for this if the above approach is preferred.

### CODE REVIEW

**Comment by dadgar** [comment]
@lovwal Hey great work! I prefer the approach you took in the gist! That is the way I had planned on implementing it. Would you mind if we update the PR to go with that approach?

**Comment by lovwal** [comment]
Hey Alex! Thanks! Here's the updated version. 
Please let me know if you have any comments.

**Comment by lovwal** [comment]
Sorry forgot to tag you @dadgar 
The new commit contain a cleaned up version of the gist file.

**Comment by dadgar** [comment]
@lovwal Sorry for actually misleading you. Only after looking at it again did I realize that this approach will not work. The root of the issue is that this approach only works for hcl jobs and not jobs submitted by the JSON API.

To make things worse, the JSON and internal struct type is an integer and not a string so doing this in a backwards compatible way is a lot more work than it initially looks like. 

As such I am going to close this. We may need a separate field for percent based updates but I would like to give it a bit more thought.

**Comment by lovwal** [comment]
@dadgar No worries, this was written for the HCL alone, and is somewhat of a hack in it self ;).

Actually, I think this should be fairly straight forward to implement in the RPC endpoint, but it requires the new field. Let MaxParallelPercent (MPP) be defined as a float 0 < x =< 1, 0 per default. Swap the percent variable for the MPP variable here https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L1496 and do minor rewrite/sanity checks (i.e not more than 100%, ignore if it is 0 etc.). This should also solve any backwards compatibility as the field will either be ignored (older server versions), or 0 (older client versions). 

 The main side effect you will have to live with is overwriting hard-set max parallel values, as you won't know if the user set the max parallel to 1 or if it was left out in the spec. Likewise when submitting JSON jobs, the max parallel will most likely be defined as it was calculated previously when using MPP. 

 You can also be a little bit clever and include this variable in the base as well and have a percentage base point for all task groups. 
Sorry if I missed anything, just getting acquainted to the codebase.

**Pull request closed without merging**
