### PR TITLE
api: return 404 for alloc FS list/stat endpoints

### PR DESCRIPTION
**Pull request by tgross**
Fixes https://github.com/hashicorp/nomad/issues/11480

If the alloc filesystem doesn't have a file requested by the List Files (`/v1/client/fs/ls`) or Stat File API (`/v1/client/fs/stat`), we currently return a HTTP 500 error with the expected "file not found" error message. Return a HTTP 404 error instead.

This change doesn't help the streaming endpoints, but all our callers currently call the `/v1/client/fs/stat` endpoint first.

### CODE REVIEW

**Comment by tgross** [comment]
This missed 1.2.0-rc1, so leaving this in draft state until after the 1.2.0 GA goes out.

**Comment by DerekStrickland** [comment]
With the help of the UI team, I tracked down some [UI related code](https://github.com/hashicorp/nomad/blob/6bbcb180f2f2025d124c5b63d2156a1cabc08f11/ui/app/adapters/allocation.js#L34-L38) and [acceptance tests](https://github.com/hashicorp/nomad/blob/6bbcb180f2f2025d124c5b63d2156a1cabc08f11/ui/tests/acceptance/behaviors/fs.js#L355) that I think will have to change or be deleted along with or shortly after this PR.  cc @ChaiWithJai @lgfa29

**Comment by tgross** [comment]
I can follow-up with @ChaiWithJai and try my hand at a little bit of UI work 😀

**Comment by ChaiWithJai** [comment]
> I can follow-up with @ChaiWithJai and try my hand at a little bit of UI work 😀

I'm on it!

**Comment by tgross** [comment]
The UI changes LGTM but it's my PR so I can't be the one to approve it 😀

**Review by DerekStrickland — APPROVED** [review]
:shipit:

**Review by lgfa29 — COMMENTED** [review]
Sorry, late to the party 😅 

Minor comment on the tests, but definitely not a blocker. But maybe something we should fix in a follow-up PR.

**Pull request merged**
