### PR TITLE
Add guards around subtracting summary count

### PR DESCRIPTION
**Pull request by preetapan**
This PR adds a check such that job summary counts won't be set to negative numbers.

### CODE REVIEW

**Comment by notnoop** [comment]
if we go with this approach, i'd suggest logging so we can be in the look out and have more debugging information if it happens again.

**Comment by jippi** [comment]
in my experience, the job summary count is pretty rarely accurate without triggering a `reconcileSummary` across all versions of nomad

**Comment by tantra35** [comment]
IMHO this fix is incorrect, and doesn't solve problems  when job summary disappear when server leader moves to another nodes, see last comments in issue https://github.com/hashicorp/nomad/issues/4731

**Comment by tantra35** [comment]
@preetapan your colleague @schmichael absolutely right, this PR solve issue only on half, and as i mention before doesn't solve problems when leader server moves to another node. Please take account on this

**Pull request merged**
