### PR TITLE
CHANGELOG entries for some 1.0.4 UI bug fixes

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Trying to slip these in in time 😅

### CODE REVIEW

**Review by backspace — APPROVED** [review]
I don’t know how important this really is but it’s been suggested to me to keep each section sorted by length, from shortest to longest, so you could update that if you want to follow that convention, but there are a lot of other inconsistencies already so I’ve generally just Let Go™ haha

**Comment by DingoEatingFuzz** [comment]
From shortest to longest? I think I once heard the exact opposite. But also yeah, we're inconsistent at this point 🙈

**Comment by DingoEatingFuzz** [comment]
Okay okay, viewing the older releases in this file makes it clear that shortest to longest is indeed the original format that we have since been deviating from. Will change.

**Comment by tgross** [comment]
cherry-picked to release-1.0.4

**Pull request merged**
