### PR TITLE
Add Portworx CSI Driver example

### PR DESCRIPTION
**Pull request by ggriffiths**
Signed-off-by: Grant Griffiths <ggriffiths@purestorage.com>

### CODE REVIEW

**Comment by mikenomitch** [comment]
Hey @ggriffiths, thanks for the addition. The format and files look good generally, but I tried running this locally and ran into some issues.

* Can you clarify that volumes need to be enabled in the client config and add the example stanza. This will be obvious to Nomad power users, but for first timers, this might be nice to be explicit about.

* I ran into an error when running the controller job "API error (500): Mounts denied: The path /opt/pwx is not shared from the host and is not known to Docker." - I ended up tweaking my docker preferences to share the host, but I'm not positive I did this right. Can this be documented?

* I'm running into an error trying to launch this locally. I think this might be because I'm trying this with a single alloc on dev mode?

```time="2021-08-03T18:14:29Z" level=info msg="Input arguments: /px-oci-mon -c px-cluster-nomadv1 -a -k consul://127.0.0.1:8500 --endpoint 0.0.0.0:9015"
time="2021-08-03T18:14:29Z" level=info msg="Updated arguments: /px-oci-mon -c px-cluster-nomadv1 -a -k consul://127.0.0.1:8500" install-opts=--upgrade
time="2021-08-03T18:14:29Z" level=info msg="OCI-Monitor computed version v2.8.0-gd252e59e-dirty"
time="2021-08-03T18:14:29Z" level=info msg="REAPER: Starting ..."
time="2021-08-03T18:14:29Z" level=info msg="> run-host: /bin/sh -c systemctl show-environment"
time="2021-08-03T18:14:29Z" level=info msg="> run-host: /bin/sh -c initctl version"
time="2021-08-03T18:14:29Z" level=error msg="No suitable service controller for this platform and/or mounts configuration"
time="2021-08-03T18:14:29Z" level=error msg="Could not init service controls: Could not initialize service controller"```

I can retry on a real cluster, but related question - it looks like consul is a requirement based on these logs. If that is the case, can you document this as well?

**Comment by ggriffiths** [comment]
Thanks for the review @mikenomitch! I need to double check on a few of the questions you've asked. For now, I've updated the PR based on the questions you have. I will follow up when I've validated some of these assumptions. 

> Can you clarify that volumes need to be enabled in the client config and add the example stanza. This will be obvious to Nomad power users, but for first timers, this might be nice to be explicit about.

Yes, good catch, I added the client config.

> I ran into an error when running the controller job "API error (500): Mounts denied: The path /opt/pwx is not shared from the host and is not known to Docker." - I ended up tweaking my docker preferences to share the host, but I'm not positive I did this right. Can this be documented?

We run as a privileged container, so explicit access provided to `/opt/pwx` should not be needed after that.

> I'm running into an error trying to launch this locally. I think this might be because I'm trying this with a single alloc on dev mode?

We typically always test with 3+ nodes. Let me check if less is possible for Nomad.

> I can retry on a real cluster, but related question - it looks like consul is a requirement based on these logs. If that is the case, can you document this as well?

Yes, I'm checking if we can run without consul for Nomad. We do for K8s, but I believe we require consul for Nomad.

**Comment by ggriffiths** [comment]
Just validated the above assumptions @mikenomitch. Ready for a re-review.

**Comment by schmichael** [comment]
Thanks contributing this @ggriffiths! I pushed a little intro to the README.

I'm getting an error when trying it in a 3 node cluster on AWS:

> time="2021-08-10T18:36:37Z" level=error msg="USAGE ERROR: Please supply extra options to generate spec file"


https://gist.github.com/schmichael/e5451abd197eaea8f60f2de08955cc63#file-out-stderr-L45

**Comment by ggriffiths** [comment]
@schmichael of course! Apologies that the original spec did not work. I've updated it to add the dependency on consul back in. It assumes consul is running locally on each node at `consul://127.0.0.1:8500`.

The new .hcl spec should work if consul is setup this way.

**Comment by schmichael** [comment]
When I run `portworx-csi-plugin.hcl` the Consul health check is failing for me with:

> HTTP GET http://172.31.1.164:9015/health: 503 Service Unavailable Output: Get http://127.0.0.1:9001/v1/cluster/nodehealth: dial tcp 127.0.0.1:9001: connect: connection refused

Was hoping to get you more debugging info but ran out of time today, sorry. Not sure where that port 9001 is coming from.

**Comment by schmichael** [comment]
Hi @ggriffiths, we're changing our policy on these demos to try and help them land more quickly and easily:

I've added you in the README in an `Author: ...` field so that others can tag you on issues and PRs related to the demo. That way we can get demos onto main faster and iterate from there.

If you'd prefer not to, please just open a new PR or let me know! Thanks for the contribution and sorry it's taken so long to merge.

**Review by schmichael — APPROVED** [review]

**Comment by ggriffiths** [comment]
No problem @schmichael, I meant to respond earlier but never got around to it. Thank you for the review and trying it out!

**Pull request merged**
