### PR TITLE
Support docker syslog unixformat and defaultformat

### PR DESCRIPTION
**Pull request by a86c6f7964**
for #1386

### CODE REVIEW

**Comment by diptanu** [comment]
@a86c6f7964 Did you test this for older versions of docker?

I was thinking that we can do separate parsers for different versions the code will be clearer. I am assuming they are going to change this again in the future.

**Comment by a86c6f7964** [comment]
I did test on older version, plus the unit test that I edited tests the old version of the log line. Feel free to close this if this you would rather take that approach, I was just trying to make the change with the least impact to the rest of the code.

**Comment by diptanu** [comment]
After thinking about this more, we can't initialize the parser based on the current version of docker. Users might upgrade the docker daemon without restarting the client in which case the format of the data being streamed to the syslog server is going to change.

**Comment by diptanu** [comment]
@a86c6f7964 Merging this PR, thanks!

**Pull request merged**
