### PR TITLE
Remove restrictions from docker networking mode

### LINKED ISSUE #431: Support docker with user created network (docker network create)
With the release of Docker 1.9, it is possible to provide  a user-created network (docker network create):

```
--net="bridge"   : Connects a container to a network
                    'bridge': creates a new network stack for the container on the docker bridge
                    'none': no networking for this container
                    'container:<name|id>': reuses another container network stack
                    'host': use the host network stack inside the container
                    'NETWORK': connects the container to user-created network using `docker network create` command
```

The user-defined network is too convenient in that it is possible to wire up different links among containers (across different hosts) without mess up with Docker's default docker0 bridge. With user-created network and plugin, it is much easier to integrate a customized networking solution with docker.

However, it seems that nomad at the moment only support 'bridge', 'host', or 'none' mode in client/driver/docker.go. 

Is there any plans to add user-defined network option ('NETWORK') to nomad in the near future?

### PR DESCRIPTION
**Pull request by cbednarski**
This unblocks container networking mode as well as custom networking plugins in Docker 1.9.

There's no validation so we assume users know what they are doing.

Supports #371
Closes #431

### CODE REVIEW

**Comment by dadgar** [comment]
LGTM. The docs need to be updated either in this PR or follow up

**Comment by napolenli** [comment]
@cbednarski Hello, would you like to tell me how should I use this feature in app.nomad file? Thanks!

**Comment by napolenli** [comment]
And also, @dadgar sorry for bothering you again... how to do this exactly?

**Comment by dadgar** [comment]
@napolenli Hey you can see an example here: https://www.nomadproject.io/docs/drivers/docker.html#network_aliases

It is simply: 

```
task "foo" {
  driver = "docker"
  config {
     ...
     network_mode = "<user_network>/bridge/host"
   }
}
```

**Pull request merged**
