### PR TITLE
build: update gomod go version

### PR DESCRIPTION
**Pull request by shoenig**
Keep go.mod go version up to date with the version of Go used
to build Nomad.

### CODE REVIEW

**Review by tgross — APPROVED** [review]
LGTM 👍

**Review by notnoop — APPROVED** [review]
LGTM.  Is the issue requiring us to vendor dependencies still relevant with new go version?  Don't recall the context well.

**Comment by tgross** [comment]
We should probably update https://github.com/hashicorp/nomad/blob/master/tools/go.mod#L3 as well.

**Comment by shoenig** [comment]
@notnoop if you're referring to the need to vendor the `api` submodule, that's a "feature" starting with go1.14 https://github.com/golang/go/issues/33789

Otherwise, we're still vendoring dependencies until the artifactory computes checksums correctly (AFAIK)

**Pull request merged**
