### PR TITLE
Document new `expirationDate` prop for AlertBanner

### PR DESCRIPTION
**Pull request by pruett**
[Asana](https://app.asana.com/0/0/1198562802487554/f)

Adds an example of the `expirationDate` prop associated with the `<AlertBanner/>` component, in order to help expose this "feature" to future contributors.

### CODE REVIEW

**Review by jescalan — APPROVED** [review]

**Comment by mwickett** [comment]
This needs to be targeted to `master` and then cherry picked to `stable-website` - just flagging that.

**Review by mwickett — APPROVED** [review]

**Comment by mwickett** [comment]
I have #9158 stacked off of this PR, so once it's rebased and merges, I'll rebase mine and then these can both be cherry-picked over together.

**Comment by pruett** [comment]
@mwickett Just to clarify, did you want me to merge this into `master` (once all checks run)? or did you want me to tack on your commit into this PR before merging?

**Comment by mwickett** [comment]
@pruett Actually yeah, that'd be great if you could just bundle it all up. And yes, it has to go to `master` first, then be cherry picked over to `stable-website`. Thanks!

**Pull request merged**
