### PR TITLE
Draft: Add CPU in MHz to stats and emit nomad.client.allocs.cpu.total_mhz metric

### LINKED ISSUE #11142: Provide CPU metrics in MHz
https://www.nomadproject.io/docs/operations/metrics

The metric `nomad.client.allocs.cpu.total_ticks` is in ticks, but there's no metric for MHz used (although there's one for MHz allocated) making it hard to relate the the resources in the *nomad file's resource stanza.

Also the doc page doesn't specify if the Percentage values are 0~100 or 0~1.0 based

### PR DESCRIPTION
**Pull request by conorevans**
Signed-off-by: Conor Evans <coevans@tcd.ie>

Resolves #11142

This is a draft PR as I would like to get feedback if I've gone awry. I wasn't sure how the driver.pb.go file gets updated (I see a reference in the makefile but wasn't sure if that gets run as part of PR). I couldn't see any instructions as to regenerating it locally.

### CODE REVIEW

**Comment by DerekStrickland** [comment]
Hi @conorevans 

Thanks for this and the other contributions!  We'll get them in the pipeline for review!

**Review by tgross — COMMENTED** [review]
Hi @conorevans! The overall approach here looks ok. 

If you have `buf` installed (as per make deps` or just `go install github.com/bufbuild/buf/cmd/buf@v0.36.0`), you can run `make proto` and that should regenerate the protobuf file. Once that's done we can review the implementation in detail.


I'm a little concerned about how showing MHz works in practice given CPU frequency scaling... are we going to be giving users completely misleading metrics? But maybe we can assume that if you're using MHz for your metrics that you also know what's going on with CPU frequency scaling? Not sure.

**Comment by TrueBrain** [comment]
While I was fiddling a bit how to get the MHz as a counter, I noticed this PR. Maybe a silly question, and I might misunderstand the code: but isn't `total_ticks` already in MHz? `TotalTicksAvailable` returns `cpuTotalTicks` which is calculated as `cpuTotalTicks = math.Floor(float64(cpuNumCores) * cpuMhzPerCore)`, which is the same `CPUMHzTotal` returns?

Mainly I think `ticks` is a bit ambiguous, as one could think they are jiffies; but they are not.

Again, not that into the Nomad code, so might misunderstand things, but just wanted to leave this here :)

**Comment by tgross** [comment]
Yeah I think you're right there @TrueBrain. Let's get your PR #17579 in to get this done.

**Pull request closed without merging**
