### PR TITLE
[demo] Kadalu CSI support for Nomad

### PR DESCRIPTION
**Pull request by leelavg**
- Access external gluster cluster from Nomad via Kadalu CSI

Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

**Comment by leelavg** [comment]
- Please suggest any changes wrt Nomad
- Any changes wrt Kadalu will be tracked in https://github.com/kadalu/kadalu/pull/659

**Comment by leelavg** [comment]
Please review @tgross if you get time. Thanks.

**Comment by jrasell** [comment]
Hi @leelavg and thanks for raising this PR. Tim no longer works at HashiCorp, however, a member of the team will review this PR when possible.

**Comment by apollo13** [comment]
@leelavg This looks interesting. How are you handling updates though? Last time I checked glusterfs has a fuse based driver and as such upgrading the node pods will result in all mounts of the node getting lost.

**Comment by leelavg** [comment]
@apollo13 

1. yep, that is still the case for all fuse based drivers (in k8s too, yet to reach a consensus ig https://github.com/kubernetes/kubernetes/issues/70013)
2. generally, we need to drain the node for specific pods (if that's possible at all) which are consuming PVs from that specific nodeplugin and upgrade nodeplugin on that node and perform uprades for remaining pods in the same way
3. basically rolling update of each node but before update drain pods which are using volume from that node
4. I also took a stab at it in Kadalu (https://github.com/kadalu/kadalu/pull/645) but couldn't quite make that work yet (even this implementation also has shortcomings, as in, pods loose mount for a brief period of time)
5. So, should the demo include I/U as well? In that case it's going to stay here for long 😞
6. Gist is, if nodeplugin is fuse based and if it reboots/upgrades, pods will definitely loose the mount, no way around it yet (or at-least I'm not aware of any common solution).

PS: Pls don't mind k8s terminology, muscle memory 😅

**Comment by apollo13** [comment]
Thanks, that makes sense. The main blocker I see here (for me personally, I am not a nomad team member) is that it is currently (afaik) not really possible to upgrade node by node. This is the reason why I export my glusterfs via nfs-ganesha and use NFS to mount it: https://gitlab.com/rocketduck/csi-plugin-nfs -- this works nicely since NFS is a kernel driver and as such I can just upgrade the system job running the node plugins.

**Comment by leelavg** [comment]
- Cool, that's a good workaround. It adds an extra layer of dependency though but I get the need 😅 
- Can you provide the config/job files that you are using, if they are public?
- We are also planning for SMB export (with gluster managed by k8s) and guess NFS support is also doable, however fuse driver offers good latency ig
- Will ask one of the maintainers to comment about NFS functionality if we were to enhance Nomad support to use gluster deployed and managed internally in containers using Kadalu.
- Until then, it is what it is, this PR demos another CSI support for Nomad.

Thanks for your inputs.

**Comment by apollo13** [comment]
This is the config for nomad: https://gitlab.com/rocketduck/csi-plugin-nfs/-/tree/main/nomad and the nfs-ganesha jobfile looks like this:
```
EXPORT
{
	Export_Id = 1;
	Path = "/nomad";
	Pseudo = "/nomad";
	Access_Type = RW;
	Squash = No_Root_Squash;
	SecType = "sys";

	FSAL {
		Name = "GLUSTER";
		Hostname = localhost;
		Volume = "nomad";
        Up_poll_usec = 10;
        Transport = tcp;
	}
}
```
It is indeed an extra layer, but one that I need :)

**Comment by apollo13** [comment]
> ig, setting network_mode to host (from nfs repo) in attached job files also might work during reboots (not sure though).

It is also required so the mount survives pod updates, otherwise the underlying source ip for the nfs mount is no longer available on the host :D

**Comment by leelavg** [comment]
@lgfa29 definitely, I've raised this PR for visibility of CSI projects supporting Nomad.

I specifically mention in the README to contact kadalu team for any issues.

Will tag the author as me but I anticipate users to raise CSI issues against Kadalu repo and someone from Kadalu will raise issue against Nomad if needed.

**Review by lgfa29 — APPROVED** [review]
Thank you @leelavg for the contribution and @apollo13 for the feedback!

I made some minor changes to the text formatting and will get this merged. Feel free to open any follow-up PRs if I messed up anything 😄

**Pull request merged**
