### PR TITLE
Fix docker user specified syslogging

### PR DESCRIPTION
**Pull request by dadgar**
Fixes https://github.com/hashicorp/nomad/issues/3182

### CODE REVIEW

**Comment by shantanugadgil** [comment]
Hi,
I did the following:

```
git checkout b-docker-logging
git pull
git log -p
make pkg/linux_amd64/nomad
```

Copied the binary to one of my client machines.
Logs appear correctly when I stop and start the service, but Nomad keep crashing upon startup.
Possibly related to https://github.com/hashicorp/nomad/issues/3188
(FWIW, I have stats reporting to a statsite enabled).

For now, I am reverting to version 0.6.2 GA

**Comment by dadgar** [comment]
@shantanugadgil can you build off of stable-v0.6.3 branch. Master isn't stable right now

**Comment by shantanugadgil** [comment]
just confirming; I too am seeing the same traceback:
```
2017/09/11 06:38:27 [INFO] (runner) creating new runner (dry: false, once: false)
fatal error: sync: RUnlock of unlocked RWMutex
goroutine 356 [running]:
runtime.throw(0x146faf6, 0x21)
...
```

@dadgar ok, I'll try building from `stable-v0.6.3`.

Q: But your syslog fix isn't merged to the branch `stable-v0.6.3`, right?

**Comment by dadgar** [comment]
You should be able to rebase it onto the stable branch or cherry pick the commit.

**Comment by dadgar** [comment]
Can you post the full stack trace as well! Thank you

**Comment by shantanugadgil** [comment]
[nomad_0.6.3_traceback.txt](https://github.com/hashicorp/nomad/files/1292494/nomad_0.6.3_traceback.txt)

**Comment by shantanugadgil** [comment]
@dadgar I chery picked the single commit from `b-docker-logging` into `stable-v0.6.3` and can see the logs on the central server correctly.

**Comment by shantanugadgil** [comment]
hi @dadgar  @schmichael 
this hasn't made its way into 0.6.3 GA right?
because I am seeing the same behavior with the 0.6.3 that I downloaded.
reverting to the file I have compiled myself works as expected with the logs appearing on the central server?

Regards,
Shantanu

**Comment by dadgar** [comment]
@shantanugadgil Ah shoot. I am sorry I forgot to cherry pick that commit into the branch! 0.7.0 will be out soon, sorry about that.

**Comment by shantanugadgil** [comment]
Thanks for the confirmation! Till 0.7.0 is out, I'll live with the file I have! 😄

**Comment by shantanugadgil** [comment]
Hi @dadgar 
just wondering if this is in the 0.7.0 branch (?)
Asking as I didn't see it in the changelog 
https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md

_waiting for 0.7.0 with much anticipation!_ 👏  👏 😁

**Comment by dadgar** [comment]
@shantanugadgil Added to changelog

**Pull request merged**
