### PR TITLE
Update go-getter@1.1.0 to fix #3491

### LINKED ISSUE #3491: nomad run example.nomad requires Admin privileges on Windows
### Nomad version

```
Nomad v0.7.0-rc3
```

### Operating system and Environment details

Windows Server 2016

### Issue

`nomad run example.nomad` fails with a permission error.

### Reproduction steps

In a non-admin powershell:

```
nomad init
nomad run example.nomad

Error getting job struct: Error getting jobfile from "example.nomad": symlink C:\Users\mschurter\go\src\github.com\hashicorp\nomad\example.nomad C:\Users\MSCHUR~1\AppData
\Local\Temp\2\jobfile712770031: A required privilege is not held by the client.
```

It appears the way hashicorp/go-getter is used to copy the jobfile into a temporary file doesn't work on Windows.

### PR DESCRIPTION
**Pull request by hmalphettes**
As reported in #3491, `nomad run example.nomad` on windows without the symbolic link creation privileges fails.

As suggested in hashicorp/go-getter#159, a workaround was added to the go-getter source.
However go-getter in nomad has not been updated to benefit from this fix.

This pull request is an update to go-getter.

I have tested that it does fix #3491 
Thanks @azr for the actual fix in go-getter!

### CODE REVIEW

**Comment by hmalphettes** [comment]
For now staying at v1.1.0 of go-getter to keep the actual change limited to changes in the `vendor/github.com/hashicorp/go-getter/` folder.

Later versions of go-getter require to add to the vendor folder cloud.google.com/api and cloud.google.com/go and are not required to fix the Windows issue.

**Comment by greut** [comment]
iirc `make dev` should reformat the vendor.json file to keep the diff easy on the eye.

**Comment by hmalphettes** [comment]
Thanks @greut ! Fixed that.

**Comment by schmichael** [comment]
Thanks @hmalphettes ! I think you just got unlucky on some flaky tests. Sorry. Trying again.

I think we want to wait to merge this into 0.10.0 (which will become master once 0.9.4-final is released) at which point let's pull in the latest release (looks like v1.3.0 instead of v1.1.0).

**Comment by hmalphettes** [comment]
Thanks @schmichael!

In the mean time, if it is useful for someone - and you happen to trust my own build of nomad - I uploaded a windows build with this patch: https://github.com/hmalphettes/nomad/releases/tag/v0.9.4-rc1h
My colleagues  and I are happily using it from our locked-down windows machines to prototype the jobs.
I'll update it when 0.9.4 is released.

If this is not good community etiquette to point at my build, please do delete this comment or let me know.

**Comment by schmichael** [comment]
Thanks @hmalphettes ! Merged. Linking to forks and prebuilt binaries is great as long as you make it clear it's a fork (which you did).

**Pull request merged**
