### PR TITLE
Update the vagrant file

### PR DESCRIPTION
**Pull request by cbednarski**
- Automatically CD into the working directory after `vagrant ssh`
- Install docker idempotently
- Install dependencies inside the VM
- Consolidate memory and CPU options for various VM providers

### CODE REVIEW

**Comment by catsby** [comment]
LGTM, any specific reason you cut the memory in half?

**Comment by cbednarski** [comment]
@catsby I made this consistent with Parallels, so if you have several VMs running or are on a resource constrained laptop (like an Air) we don't use all of your memory. I tweak this locally to 2048 but if 1024 actually causes problems we can increase it. Thoughts?

**Comment by catsby** [comment]
SGTM, was just curious

On Tue, Oct 27, 2015 at 4:44 PM, Chris Bednarski <notifications@github.com>
wrote:

> @catsby <https://github.com/catsby> I made this consistent with
> Parallels, so if you have several VMs running or are on a resource
> constrained laptop (like an Air) we don't use all of your memory. I tweak
> this locally to 2048 but if 1024 actually causes problems we can increase
> it. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/nomad/pull/350#issuecomment-151654839>.
>



-- 
Clint

**Comment by dadgar** [comment]
LGTM. I would double the RAM but either way

**Comment by cbednarski** [comment]
Updated RAM to 2048

**Pull request merged**
