### PR TITLE
ci: Migrate remaining jobs to CircleCI

### PR DESCRIPTION
**Pull request by endocrimes**
- The UI Job had already been replaced in CircleCI
- Added the test-e2e and test-website jobs
- Added the remaining lint step to lint-go

### CODE REVIEW

**Comment by notnoop** [comment]
The changes lgtm.  Though, I'd like to get a prospective on CircleCI build stability.  

I still consult Travis and compare it to CircleCI, as anecdotally, I've seen some stability issues until recently.  `test-exec` was super unreliable in circleci, which hopefully was fixed in https://github.com/hashicorp/nomad/pull/6219 .  `lint-go` also seemed unreliably and i've seen it failing unexpectedly frequently in my and some other branches, e.g. https://circleci.com/gh/hashicorp/nomad/4509 and https://circleci.com/gh/hashicorp/nomad/4293 .

Do you have some prospective or basic analysis for how flaky CircleCI builds are yet?

I'd suggest adding more circleci jobs now, and let them soak a bit more before completely removing Travis.

**Comment by endocrimes** [comment]
@notnoop We removed the rest of the Go tests from travis yesterday - but anecdotally I've seen much less problematic flakiness from circle since upgrading to the newer machine

**Comment by endocrimes** [comment]
@notnoop WRT issues with lint-go, 4509 is the only one I've since on branches since `GOMAXPROCS=1` was set (the branch associated with 4293 is quite old I think)

**Comment by notnoop** [comment]
Sounds good - thanks for the context.

**Comment by marcomorain** [comment]
❤️

**Pull request merged**
