### PR TITLE
UI: Change Mirage data to be stable in development

### PR DESCRIPTION
**Pull request by backspace**
This sets a default-but-query-configurable Faker seed in development,
via `faker-seed`. It also changes uses of `Math.random` to use Faker’s
randomness so auto-generated data remains stable in development.

### CODE REVIEW

**Comment by backspace** [comment]
Some implementation notes:

1. It’s not necessary to have everything import Faker from `nomad-ui/mirage/faker`. `mirage/common.js` is the place that first uses Faker and that could be the place where the seed-setting occurs. I have a slight preference for this approach because it seems conceptually clearer despite not actually working differently. But it’s easy to change to having the seed-setting in `common`.

2. I made the seed configurable via a `faker-seed` query parameter. The default is `1`, but it’s only set when the environment isn’t `test`. If you want a seed in tests, `faker-seed` works there too. You can see an example seed override [here](https://deploy-preview-6389--nomad-ui.netlify.com/ui/jobs?faker-seed=2).

**Comment by backspace** [comment]
1. Seeding Faker in `mirage/config.js` would seem most appropriate to me, but doing it there means some data has already been randomised, sadly. It’s my belief that files are processed in alphabetic order, which is why setting the seed in `mirage/common.js` worked when I didn’t have it in its own file. I could still move it there but it seems less obvious than `config`, sadly.

2. Check out e92d846; it turns out that setting a seed of `0` for Faker actually makes it use a random seed. Does it seem acceptable to use that (documented) magic number rather than have another query parameter?

**Comment by DingoEatingFuzz** [comment]
The `faker-seed=0` trick is good enough for me, especially since you documented it.

As for where to seed faker, it's certainly more important to not have unwanted randomness sneak in, so I'm cool with carrying on with the way you implemented things.

**Comment by backspace** [comment]
This sets a default-but-query-configurable Faker seed in development,
via faker-seed. It also changes uses of Math.random to use Faker’s
randomness so auto-generated data remains stable in development.

**Pull request merged**
