### PR TITLE
UI: Reset page query param on search

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Fixes a search + pagination bug.

**Current behavior**
1. Visit a page with a paginated table
2. Click "next page"
3. Search for anything
4. See that there are supposed to be results, but none are shown because you are still on page 2

**New behavior**
1. Visit a page with a paginated table
2. Click "next page"
3. Search for anything
4. See the results because searching takes you back to page 1

### CODE REVIEW

**Comment by johncowen** [comment]
Hey,

I was just trying this out with a `smallCluster` changed to 30 jobs. I was wondering if, as a extra bit of detail, it would only jump back to page 1 if there are no items on the page I'm currently on. So say I search and get 20 results, and click to go to page 2, then refine my search slightly by adding a further letter and I get 15 results, do I want to be auto navigated back to page 1, or would I rather stay on page 2? To put it shorter, should it only go back to page 1 if there are no items on the page you are on?

Refinement suggestion more than anything.

Thanks

**Comment by DingoEatingFuzz** [comment]
IMO it should always go back to page one. Since the search results are sorted by relevancy, refining the search and not being one page one means you aren't seeing the most relevant results.

**Comment by DingoEatingFuzz** [comment]
I just double checked what various sites do (google, duckduckgo, gmail, github) and they all reset pagination.

**Comment by johncowen** [comment]
Cool, good point, thanks for looking into it!

**Pull request merged**
