### PR TITLE
updated to latest hashicorp/raft and hashicorp/memberlist to pull

### PR DESCRIPTION
**Pull request by cgbaker**
upstream fixes for accept-loop error handling

### CODE REVIEW

**Comment by preetapan** [comment]
@cgbaker curious why is the btree dependency in this PR

**Comment by cgbaker** [comment]
> @cgbaker curious why is the btree dependency in this PR

because some commits from @rboyer pulled it in. i can backdate this dependency to just pull in my work on the accept loop if we want to pull in the minimal changes, but i figured we should move forward from master HEAD.

**Comment by rboyer** [comment]
If you are updating memberlist you should also update serf to pickup: https://github.com/hashicorp/serf/pull/545

**Comment by preetapan** [comment]
ah yeah I remember that performance update from @rboyer now. Makes sense for us to update all three libs now rather than partially bring in just memberlist and raft.

**Comment by cgbaker** [comment]
updating serf now

**Pull request merged**
