### PR TITLE
Pin docker version

### PR DESCRIPTION
**Pull request by greut**
- pin docker/docker (as docker/engine)
- pin aws/aws-sdk-go
- pin opencontainers/runc

### CODE REVIEW

**Comment by notnoop** [comment]
Thanks @greut mind if you provide some background or context for this PR?  We pin our dependencies in vendor/vendor.

Also this seems to vendors some dependencies that aren't used anywhere - for example, this vendors packages `gotest.tools/assert` and `gotest.tools/icmd` yet no other package references them:

```
$ git grep -l -e gotest.tools/assert  -e gotest.tools/icmd
vendor/gotest.tools/assert/assert.go
vendor/gotest.tools/assert/cmp/compare.go
vendor/gotest.tools/assert/result.go
vendor/gotest.tools/icmd/command.go
vendor/vendor.json
```

**Comment by greut** [comment]
@notnoop it's pinned to commits rather than version... I'm discovering govendor (hard). My goal was to use docker/docker/client rather than go-dockerclient. The whole refactoring required for the go modules transition is way too hard for now.

**Comment by nickethier** [comment]
Hey @greut!
First off, thanks for contributing! Whats the reasoning behind change docker api clients? `go-dockerclient` has served us well and (to my knowledge) isn't the source of any existing bugs. Switching it out now seems like a pretty high risk change for no gain. Just trying to understand and build some context around these changes. Thanks!

**Comment by greut** [comment]
it's a bit of a mess. Lemme try differently.

**Pull request closed without merging**
