### PR TITLE
UI: Add acceptance test accessibility auditing and fixes

### PR DESCRIPTION
**Pull request by backspace**
This is a first pass at incorporating axe/ember-a11y-testing and addressing some failures it catches. The commits can be read in order, they:
1. introduce the addon
2. set up a helper wrapper to ignore all initial rule violations
3. add the wrapper to acceptance tests
4. fix violations of one rule per commit

The wrapper for the `a11yAudit` helper let me globally skip certain axe rules for now:
* [`color-contrast`](https://dequeuniversity.com/rules/axe/3.5/color-contrast), which will be a significant undertaking to address but also self-contained and appropriate for a separate PR
* [`heading-order`](https://dequeuniversity.com/rules/axe/3.5/heading-order), which ensures that `h1` to `h6` are always in order and don’t skip levels, I need to look more into how people handle this in dynamic applications

I chose to only add accessibility audits to acceptance tests for now, but will proceed with component tests in a subsequent pull request. Some other things to address/survey (in addition to the above):
* tabbing into the CodeMirror component traps the cursor there, you can’t tab out
* the CodeMirror component also fails [`scrollable-region-focusable`](https://dequeuniversity.com/rules/axe/3.5/scrollable-region-focusable), there’s a targeted exception for that rule
* the possibility that randomness in test data will cause intermittent failures that aren’t fixed in this PR
  * for instance, I could only reliably reproduce the `scrollable-region-focusable` failure when I ensured the job definition was long enough that it would cause the container to be scrollable
* the placeholder in the token-setting field gets read aloud by VoiceOver
* a general overview of the experience of using the interface with VoiceOver to uncover other problems

The documentation shows adding a [separate test for the audit](https://github.com/ember-a11y/ember-a11y-testing#acceptance-tests), which is also the route Terraform Cloud is taking, but I’m torn about it… I wonder whether it might make more sense to include in an existing test, similarly to how there are assertions on `document.title` in most acceptance test files’s first tests. I’m leaning toward that direction but want to check in before doing it.

One possibility I looked into was adding a custom ESLint rule that would check each acceptance test file to ensure it uses the helper at least once. Does this seem worth it? 🤔

### CODE REVIEW

**Comment by backspace** [comment]
👍 thanks, I’ll change it around to have the audits in the existing tests.

re ESLint, it seemed to me to not be too difficult, I think there are some rules I can take inspiration from, I’ll make a timeboxed attempt 😀

**Comment by backspace** [comment]
oh oops maybe we’re talking about slightly different things re my question about where the audits should happen. I followed the suggestion of the documentation in adding a separate test into each acceptance test file (almost), but I was asking about whether it would make more sense to add the `a11yAudit` to existing tests inside the file instead of having a separate `it passes an accessibility audit` test. I am slightly irked by it being separate and especially the `assert.ok(true, 'a11y audit passes')` that is only present (from what I can tell) to have a non-zero assertion count that QUnit errors on. I think putting the audit around where `document.title` is asserted on could work too.

**Comment by DingoEatingFuzz** [comment]
Ah, I see what you mean now. I think it's good the way it is?

If I understand correctly, when a page doesn't pass the audit, then `await a11yAudit();` throws an error and that's how the test fails?

If that's the case, then I think it's helpful to know that `it passes the accessibility audit` is the test that fails rather than `correct page title` or whatever. A theoretical `assert.noThrow` would be nice for this, lol.

**Comment by backspace** [comment]
The `assert.ok` is only there so you don’t need `assert.expect(0)`, I believe. I think something like this would be nicer particularly for tests that require duplicate Mirage setup:

image

I pushed a [commit](https://github.com/hashicorp/nomad/commit/70443ddd1f7267271ff900e92d6159c78a4a2778) with that and a deliberate accessibility violation and you can see that the [test fails](https://app.circleci.com/pipelines/github/hashicorp/nomad/10789/workflows/fcea9718-c086-4967-a9f5-bc75d51a6c86/jobs/86737/tests) without needing the `assert.ok`.


Unrelatedly, re ESLint, you saw that I got that PR merged, but I’ll make a separate PR to use it in Nomad 😀

**Comment by DingoEatingFuzz** [comment]
My concern is around the presentation of errors given that the underlying failure condition is a promise error rather than an assertion error. Note the title differences in these two error cards.

image

But fewer lines of code is always compelling, and the error message body still says it's accessibility related, so maybe I'm just overthinking things.

**Comment by backspace** [comment]
hmm yes, the test name does help emphasise… well I’ll merge for now, can always change later!

**Pull request merged**
