### PR TITLE
Rename GNUMakefile to Makefile

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by shantanugadgil** [comment]
I think the name should be kept as GNUMakefile.

I thought keeping it GNUMakefile was with the explicit intent (clarity) of needing GNU Make on all platforms.

Is the current GNUMakefile is compliant with the other makes? (only Mac for now)

Also, I wonder if the Travis CI build is showing results for other platforms.
From what I see the build is only on an Ubuntu 14.04 Linux.
(Apologies, if any errors, not an expert at Travis CI).

If and when Nomad can be built on other platforms like FreeBSD, Solaris(?), etc. having the file named GNUMakefile would make it obvious that "GNU Make" is required rather than having to deal with issue with OS specific make.

Regards,
Shantanu

Regards,
Shantanu

**Comment by sethvargo** [comment]
From the docs:

> The first name checked, GNUmakefile, is not recommended for most makefiles. 

As far as I know, we aren't using any GNU make-isms that wouldn't work on other systems, although that's not something we explicitly support. I believe the doc recommends that naming convention iff you're using Makefile syntax or builtins that aren't part of standard make. I do not think we are. The spec says nothing about whether the underlying software itself will build on other platforms. 

Additionally, we list supported OSes and platform requirements in the development section. I think that's significantly better than a special file naming convention that very few people are privy to :).

I think it's a bit of a silly bikeshed argument that isn't actually going to matter in the grand scheme of things. Most users will consume Nomad via the pre-compiled packages. Others can use the provided Vagrantfile to avoid OS-specific things. At the end of the day, we have to choose whether we want to spend a sprint building a completely cross-platform makefile for a small percentage of users to build from source or develop and awesome new feature. This rename is a perfect example of that type of balance.

**Comment by schmichael** [comment]
@sethvargo LGTM! Thanks for finally doing this!

@shantanugadgil like Seth said: our makefile is awfully simple, so I doubt we're incompatible with other systems. I'd be more than happy to accept PRs if we are. At 77 lines I would maintaining a broadly compatible makefile won't be too difficult.

**Comment by jen20** [comment]
There are no GNU specific constructs that I can see in the existing Makefile, though the one introduced in #2953 definitely has use GNU-specific behaviour.

**Comment by jen20** [comment]
Actually, I'm wrong. The [very first line](https://github.com/hashicorp/nomad/blob/9f2ea92877ed655063a5ecf6bb22b7703bc2cea2/Makefile#L1) of the Makefile uses the GNU Make specific `shell` function - this should be reverted if platform compatibility is a concern for Nomad. If it is not, can that be made explicit in order that developers do not waste time in future trying to contribute cross-platform support?

**Comment by shantanugadgil** [comment]
@schmichael @sethvargo 

In the past, I have had the pleasure of maintaining a software which was cross platform (Linux x86_64, Solaris x64/SPARC, HPUX, AIX). The Makefile for each platform had already been written long ago.

While _trying_ to enhance the build system, I always felt that having a **prerequisite** of GNU Make was far-far simpler than having to know oddities of each make!

That said, I am not too upset 😀  by this change. Just wanted to let you know my thoughts!

Cheers!
Shantanu

**Comment by jen20** [comment]
I don't disagree at all - writing for GNU Make is a good idea (see #2953 for example 😉). That said, the justification for the incorrect renaming here is "we don't use any GNUisms", which is false, since there is one in the first seven characters of the file. Therefore, it should be named accordingly.

**Comment by schmichael** [comment]
Good call. Reverted back to GNUmakefile.

**Pull request merged**
