### PR TITLE
Add metadata to namespaces

### LINKED ISSUE #9631: [feature request] Support for namespace metadata tags
It would be useful to support key/value metadata tags in namespace API definition. 

The use case is for example for billing tags or contact information.

```
nomad namespace inspect team-a
{
    "CreateIndex": 100,
    "Description": "Team A Namespace",
    "ModifyIndex": 22661669,
    "Name": "team-a",
    "Quota": "",
    "Metadata": {
            "owner": "John Doe",
            "contact": "team-a@company.com",
            "billing-ua": "00001"
    }
}
```

### PR DESCRIPTION
**Pull request by jorgemarey**
This PR adds a metadata field to the namespace objects allowing users to attach custom data to namespaces.

Fixes #9631

### CODE REVIEW

**Comment by jrasell** [comment]
Hi @jorgemarey and thanks for raising this PR. We will try and get an initial review done promptly to provide any feedback.

**Comment by schmichael** [comment]
Thanks for the PR @jorgemarey! I updated some more docs and the CLI output.

Mind giving it one last look @jrasell?

**Review by jrasell — COMMENTED** [review]
Hi @jorgemarey and thanks again, this looks great!

I wonder if it would be possible to add or modify a namespace test to ensure the meta field is present as expected? `/nomad/namespace_endpoint_test.go` or `/command/agent/namespace_endpoint_test.go` perhaps?

If you could add a changelog entry that would be wonderful, [this document](https://github.com/hashicorp/nomad/blob/main/contributing/CHANGELOG.md) details the process.

**Comment by jorgemarey** [comment]
Hi @jrasell I added a meta value to the mock namespace. Is that enought? I also created the changelog file.

**Comment by jrasell** [comment]
> Hi @jrasell I added a meta value to the mock namespace. Is that enought? I also created the changelog file.

Yeah that is a great idea.

**Review by jrasell — APPROVED** [review]
LGTM, thanks @jorgemarey!

**Review by schmichael — APPROVED** [review]
Thanks @jrasell and @jorgemarey!

**Pull request merged**
