### PR TITLE
plugins/drivers: change stats interval to duration type in proto

### PR DESCRIPTION
**Pull request by nickethier**
Switch the interval type used in drivers proto to a google.protobuf.Duration instead of a plain int64. This is in line with how duration types are represented in other fields.

### CODE REVIEW

**Comment by schmichael** [comment]
This doesn't affect any tests?

**Comment by nickethier** [comment]
Rerunning the tests because the seem like flakes. It shouldn't though

**Comment by nickethier** [comment]
Looks like website build got broken recently. All other tests passed: https://travis-ci.org/hashicorp/nomad/builds/484194749

**Comment by nickethier** [comment]
That's the beauty of the go shim between protobuf and the plugin implementation. We can hide these protocol level changes from the plugin implementation.

**Pull request merged**
