### PR TITLE
tmp remove darwin arm build

### PR DESCRIPTION
**Pull request by drewbailey**

### CODE REVIEW

**Review by shoenig — APPROVED** [review]

**Comment by krishicks** [comment]
🎉

**Comment by loafoe** [comment]
Will this come back? 

I'm developing a custom driver and my dev box is an `M1` but getting errors around stats helper:

```
Unable to obtain CPU information: no such file or directory
```

Is this perhaps related?

**Comment by tgross** [comment]
@loafoe your issue sounds like https://github.com/hashicorp/nomad/issues/11046. I've also reopened https://github.com/hashicorp/nomad/issues/9408

**Comment by loafoe** [comment]
thanks @tgross indeed issue seems to be related to `gopsutils` (https://github.com/shirou/gopsutil/issues/1000) which causes broken stats calculations (all zero). I've resorted to testing on an `x86_64` system  for now.

**Pull request merged**
