### PR TITLE
Expose website port

### PR DESCRIPTION
**Pull request by chelseakomlo**
Allow serving a local instance of Nomad's website from Vagrant.

### CODE REVIEW

**Comment by schmichael** [comment]
It already runs in a Docker container and exposing the port from Vagrant will break running it on the host (without manually disabling the port forwarding).

**Comment by preetapan** [comment]
+1 to not doing

**Comment by angrycub** [comment]
OTOH, This allows users without Docker installed locally to generate the docs site.  Makes the vagrantfile a bit more one-stop-shopping. I'm 50/50 on this, but can see a value.

**Comment by DingoEatingFuzz** [comment]
Can we provide a different port when in vagrant?

This is what I suggest to do with the UI: https://github.com/hashicorp/nomad/blob/master/ui/README.md#running--development-with-vagrant

**Comment by dadgar** [comment]
I am +1 to not doing this. I already find having 4646 exposed very annoying

**Pull request closed without merging**
