### PR TITLE
add -data-dir option when starting nomad

### PR DESCRIPTION
**Pull request by scottw**
When you run the commands from the guide as it exists now returns:

```
# nomad agent -config=/etc/nomad.d/server.hcl
==> Must specify data directory
```

By adding `-data-dir` nomad starts properly.

### CODE REVIEW

**Comment by dadgar** [comment]
Could you instead add it to the config?

**Comment by scottw** [comment]
Updated.

**Comment by scottw** [comment]
Hold off... I should have checked this first.

**Comment by scottw** [comment]
Ok, should be good now.

**Comment by dadgar** [comment]
@scottw Unfortunately I think something happened when you rebased as you pulled in a lot of other changes.

**Comment by scottw** [comment]
Those should have been from master. Sorry for the mess. I'm going to close this request and make a clean fork.

**Pull request closed without merging**
