### PR TITLE
vault: revert support for entity aliases

### PR DESCRIPTION
**Pull request by lgfa29**
After a more detailed analysis of this feature, the approach taken in
PR #12449 was found to be not ideal due to poor UX (users are
responsible for setting the entity alias they would like to use) and
issues around jobs potentially masquerading itself as another Vault
entity.

I didn't revert the full PR as it contained some nice refactoring.

I also removed entity alias references from https://github.com/hashicorp/nomad/pull/12385

No CHANGELOG since the feature was never released.

### CODE REVIEW

**Comment by mikenomitch** [comment]
Adding some context on this rollback for anybody interested.

After speaking with the Vault team a bit more on this last minute, we decided that there is probably a better UX that we can deliver. Rather than forcing each submitter to provide an alias on each job submit (and then map that to a key), Nomad could provide the alias for you. As long as the Vault role was configured with proper allowed_entity_aliases, end Nomad users wouldn't need to know much about alias specifics.

Apologies for the last minute revert to anybody who was excited about this! Better for us to do this now, than to ship it and then have to quickly deprecate the new solution (or be stuck with bad UX).

**Comment by shoenig** [comment]
Oof, hard to see this reverted but it's definitely one of those things we need to get right the first time

**Review by shoenig — APPROVED** [review]

**Comment by mrproper** [comment]
uggh, when you revert an PR like this you should probably not leave the documentation in for it, its in the official documentation pages:
https://www.nomadproject.io/docs/job-specification/vault#vault-parameters
https://www.nomadproject.io/docs/job-specification/vault#entity_alias

**Comment by lgfa29** [comment]
Thank you for the heads up. There was a missing step during the release process that caused the website not be updated to latest version. It should be all updated now.

**Pull request merged**
