### PR TITLE
[ui] Dropdowns on the jobs index page get a max-height and filtering

### PR DESCRIPTION
**Pull request by philrenaud**
Before: 
image
After:
image

### CODE REVIEW

**Comment by david-yu** [comment]
Thanks for doing this!

**Comment by gulducat** [comment]
this is great for several-many namespaces!  maybe the box could be just a little taller?  or screen height as before, but with a scrollbar?

for _very_-many, though (thousands?), the little box is still kinda unwieldy.  a filter/search box on the dropdown would be real neat if you can swing it!

**Comment by david-yu** [comment]
Would be awesome if we could get this in for 1.8.0.

**Comment by philrenaud** [comment]
> for very-many, though (thousands?), the little box is still kinda unwieldy. a filter/search box on the dropdown would be real neat if you can swing it!

@gulducat updated with a lil' searchbox!

**Review by gulducat — APPROVED** [review]
love it!

**Pull request merged**
