### PR TITLE
Add artifacts manifest (automatically generated)

### PR DESCRIPTION
**Pull request by jeanneryan**
This PR was automatically generated by CRT tooling.

If this PR *_does not_* target a release branch, ensure it gets backported to active release branches.

Artifact source:
* HEAD commit SHA: 9d4686c0df9c42a9abefc036d7eb5c399455f815
* Version: 1.8.3-dev
* [workflow](https://github.com/hashicorp/nomad/actions/runs/10198675798)

### CODE REVIEW

**Review by tgross — COMMENTED** [review]
@jeanneryan we removed 32-bit ARM builds in https://github.com/hashicorp/nomad/pull/23189, which is reflected in the workflow you've got here... but that doesn't actually seem to match up with what's showing up at https://releases.hashicorp.com/nomad, where we're still seeing 32-bit ARM builds for Linux. I'm not sure where those could be coming from, but I imagine having a mismatch is going to fail this artifact check too?

(Note for other reviewers: there's a separate PR for Enterprise: https://github.com/hashicorp/nomad-enterprise/pull/1726)

Also: we should probably add these files to the ignore list for copywrite checks

**Comment by jeanneryan** [comment]
> @jeanneryan we removed 32-bit ARM builds in #23189, which is reflected in the workflow you've got here... but that doesn't actually seem to match up with what's showing up at https://releases.hashicorp.com/nomad, where we're still seeing 32-bit ARM builds for Linux. I'm not sure where those could be coming from, but I imagine having a mismatch is going to fail this artifact check too?
> 
> (Note for other reviewers: there's a separate PR for Enterprise: [hashicorp/nomad-enterprise#1726](https://github.com/hashicorp/nomad-enterprise/pull/1726))
> 
> Also: we should probably add these files to the ignore list for copywrite checks

@tgross , I took a peak at the release branch for 1.8.x and the build still has 32-bit ARM [here](https://github.com/hashicorp/nomad/blob/release/1.8.x/.github/workflows/build.yml#L135). The build instructions just need to get updated in your release branches to remove the 32-bit ARM builds. 

As for the copyright headers, someone else had reached out to me about this and we totally forgot to include it in our automation. I wrote up a quick script using the copywriter tool to add the headers. There is another commit in this PR to reflect this change so no need to add this to the ignore list. I did notice that some of the PRs you reviewed were already merged so I will create new PRs for those to add the headers. Thank you for being diligent on reviewing these PRs! I appreciate it!

**Comment by tgross** [comment]
> @tgross , I took a peak at the release branch for 1.8.x and the build still has 32-bit ARM here. The build instructions just need to get updated in your release branches to remove the 32-bit ARM builds.

:facepalm: I didn't even think to look there. Now I wonder what else we forgot to backport. I'll look into that. Thank you!

> As for the copyright headers...

Great, thanks!

**Review by tgross — APPROVED** [review]
LGTM!

**Pull request merged**
