### PR TITLE
Add ContainerID() method to get the containerID from a handle

### PR DESCRIPTION
**Pull request by cbednarski**
/cc @diptanu

### CODE REVIEW

**Comment by diptanu** [comment]
LGTM

**Comment by fernandezvara** [comment]
Was wondering what that was not exposed. When that get merged I will update the docker driver test, since I extract the ID using a really unmaintainable method

https://github.com/hashicorp/nomad/blob/master/client/driver/docker_test.go#L481

**Comment by cbednarski** [comment]
@fernandezvara Oh I just looked at that this morning, thanks for pointing that out! I'm in the code so I'll just do it now.

**Comment by fernandezvara** [comment]
Great, thanks.

**Comment by cbednarski** [comment]
I had already copy-pasted that code a few times for other tests. :grinning:

**Pull request merged**
