### PR TITLE
Added the update API

### PR DESCRIPTION
**Pull request by diptanu**
Looks like we didn't have the client API to talk to the update endpoint.

### CODE REVIEW

**Comment by diptanu** [comment]
cc/ @makewhatis

**Comment by dadgar** [comment]
How is this different from: https://github.com/hashicorp/nomad/blob/eb68ceff036b564c1326c214eda7c38a1a9c8b99/api/jobs.go#L68?

**Comment by makewhatis** [comment]
To me it is a little more explicit than the above one you mentioned. This seems to reflect the documentation a little better. 

https://www.nomadproject.io/api/jobs.html#update-existing-job

Just my 2 cents. I see when I dig through that this might accomplish the same thing, but it is much clearer to just have an Update that hits /jobs/:jobid

**Comment by dadgar** [comment]
I would be happy to accept changes to the documentation on the register functions, but as it is I don't think we would accept this PR since it is just another set of structs/functions to maintain and test.

**Comment by diptanu** [comment]
@dadgar Yeah that's fine if there is already a client API which accomplishes this.

**Pull request closed without merging**
