### PR TITLE
api: return X-Nomad-Index header on allocation stop

### PR DESCRIPTION
**Pull request by cgbaker**

### CODE REVIEW

**Comment by notnoop** [comment]
Mind if provide some context or motivation? iiuc, `X-Nomad-Index` is only relevant for blocking queries endpoints, according to https://www.nomadproject.io/api/index.html#blocking-queries .  Blocking queries make more sense for GET queries that pull value of resource where consumers want to subscribe for updates.

The alloc lifecycle endpoints are update calls that don't support blocking queries and is documented in https://www.nomadproject.io/api/allocations.html#signal-allocation .

**Comment by cgbaker** [comment]
>  the alloc lifecycle endpoints are side-effecting calls that don't support blocking queries 

The endpoint advances the index of the allocation, and the new index is useful for subsequent call to blocking endpoints (like allocation info). This index is currently returned by the allocation lifecycle endpoint, as part of the response body. This change simply returns it in the standard headed as well.

Apologies for not providing more context.

**Comment by notnoop** [comment]
Ah - good catch!  I guess this is relevant only to the server endpoints?  

Should also apply it to client endpoints (e.g. alloc signal/restart)?  I assume not because the alloc raft data isn't updated synchronisly as part of the api call?

Let's follow up and update the docs and New CLI command checklist to note the value of index field as well.

**Comment by cgbaker** [comment]
I'm going to merge this for the 0.9.4 RC; the index field is already documented in the [Alloc Stop API endpoint](https://www.nomadproject.io/api/allocations.html#stop-allocation).

**Comment by notnoop** [comment]
sounds good.  fwiw, the [Stop API endpoint](https://www.nomadproject.io/api/allocations.html#stop-allocation) documents `"index"` field in the response body not `X-Nomad-Index` header added here.

**Comment by cgbaker** [comment]
correct. the `X-Nomad-Index` documentation above should probably be amended to state that `X-Nomad-Index` is returned from endpoints that modify the index, for *use by* blocking endpoints that support blocking queries. before doing that, i need to determine whether it's actually the case that all of these endpoints return this response header.

**Pull request merged**
