### PR TITLE
Clean-up provisioning output

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by errordeveloper** [comment]
There is still quite a bit of noise from Docker installer, but I'm not sure what to do about that... I'd switch to Vagrant provider, which installs docker silently, what do people think?

**Comment by ryanuber** [comment]
@errordeveloper looks fine so far, using the docker Vagrant provider would be fine too!

**Comment by errordeveloper** [comment]
@ryanuber I added a simple `config.vm.provision "docker"`, which just does the trick :)

**Comment by ryanuber** [comment]
Thanks!

**Pull request merged**
