### PR TITLE
added host network interpolation

### LINKED ISSUE #10195: networking: add host network interpolation
### Proposal
Add `host_network` interpolation to be able to get host network name from node meta.

### Use-cases
As per #10106 it could be useful to have a `host_network` interpolation in case of using the same job spec for multiple regions with different network configuration 

### Attempted Solutions
It's possible to add multiple `group->port` stanzas with `service->port` interpolation but this configurations is redundant

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
Fixes  #10195

### CODE REVIEW

**Comment by tgross** [comment]
Hi @AndrewChubatiuk sorry about the delay here... I want to make sure that the root problem of https://github.com/hashicorp/nomad/issues/10106 is better understood before we review this.

**Review by tgross — CHANGES_REQUESTED** [review]
Hi @AndrewChubatiuk! I'm not sure I understand what this approach to interpolation is doing. But generally speaking we do any interpolation that's going to happen at either job submission time or on the client (sometimes both). It might help if there were tests?

**Comment by AndrewChubatiuk** [comment]
@tgross 
Without these changes workload will not even schedule on any agent

**Comment by tgross** [comment]
@AndrewChubatiuk maybe the code is fine where it is, but there's no tests and no "interpolation" going on here, so I can't even use the commit message to figure out what you're doing. If you can provide more context, I can review it.

**Comment by AndrewChubatiuk** [comment]
@tgross 
Added some tests

**Review by tgross — APPROVED** [review]

**Comment by tgross** [comment]
LGTM. I've rebased this on `main` to pick up recent fixes and added two more smallish tests. Once this is ✅  on CI I'll merge it.

**Pull request merged**
