### PR TITLE
Remove weight and hard/soft fields from constraint

### PR DESCRIPTION
**Pull request by dadgar**
The constraints are becoming all hard constraints thus we don't need the boolean or the weight.

### CODE REVIEW

**Comment by armon** [comment]
LGTM

**Comment by c4milo** [comment]
does this now mean Nomad allows overcommitting resources or what's the reasoning for this change?

**Comment by dadgar** [comment]
@c4milo: This change doesn't effect oversubscription. The reason for this change is that a soft constraint is really an affinity or anti-affinity. Currently we don't have any affinity/anti-affinity operators but the goal of this change was to make the distinction now so moving forward the messaging and code both are clear.

**Comment by c4milo** [comment]
Nice! Thanks for explaining @dadgar!

**Pull request merged**
