### PR TITLE
Docker 19.03.8

### PR DESCRIPTION
**Pull request by greut**
A follow up to #7350 

- [ ] `docker`'s is incompatible with `golang.org/x/sys/windows` which is required by `gopsutils`. `moby` should upgrade to a fresher version. (**or** I'm doing it wrong and it's much easier than that)

### CODE REVIEW

**Comment by greut** [comment]
it needs that one, https://github.com/moby/moby/pull/40021

**Comment by greut** [comment]
At some point, wouldn't it be easier to have docker as a separated plugin?

**Comment by jippi** [comment]
Having Docker as external plugin would be huge :)

**Comment by greut** [comment]
@jippi I did a couple of tries and I'm still on them. Nomad is using many of the docker/docker/pkg bits here and there. Until there is a proper nomad/sdk package (which seems to be a massive work) it will be hard to break those two apart.

Another try from a fresh master: #7531

**Pull request closed without merging**
