### PR TITLE
Add working directory parameter to exec driver

### LINKED ISSUE #10979: Specify working directory in exec driver chroot
### Proposal

Since the exec driver (unlike the raw exec driver) offers file system isolation it would make sense for it to have support for setting the `work_dir` like the docker driver. This would likely involve parametrizing [this bit](https://github.com/hashicorp/nomad/blob/master/drivers/shared/executor/executor.go#L275) of the shared executor 

### Use-cases

Avoiding `sh -c 'cd foobar; bazcommand'`

### Attempted Solutions

`sh -c 'cd foobar; bazcommand'`

### PR DESCRIPTION
**Pull request by cyruseuros**
Fixes #10979

### CODE REVIEW

**Comment by wurosh** [comment]
Am I missing something? The executor definitely sets the working directory (see the test), but running a job end-to-end on linux doesn't seem to apply the setting. It's as if it's using the universal executor instead of the libcontainer one.

**Comment by schmichael** [comment]
Sorry for the delay and frustration @wurosh and thanks for the contribution! There's a gRPC layer between the driver and executor which needs the WorkDir plumbed through. To make matters more interesting that layer involves protobufs, so I went ahead and pushed those changes. That appears to get it working with a dev agent and [test job](https://gist.github.com/schmichael/3a58a33d55b63142a9d146146dece42e)!

I think the outstanding items for this to get merged are:
- [ ] Fix tests
- [ ] Add Changelog entry - https://github.com/hashicorp/nomad/blob/main/contributing/CHANGELOG.md
- [ ] Add it to the docs - https://github.com/hashicorp/nomad/blob/main/website/content/docs/drivers/exec.mdx

**Comment by wurosh** [comment]
@schmichael I only have my own stupidity to blame for my frustration. I was spoiled by the ease of writing nomad *drivers* where the gRPC layer is obscured by interfaces. I'll get on the outstanding items in the next couple of days. Thank you so much for the help!

**Comment by schmichael** [comment]
Ha, don't feel bad. Nothing in our docs or tooling help you with this, and I'm not sure how to fix that. It's a really unfortunate dev story, and a pretty big cautionary tale for the Nomad team as we think about future use cases for gRPC.

**Review by tgross — CHANGES_REQUESTED** [review]
@wurosh I took a quick look over this but it looks like this needs to be rebased. I can review and get this ready for merge once that's done.

**Comment by tgross** [comment]
This work is superceded by https://github.com/hashicorp/nomad/pull/24249.

**Pull request closed without merging**
