### PR TITLE
Update runc to v1.0.0-rc93

### PR DESCRIPTION
**Pull request by zhsj**

### CODE REVIEW

**Comment by zhsj** [comment]
seems it needs a newer x/sys, which breaks gopsutil on darwin https://github.com/shirou/gopsutil/pull/970

Probably the best is to upgrade gopsutil, same as https://github.com/hashicorp/consul/pull/9118

**Review by tgross — CHANGES_REQUESTED** [review]
Hi @zhsj! Thanks for this PR. Is there a specific feature you're hoping Nomad is going to be able to implement with rc93, rather than waiting for the upcoming 1.0.0 which should be released in a few weeks [according to the rc93 release notes](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc93)?

In any case, it does look like we'll need that gopsutil update as well. Probably best to do that under separate PR and then rebase this one on that once merged. I can probably do that for the Nomad 1.1 release cycle, which will be after runc is likely to ship 1.0.0 as well. I'll keep this PR open until then and we can rebase on 1.0.0 at that time.

**Comment by zhsj** [comment]
> Hi @zhsj! Thanks for this PR. Is there a specific feature you're hoping Nomad is going to be able to implement with rc93, rather than waiting for the upcoming 1.0.0 which should be released in a few weeks [according to the rc93 release notes](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc93)?
> 

Since runc has large refactor in its libcontainer package, so it would be nice to see if it breaks nomad in some way.
Upgrading from rc93 to 1.0.0 should be much easier than upgrading rc92 to rc93.

> In any case, it does look like we'll need that gopsutil update as well. Probably best to do that under separate PR and then rebase this one on that once merged. I can probably do that for the Nomad 1.1 release cycle, which will be after runc is likely to ship 1.0.0 as well. I'll keep this PR open until then and we can rebase on 1.0.0 at that time.

Sure.

**Review by tgross — APPROVED** [review]

**Comment by tgross** [comment]
@nickethier I've rebased this on `main` with the `gopsutil` update. There's some small code updates made here and I want to make sure they line up with what you've got on https://github.com/hashicorp/nomad/pull/10228

**Pull request merged**
