### PR TITLE
vendors: avoid vendors from docker's vendors

### PR DESCRIPTION
**Pull request by greut**
The following vendors were fetched from docker's repository.

- `golang.org/x/net/proxy`
- `github.com/docker/libnetwork/ipamutils`

This kind of setup makes it very hard to use go modules.

### CODE REVIEW

**Comment by notnoop** [comment]
Thanks - Noticed a similar situation with some packages from opencontainers/runc.

**Comment by greut** [comment]
@notnoop the opencontainers/runc one look quite hairy indeed.

**Comment by notnoop** [comment]
Noticed `TestTasklet_Exec_Timeout` failing in `test-client` that might be relevent - mind if you re-run the workflow from failures in https://circleci.com/workflow-run/ccea6c02-f656-46db-b1c4-14826a4f777a ?

**Comment by greut** [comment]
Done, it went through.

**Pull request merged**
