### PR TITLE
Logs view - support widescreen format

### LINKED ISSUE #5303: Nomad Job Logs Should Support Widescreen Format
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Windows 10
Google Chrome

### Issue
Logs (stdout,stderr) should be expandable or expand out to the right edge of browser windows. Most monitors in the last 10 years have been sold in a wide-screen format, and Nomad should not wrap logs unnecessarily.

Feature Request:  Please allow for an adjustable or wider log output pane to prevent scrolling of logs and wasted space. Please see the attached image as an example of wasted space.

image

### Reproduction steps
Open Nomad task Logs on a wide-screen monitor, observe wasted space.

### PR DESCRIPTION
**Pull request by jacekjagiello**
Fixes #5303 

Added simple class that allows `section` to take whole available space

### CODE REVIEW

**Comment by DingoEatingFuzz** [comment]
Huzzah! Thanks for jumping on this. I checked out your branch and can confirm that it does what it reports to do:

image

I'm happy merging this as is, but since we're in the middle of beta-testing 0.9 I want to consult with the team first. If it doesn't make it into 0.9 it will surely make it into 0.9.1.

**Comment by jacekjagiello** [comment]
> I'm  happy merging this as is, but since we're in the middle of beta-testing  0.9 I want to consult with the team first. If it doesn't make it into  0.9 it will surely make it into 0.9.1.
That's great, @cpumanaz FYI

**Comment by DingoEatingFuzz** [comment]
@jacekjagiello, since we haven't released an 0.9 release candidate, it looks like this one is gonna barely slip into 0.9!

Merging now, great work!

**Comment by jacekjagiello** [comment]
@DingoEatingFuzz Thanks for merging this. I'm happy that I can give a little help with making such great software even better. I'll be looking forward to contributing in the future :grinning:

**Comment by cpumanaz** [comment]
Thank you for your work @jacekjagiello

**Pull request merged**
