### PR TITLE
Pass command and trust_prefix to the validation of rkt task configuration

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by dadgar** [comment]
LGTM thanks

**Comment by dadgar** [comment]
Those values are not passable in the driver config?

**Comment by nak3** [comment]
Thank you. I added them to the driver config.

**Comment by dadgar** [comment]
We should add some tests for the new flags before merging this

**Comment by nak3** [comment]
Thank you. I added tests. `TestRktTaskValidate` might not be necessary, since other drivers don't do this.

**Comment by dadgar** [comment]
Looks good! Last thing I forgot is please add the new fields to the rkt docs. https://github.com/hashicorp/nomad/blob/master/website/source/docs/drivers/rkt.html.md

**Comment by nak3** [comment]
Thank you. The docs already has the field `command` and `trust_prefix`. Should I still need to add something?

**Comment by dadgar** [comment]
Oh you are right! Sorry

**Pull request merged**
