### PR TITLE
Guard against bad restore in alloc runner

### PR DESCRIPTION
**Pull request by dadgar**

### CODE REVIEW

**Comment by dadgar** [comment]
Fixes #1141

**Comment by a86c6f7964** [comment]
Should #1141 get closed? Or is there more to do on it?

**Comment by diptanu** [comment]
@a86c6f7964 Can you try reproducing #1170 after building with this patch? Please close #1141 if you can't reproduce the issue anymore. You could also use the Nomad 0.4.0-rc2.

**Comment by a86c6f7964** [comment]
I put some notes into #1170 I did not close #1141 since IMHO just not panicing is not really the right fix. The intent of #1141 probably is that nomad agent should start up, and now it just gives different errors.

**Pull request merged**
