### PR TITLE
core: implement system batch scheduler

### LINKED ISSUE #2527: Batch System Jobs
Currently, for running short living jobs, there is the batch scheduler, and for cluster-wide jobs (one per node) there is the service scheduler.
But sometimes you may want a short living job (that exits fast, not running any daemon) that is propagated across all the nodes. One example would be a job that changes some kind of config on the nodes.
Would it be possible to either support this kind of jobs in the system scheduler, or allow the batch scheduler to be run on all nodes?

Thanks

### PR DESCRIPTION
**Pull request by shoenig**
This PR implements a new "System Batch" scheduler type. Jobs can
make use of this new scheduler by setting their type to 'sysbatch'.

Like the name implies, sysbatch can be thought of as a hybrid between
system and batch jobs - it is for running short lived jobs intended to
run on every compatible node in the cluster.

As with batch jobs, sysbatch jobs can also be periodic and/or parameterized
dispatch jobs. A sysbatch job is considered complete when it has been run
on all compatible nodes until reaching a terminal state (success or failed
on retries).

Feasibility and preemption are governed the same as with system jobs. Because the existing system scheduler does not support *deployments*, sysbatch jobs cannot yet make use of deployments either. (Described in https://github.com/hashicorp/nomad/issues/4740)

Closes #2527

### CODE REVIEW

**Comment by shoenig** [comment]
TODO
- [ ] disable option
- [ ] tests
- [ ] e2e tests
- [ ] documentation
- [ ] changelog

**Comment by tgross** [comment]
Something else to consider here is that all job types have a job detail page in the web UI tailored to the job type, (e.g., service jobs have deployments, parameterized children have a payload). System batch jobs should also have a tailored job detail page. What features of system batch need to be called out? Before this lands we should coordinate with @DingoEatingFuzz to work through what's needed for that design.

**Review by notnoop — COMMENTED** [review]
Thanks @shoenig ! I like the approach taken here. Looks like the conflicts are minimal.

Have few questions:
First, do we need to add any special logic for `reschedule` block? I assume it doesn't apply to system batch jobs, should we add any validation?

second, what's the intended behavior for new nodes? When should the system batch job be considered "complete"? I envision use cases where system batch jobs should run on the nodes matching the constraints at submission time but not for new nodes and where running them on new nodes can be "surprising". This might be an interesting intersection with parameterized/dispatch system batch jobs, if supported.

**Review by notnoop — APPROVED** [review]
LGTM. Merging and will iterate on this.

Also, double checked - periodic/parameterized system batch jobs are supported. And system batch jobs only run on the nodes that are ready at the time of scheduling; system batch jobs don't run on nodes that got added after the initial scheduling, unless operator triggers an job eval (e.g. resubmitting the job, etc).

**Pull request merged**
