### PR TITLE
Vendor fsouza/go-docker-client update

### LINKED ISSUE #6085: Docker containers use swap in 0.9.4
### Nomad version
Nomad v0.9.4 (a81aa846a45fb8248551b12616287cb57c418cd6)

### Operating system and Environment details
CentOS Linux release 7.6.1810 (Core)
Docker version 18.03.1-ce, build 9ee9f40

### Issue
After updating nomad from 0.8.4 to 0.9.4 docker containers started to use swap.
Despite this:
https://github.com/hashicorp/nomad/blob/v0.9.4/drivers/docker/driver.go#L730
`docker inspect` shows that containers use unlimited swap:
```
docker inspect 2bc3d0fd13b3 | grep Memory
            "Memory": 268435456,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": null,
```
### Reproduction steps
* Create a job that uses docker driver.
* Check `MemorySwap` parameter of the container

### PR DESCRIPTION
**Pull request by notnoop**
Reprise of https://github.com/hashicorp/nomad/pull/7416.  Thanks @greut .

Also, includes some docker vendoring tweaks to ensure that all `github.com/docker/docker` packages are of v19.03.8

Also fixes #6085

### CODE REVIEW

**Comment by tgross** [comment]
This looks like it still has Windows build issues:

```
==> Building pkg/windows_amd64/nomad with tags codegen_generated...
# github.com/hashicorp/nomad/vendor/github.com/docker/docker/pkg/system
vendor/github.com/docker/docker/pkg/system/filesys_windows.go:111:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"github.com/hashicorp/nomad/vendor/golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
make: *** [GNUmakefile:120: pkg/windows_amd64/nomad] Error 2
```

and some Linux build issues:

```
==> Building pkg/linux_amd64/nomad with tags codegen_generated ...
vendor/github.com/docker/docker/pkg/archive/archive_linux.go:12:2: cannot find package "github.com/containerd/continuity/fs" in any of:
	/home/circleci/go/src/github.com/hashicorp/nomad/vendor/github.com/containerd/continuity/fs (vendor tree)
	/usr/local/go/src/github.com/containerd/continuity/fs (from $GOROOT)
	/home/circleci/go/src/github.com/containerd/continuity/fs (from $GOPATH)
GNUmakefile:82: recipe for target 'pkg/linux_amd64/nomad' failed
```

**Comment by notnoop** [comment]
@tgross sorry - I need to fix CI first before requesting review :( .

**Comment by notnoop** [comment]
This is ready for review again - all green and is passing Windows appveyor tests too

**Comment by greut** [comment]
@notnoop brilliant!

**Pull request merged**
