### PR TITLE
B 208 increase decrease group count r2

### PR DESCRIPTION
**Pull request by lovwal**
This implements #208 

Right now the update job struct is returned after the update. This could possibly be changed to return a diff struct instead. I chose not to this as you may handle this in the calling method instead.

It could be updated to provide values such as disk/ram/CPU etc. I have tooling which does this.

Example usage:
 curl -d '{"count":1, "taskgroupid":"cache"}' $NOMAD_ADDR/v1/job/example/increase 

Please let me know if you have any comments or if I misunderstood something regarding the issue.

### CODE REVIEW

**Comment by lovwal** [comment]
Realized that group.Count < group.Update.MaxParallel may be a bad check after seeing #2819.
I can update the PR if required.

**Comment by jrasell** [comment]
@lovwal the build is failing as you added the import of "log" without using the package within `job_endpoint.go`. It would also be advisable for this kind of change to add tests for the new endpoints to `job_endpoint_test.go`.

**Comment by lovwal** [comment]
@jrasell Sorry, silly mistake when migrating my local branches. This one should build at least. I added tests as requested, please let me know if there is anything else.

**Comment by dadgar** [comment]
Hey sorry for the long delay here. I am actually going to close this PR. Our long term plan will be to support this using variables in the job file. The count would be specified as a variable and then to scale, you would update the value of the variable.

**Pull request closed without merging**
