### PR TITLE
Do not emit logs on SIGPIPE since logging service could be unavailable

### PR DESCRIPTION
**Pull request by maxvt**
This should fix https://github.com/hashicorp/nomad/issues/3554

### CODE REVIEW

**Comment by dadgar** [comment]
@maxvt Have you built and tried this change? If so it looks good! Want to confirm it fixes the problem first though!

**Comment by maxvt** [comment]
Haven't built it yet. I'm away from work for a few days, I'll try it (backported to the version we run) once I'm back.

**Comment by maxvt** [comment]
@dadgar I built and tested it, nothing seems to break but I couldn't reproduce the original problem we had either -- I could stop journald on the test box and Consul would freak out but Nomad stayed at low CPU. Up to you if you want to pick this up or close.

**Comment by dadgar** [comment]
Thanks for following up @maxvt!

**Pull request merged**
