### PR TITLE
[ui] Color indicators for server/client status

### PR DESCRIPTION
**Pull request by philrenaud**
Plus a nice little icon for when a server is leader

image
image

### CODE REVIEW

**Comment by apollo13** [comment]
Maybe put the leader icon after the text so the text stays aligned?

**Comment by philrenaud** [comment]
@apollo13 good call; I've moved it to post-text.

**Comment by angrycub** [comment]
So I generally appreciate color's ability to improve scanability and quite like this. Is it possible to provide a symbolic alternative to benefit folks that might not be able to use the colors?  I think that Apple has a nice idea on this front with their "Differentiate without Color" accessibility option. 

Before and After showing a macOS UI with Differentiate without Color being set

h/t to AbilityNet's article [How to differentiate items without using colour in iOS 15 on your iPhone, iPad, or iPod Touch](https://mcmw.abilitynet.org.uk/how-to-differentiate-items-without-using-colour-in-ios-15-on-your-iphone-ipad-or-ipod-touch)

**Comment by philrenaud** [comment]
@angrycub Thanks to your feedback on this, @juliezzhou and I went over and updated these to use icons where distinction is relevant, using [Helios badges](https://helios.hashicorp.design/components/badge?tab=code):

image
image

**Review by juliezzhou — APPROVED** [review]
lgtm

**Pull request merged**
