### PR TITLE
B 2117 windows group process

### PR DESCRIPTION
**Pull request by ninoles**
A followed up on [GH-4153](https://github.com/hashicorp/nomad/pull/4153)

### CODE REVIEW

**Comment by ninoles** [comment]
BTW, here the job I used for testing:

```
job "com" {
  datacenters = ["dc1"]
  task "com" {
    driver = "raw_exec"
    config = {
      command = "C:\\WINDOWS\\py.exe"
      args = ["-c", "import subprocess; subprocess.run('nomad logs -f -job com')"]
    }
  }
}
```
Note that applications like notepad will not work since they don't answer to Ctrl-Break events.

**Comment by schmichael** [comment]
Thanks @ninoles! There's a couple linter errors that I'll fixup post merge.

**Comment by ninoles** [comment]
I just try the version you put in #4169 and it works, but not with the job I sent you (I was trying to give you an easier example than what I use for our software).  Here a more complete example, that also work with GUI application (notepad here):

[com.nomad.txt](https://github.com/hashicorp/nomad/files/1929504/com.nomad.txt)

**Comment by schmichael** [comment]
@ninoles I deleted #4169 and merged this PR. Are you saying it doesn't work as expected? Here's an executable built from master 45d0c88fa

[nomad-45d0c88fa-windows_amd64.zip](https://github.com/hashicorp/nomad/files/1929918/nomad-45d0c88fa-windows_amd64.zip)

**Comment by ninoles** [comment]
No, sorry, the previous job was a slight variation on one I was using internally, in my own setup (with other jobs running, etc.).  The one above just work perfectly.  My only problems now is how to make nomad ignore the IPv6 address that windows set on their default loopback, but that's another problem.

**Pull request merged**
