### PR TITLE
pass in msgType for UpsertJob

### LINKED ISSUE #9432: UpsertJob not using msgtype
### Nomad version
1.0.0-beta3

### Issue
`StateStore.UpsertJob` does not use the raft message type which it was passed:
https://github.com/hashicorp/nomad/blob/v1.0.0-beta3/nomad/state/state_store.go#L1446-L1447
As a result, the events in the write transaction do not result in events in the event stream. The main consequence is that job register events are not emitted for job updates.

### Reproduction steps
1. Register a job; not that the event is emitted by the stream.
2. Make a change and update the job. Note that no associated `JobRegistered` event is emitted.

### PR DESCRIPTION
**Pull request by drewbailey**
Create events for upsertjob msg type
resolves #9432

### CODE REVIEW

**Review by jrasell — COMMENTED** [review]
LGTM but probably worth another review from someone who has more experience within the state store.

**Review by cgbaker — APPROVED** [review]
lgtm. I will note that in manual testing, this results in a lot more events (many duplicate) on the event stream. that was the goal, but we may want to consider deduping in the future.

**Comment by drewbailey** [comment]
@cgbaker thanks for bringing that up, turns out this is a bug :beetle: https://github.com/hashicorp/nomad/issues/9484

**Comment by drewbailey** [comment]
Merging and following up bug in separate PR

**Pull request merged**
