### PR TITLE
fingerprint kernel architecture name

### PR DESCRIPTION
**Pull request by shantanugadgil**
first attempt at classic cpu architecture names while fingerprinting the cpu.

ref: #13181 

Note as mentioned in the issue, I am fine if folks can come up with a name different that "classic" :)

### CODE REVIEW

**Comment by shantanugadgil** [comment]
@angrycub @lgfa29 @jrasell 

Any inputs here? I am not sure what/why the tests are failing!

**Comment by lgfa29** [comment]
Vercel requires an explicit approval when deploying code from PRs, not a test failure 😄 

I will double check with team with regards to the naming here, in the meantime, would mind adding a [`CHANGELOG` entry](https://github.com/hashicorp/nomad/blob/main/contributing/CHANGELOG.md)?

Thanks for the PR!

**Comment by lgfa29** [comment]
@shantanugadgil I spoke with the team and they brought up a good point, which is that these naming are really standardized and the same ISA can have even more than two common representations. For example, `386` can be `i386` but also `x86` in some places, so it would not be feasible for us to support all the different options.

One suggestion is to instead set node metadata values for the architectures that you need. How does that sound for you?

**Comment by shantanugadgil** [comment]
after thinking about this a bit more ... what I essentially need/want is (pseudo-code):

```sh

if (linux) {
    attr.cpu.machine=$(uname -m)
}

```
`attr.cpu.machine` can be `attr.os.machine` as well.

**Comment by lgfa29** [comment]
Ah yeah, that's a great point. To make the implementation even more robust and support other operating systems, you can read this value from the `gopsutil`, which is the library we use to fingerprint other system properties. 

More specifically, you can do this in the `host.go` fingerprinter and read the value of `KernelArch` from [`host.InfoStat`](https://pkg.go.dev/github.com/shirou/gopsutil/v3@v3.22.5/host#InfoStat), just like we do for [`kernel.version`](https://github.com/hashicorp/nomad/blob/v1.3.1/client/fingerprint/host.go#L33). So this would be a new attribute called `kernel.arch`.

And then, just one last thing missing in the PR would to document this new attribute in this page:
https://github.com/hashicorp/nomad/blob/main/website/content/docs/runtime/interpolation.mdx#node-variables-interpreted_node_vars-node-variables-

**Review by lgfa29 — APPROVED** [review]
Thanks @shantanugadgil!

I just pushed a commit to keep the attribute table in alphabetical order.

**Pull request merged**
