### PR TITLE
website: upgrade code-block

### PR DESCRIPTION
**Pull request by zchsh**
👀 [Preview](https://nomad-git-fork-zchsh-zsupgrade-code-block-hashicorp.vercel.app/docs)

This PR upgrades all MDX code snippets to use [our latest `code-block` component](https://github.com/hashicorp/react-components/pull/205), which contains a number of new features detailed in [[MKTG-035] Improvements to our Code Blocks](https://docs.google.com/document/d/1b2ROeAoy708dSqpJZjZRvuhJm9FB86skKEeQC3ZkLMY/edit?ts=5fadaaee).

We've also converted our `code-block` component to use CSS modules, which removes the need for global code-block related style imports.

### CODE REVIEW

**Comment by tgross** [comment]
@zchsh I did a spot check of this and it looks like there'll be some cleanup of code blocks to do here before this can get merged; there are places where in-line code blocks are getting used where they shouldn't. Previously this worked fine, probably because typical markdown parsers accept it. But with this change they are broken.

For example, take a look at the existing [`network`](https://www.nomadproject.io/docs/job-specification/network#network-parameters) documentation. Note that GitHub renders the [`network.mdx`](https://github.com/hashicorp/nomad/blob/main/website/content/docs/job-specification/network.mdx) as we'd expect but if we look at the [raw file](https://raw.githubusercontent.com/hashicorp/nomad/main/website/content/docs/job-specification/network.mdx) we can see the `<code>` blocks. (I understand that we're not using the same markdown renderer as GitHub obviously, but it gives a clue as to how we got into this state.) Currently, this renders nicely like so:

Screen Shot 2021-06-21 at 8 39 55 AM

Whereas if we look at the [preview of the new version](https://nomad-git-fork-zchsh-zsupgrade-code-block-hashicorp.vercel.app/docs/job-specification/network) it looks like this:

Screen Shot 2021-06-21 at 8 39 39 AM

If I do a quick search for that block:

<details>

```
$ rg -e '<code>' website
website/content/api-docs/search.mdx
130:fuzzy searching can be tuned through the <code>[search]</code> stanza in Nomad agent config.

website/content/partials/envvars.mdx
11:        <code>NOMAD_ALLOC_DIR</code>
14:        The path to the shared <code>alloc/</code> directory. See
22:        <code>NOMAD_TASK_DIR</code>
25:        The path to the task <code>local/</code> directory. See
31:        <code>NOMAD_SECRETS_DIR</code>
40:        <code>NOMAD_MEMORY_LIMIT</code>
46:        <code>NOMAD_MEMORY_MAX_LIMIT</code>
55:        <code>NOMAD_CPU_LIMIT</code>
61:        <code>NOMAD_ALLOC_ID</code>
67:        <code>NOMAD_ALLOC_NAME</code>
73:        <code>NOMAD_ALLOC_INDEX</code>
83:        <code>NOMAD_TASK_NAME</code>
89:        <code>NOMAD_GROUP_NAME</code>
95:        <code>NOMAD_JOB_ID</code>
104:        <code>NOMAD_JOB_NAME</code>
110:        <code>NOMAD_JOB_PARENT_ID</code>
116:        <code>NOMAD_DC</code>
122:        <code>NOMAD_NAMESPACE</code>
128:        <code>NOMAD_REGION</code>
134:        <code>NOMAD_META_&lt;key&gt;</code>
137:        The metadata value given by <code>key</code> on the task's
140:          <code>$&#123;meta.&lt;key&gt;&#125;</code>
147:        <code>VAULT_TOKEN</code>
160:        <code>NOMAD_IP_&lt;label&gt;</code>
163:        Host IP for the given port <code>label</code>. See
169:        <code>NOMAD_PORT_&lt;label&gt;</code>
172:        Port for the given port <code>label</code>. Driver-specified port when a
180:        <code>NOMAD_ADDR_&lt;label&gt;</code>
183:        Host <code>IP:Port</code> pair for the given port <code>label</code>.
188:        <code>NOMAD_HOST_PORT_&lt;label&gt;</code>
191:        Port on the host for the port <code>label</code>. See
198:        <code>NOMAD_IP_&lt;task&gt;_&lt;label&gt;</code>
201:        Host IP for the given port <code>label</code> and <code>task</code> for
207:        <code>NOMAD_PORT_&lt;task&gt;_&lt;label&gt;</code>
210:        Port for the given port <code>label</code> and <code>task</code> for
218:        <code>NOMAD_ADDR_&lt;task&gt;_&lt;label&gt;</code>
221:        Host <code>IP:Port</code> pair for the given port <code>label</code> and
222:        <code>task</code> for tasks in the same task group.
227:        <code>NOMAD_HOST_PORT_&lt;task&gt;_&lt;label&gt;</code>
230:        Port on the host for the port <code>label</code> and <code>task</code>
236:        <code>NOMAD_UPSTREAM_IP_&lt;service&gt;</code>
239:        IP for the given <code>service</code> when defined as a Consul Connect
245:        <code>NOMAD_UPSTREAM_PORT_&lt;service&gt;</code>
248:        Port for the given <code>service</code> when defined as a Consul Connect
254:        <code>NOMAD_UPSTREAM_ADDR_&lt;service&gt;</code>
257:        Host <code>IP:Port</code> for the given <code>service</code> when
264:        <code>NOMAD_ENVOY_ADMIN_ADDR_&lt;service&gt;</code>
267:        Local address <code>localhost:Port</code> for the admin port of the
268:        envoy sidecar for the given <code>service</code> when defined as a
277:        <code>CONSUL_HTTP_ADDR</code>
286:        <code>CONSUL_HTTP_TOKEN</code>
294:        <code>CONSUL_HTTP_SSL</code>
302:        <code>CONSUL_HTTP_SSL_VERIFY</code>
310:        <code>CONSUL_CACERT</code>
318:        <code>CONSUL_CLIENT_CERT</code>
326:        <code>CONSUL_CLIENT_KEY</code>

website/content/docs/configuration/audit.mdx
55:- `sink` <code>([sink](#sink-stanza): default)</code> - Configures a sink
58:- `filter` <code>(array<[filter](#filter-stanza)>: [])</code> - Configures a filter

website/content/docs/configuration/server.mdx
110:- `default_scheduler_config` <code>([scheduler_configuration][update-scheduler-config]:
188:- `server_join` <code>([server_join][server-join]: nil)</code> - Specifies
197:- `search` <code>([search][search]: nil)</code> - Specifies configuration parameters

website/content/docs/configuration/client.mdx
30:- `chroot_env` <code>([ChrootEnv](#chroot_env-parameters): nil)</code> -
72:- `options` <code>([Options](#options-parameters): nil)</code> - Specifies a
76:- `reserved` <code>([Reserved](#reserved-parameters): nil)</code> - Specifies
88:- `server_join` <code>([server_join][server-join]: nil)</code> - Specifies
137:- `template` <code>([Template](#template-parameters): nil)</code> - Specifies
141:- `host_volume` <code>([host_volume](#host_volume-stanza): nil)</code> - Exposes
144:- `host_network` <code>([host_network](#host_network-stanza): nil)</code> - Registers

website/content/docs/configuration/sentinel.mdx
26:- `import` <code>([Import](#import-parameters): nil)</code> -

website/content/docs/runtime/interpolation.mdx
77:        <code>{'${node.unique.id}'}</code>
81:        <code>9afa5da1-8f39-25a2-48dc-ba31fd7c0023</code>
86:        <code>{'${node.region}'}</code>
90:        <code>global</code>
95:        <code>{'${node.datacenter}'}</code>
99:        <code>dc1</code>
104:        <code>{'${node.unique.name}'}</code>
108:        <code>nomad-client-10-1-2-4</code>
113:        <code>{'${node.class}'}</code>
117:        <code>linux-64bit</code>
122:        <code>
127:        Property given by <code>property</code> on the client
130:        <code>{'${attr.cpu.arch} => amd64'}</code>
135:        <code>
140:        Metadata value given by <code>key</code> on the client
143:        <code>{'${meta.foo} => bar'}</code>
161:        <code>{'${attr.cpu.arch}'}</code>
164:        CPU architecture of the client (e.g. <code>amd64</code>,{' '}
165:        <code>386</code>)
170:        <code>{'${attr.cpu.numcores}'}</code>
176:        <code>{'${attr.cpu.totalcompute}'}</code>
179:        <code>cpu.frequency &times; cpu.numcores</code> but may be overridden by{' '}
180:        <code>client.cpu_total_compute</code>
185:        <code>{'${attr.consul.datacenter}'}</code>
191:        <code>
202:        <code>{'${attr.unique.hostname}'}</code>
208:        <code>{'${attr.unique.network.ip-address}'}</code>
217:        <code>{'${attr.kernel.name}'}</code>
220:        Kernel of the client (e.g. <code>linux</code>, <code>darwin</code>)
225:        <code>{'${attr.kernel.version}'}</code>
228:        Version of the client kernel (e.g. <code>3.19.0-25-generic</code>,{' '}
229:        <code>15.0.0</code>)
234:        <code>{'${attr.platform.aws.ami-id}'}</code>
240:        <code>{'${attr.platform.aws.instance-type}'}</code>
246:        <code>{'${attr.platform.aws.placement.availability-zone}'}</code>
252:        <code>{'${attr.os.name}'}</code>
255:        Operating system of the client (e.g. <code>ubuntu</code>,{' '}
256:        <code>windows</code>, <code>darwin</code>)
261:        <code>{'${attr.os.version}'}</code>

website/content/docs/job-specification/connect.mdx
55:- `sidecar_service` - <code>([sidecar_service][]: nil)</code> - This is used to
58:- `sidecar_task` - <code>([sidecar_task][]:nil)</code> - This modifies the
61:- `gateway` - <code>([gateway][]:nil)</code> - This is used to configure the

website/content/docs/job-specification/expose.mdx
136:- `path` <code>([Path]: nil)</code> - A list of [Envoy Expose Path Configurations][expose_path]
152:- `listener_port` <code>([Port]: required)</code> - The name of the port to use

website/content/docs/job-specification/task.mdx
28:- `artifact` <code>([Artifact][]: nil)</code> - Defines an artifact to download
37:- `constraint` <code>([Constraint][]: nil)</code> - Specifies user-defined
41:- `affinity` <code>([Affinity][]: nil)</code> - This can be provided
44:- `dispatch_payload` <code>([DispatchPayload][]: nil)</code> - Configures the
51:- `env` <code>([Env][]: nil)</code> - Specifies environment variables that will
71:- `lifecycle` <code>([Lifecycle][]: nil)</code> - Specifies when a task is run
74:- `logs` <code>([Logs][]: nil)</code> - Specifies logging configuration for the
77:- `meta` <code>([Meta][]: nil)</code> - Specifies a key-value map that annotates
80:- `resources` <code>([Resources][]: &lt;required&gt;)</code> - Specifies the minimum
83:- `service` <code>([Service][]: nil)</code> - Specifies integrations with
102:- `template` <code>([Template][]: nil)</code> - Specifies the set of templates
107:- `vault` <code>([Vault][]: nil)</code> - Specifies the set of Vault policies
111:- `volume_mount` <code>([VolumeMount][]: nil)</code> - Specifies where a group

website/content/docs/job-specification/spread.mdx
69:- `target` <code>([target](#target-parameters): &lt;required&gt;)</code> - Specifies one or more target

website/content/docs/job-specification/sidecar_service.mdx
54:- `proxy` <code>([proxy][]: nil)</code> - This is used to configure the
57:- `tags` <code>(array&lt;string&gt;: nil)</code> - Custom Consul service tags

website/content/docs/job-specification/service.mdx
73:- `check` <code>([Check](#check-parameters): nil)</code> - Specifies a health
165:- `meta` <code>([Meta][]: nil)</code> - Specifies a key-value map that annotates
168:- `canary_meta` <code>([Meta][]: nil)</code> - Specifies a key-value map that

website/content/docs/job-specification/group.mdx
27:- `constraint` <code>([Constraint][]: nil)</code> -
30:- `affinity` <code>([Affinity][]: nil)</code> - This can be provided
33:- `spread` <code>([Spread][spread]: nil)</code> - This can be provided
43:- `consul` <code>([Consul][consul]: nil)</code> - Specifies Consul configuration
46:- `ephemeral_disk` <code>([EphemeralDisk][]: nil)</code> - Specifies the
50:- `meta` <code>([Meta][]: nil)</code> - Specifies a key-value map that annotates
53:- `migrate` <code>([Migrate][]: nil)</code> - Specifies the group strategy for
57:- `network` <code>([Network][]: &lt;optional&gt;)</code> - Specifies the network
61:- `reschedule` <code>([Reschedule][]: nil)</code> - Allows to specify a
65:- `restart` <code>([Restart][]: nil)</code> - Specifies the restart policy for
69:- `service` <code>([Service][]: nil)</code> - Specifies integrations with
98:- `task` <code>([Task][]: &lt;required&gt;)</code> - Specifies one or more tasks to run
102:- `update` <code>([Update][update]: nil)</code> - Specifies the task's update
105:- `vault` <code>([Vault][]: nil)</code> - Specifies the set of Vault policies
109:- `volume` <code>([Volume][]: nil)</code> - Specifies the volumes that are

website/content/docs/job-specification/multiregion.mdx
72:- `strategy` <code>([Strategy](#strategy-parameters): nil)</code> - Specifies
75:- `region` <code>([Region](#region-parameters): nil)</code> - Specifies the

website/content/docs/job-specification/job.mdx
65:- `constraint` <code>([Constraint][constraint]: nil)</code> -
70:- `affinity` <code>([Affinity][affinity]: nil)</code> -
75:- `spread` <code>([Spread][spread]: nil)</code> - This can be provided multiple times
82:- `group` <code>([Group][group]: &lt;required&gt;)</code> - Specifies the start of a
86:- `meta` <code>([Meta][]: nil)</code> - Specifies a key-value map that annotates
92:- `migrate` <code>([Migrate][]: nil)</code> - Specifies the groups strategy for
99:- `parameterized` <code>([Parameterized][parameterized]: nil)</code> - Specifies
102:- `periodic` <code>([Periodic][]: nil)</code> - Allows the job to be scheduled
111:- `reschedule` <code>([Reschedule][]: nil)</code> - Allows to specify a
118:- `update` <code>([Update][update]: nil)</code> - Specifies the task's update
121:- `vault` <code>([Vault][]: nil)</code> - Specifies the set of Vault policies

website/content/docs/job-specification/upstreams.mdx
92:- `mesh_gateway` <code>([mesh_gateway][mesh_gateway_param]: nil)</code> - Configures the mesh gateway

website/content/docs/job-specification/proxy.mdx
58:- `upstreams` <code>([upstreams][]: nil)</code> - Used to configure details of each upstream service that
60:- `expose` <code>([expose]: nil)</code> - Used to configure expose path configuration for Envoy.

website/content/docs/job-specification/resources.mdx
37:- `cores` <code>(`int`: &lt;optional&gt;)</code> <sup>1.1 Beta</sup> - Specifies the number of CPU cores to reserve
42:- `memory_max` <code>(`int`: &lt;optional&gt;)</code> <sup>1.1 Beta</sup> - Optionally, specifies the maximum memory the task may use, if the client has excess memory capacity, in MB. See [Memory Oversubscription](#memory-oversubscription) for more details.
44:- `device` <code>([Device][]: &lt;optional&gt;)</code> - Specifies the device

website/content/docs/job-specification/network.mdx
48:- `mbits` <code>([_deprecated_](/docs/upgrade/upgrade-specific#nomad-0-12-0) int: 10)</code> - Specifies the bandwidth required in MBits.
50:- `port` <code>([Port](#port-parameters): nil)</code> - Specifies a TCP/UDP port
65:- `dns` <code>([DNSConfig](#dns-parameters): nil)</code> - Sets the DNS configuration

website/content/docs/job-specification/sidecar_task.mdx
140:- `resources` <code>([Resources][resources])</code> - Resources needed by the sidecar task.
144:- `logs` <code>([Logs][]: nil)</code> - Specifies logging configuration for the

website/content/docs/job-specification/device.mdx
84:- `constraint` <code>([Constraint][]: nil)</code> - Constraints to restrict
88:- `affinity` <code>([Affinity][]: nil)</code> - Affinity to specify a preference
108:        <code>{'${device.type}'}</code>
112:        <code>"gpu", "tpu", "fpga"</code>
117:        <code>{'${device.vendor}'}</code>
121:        <code>"amd", "nvidia", "intel"</code>
126:        <code>{'${device.model}'}</code>
130:        <code>"1080ti"</code>
135:        <code>
141:        <code>{'${device.attr.memory} => 8 GiB'}</code>
170:        <code>Byte</code>
173:        <code>
177:        <code>
185:        <code>Byte Rates</code>
188:        <code>
192:        <code>
200:        <code>Hertz</code>
203:        <code>MHz, GHz</code>
208:        <code>Watts</code>
211:        <code>mW, W, kW, MW, GW</code>

website/content/docs/job-specification/gateway.mdx
40:- `proxy` <code>([proxy]: nil)</code> - Configuration of the Envoy proxy that will
42:- `ingress` <code>([ingress]: nil)</code> - Configuration Entry of type `ingress-gateway`
44:- `terminating` <code>([terminating]: nil)</code> - Configuration Entry of type `terminating-gateway`
46:- `mesh` <code>([mesh]: nil)</code> - Indicates a mesh gateway will be associated
53:  the configuration option <code>[connect_timeout_ms]</code> set for the `service-resolver`, that
58:- `envoy_gateway_bind_addresses` <code>(map<string|[address]>: nil)</code> - A map of additional addresses to be bound.
91:- `tls` <code>([tls]: nil)</code> - TLS configuration for this gateway.
92:- `listener` <code>(array<[listener]> : required)</code> - One or more listeners that the
111:- `service` <code>(array<[service]>: required)</code> - One or more services to be
144:- `service` <code>(array<[linked-service]>: required)</code> - One or more services to be

website/content/docs/job-specification/scaling.mdx
38:- `min` - <code>(int: nil)</code> - The minimum acceptable count for the task group.
42:- `max` - <code>(int: &lt;required&gt;)</code> - The maximum acceptable count for the task group.
46:- `enabled` - <code>(bool: false)</code> - Whether the scaling policy is enabled.
50:- `policy` - <code>(map<string|...>: nil)</code> - The autoscaling policy. This is

website/content/docs/autoscaling/telemetry.mdx
65:        <code>nomad-autoscaler.runtime.num_goroutines</code>
72:        <code>nomad-autoscaler.runtime.alloc_bytes</code>
79:        <code>nomad-autoscaler.runtime.sys_bytes</code>
86:        <code>nomad-autoscaler.runtime.malloc_count</code>
93:        <code>nomad-autoscaler.runtime.free_count</code>
100:        <code>nomad-autoscaler.runtime.heap_objects</code>
107:        <code>nomad-autoscaler.runtime.total_gc_pause_ns</code>
114:        <code>nomad-autoscaler.runtime.total_gc_runs</code>
121:        <code>nomad-autoscaler.runtime.gc_pause_ns</code>
146:        <code>nomad-autoscaler.policy.total_num</code>
154:        <code>nomad-autoscaler.policy.source.error_count</code>
180:        <code>nomad-autoscaler.scale.evaluate_ms</code>
188:        <code>nomad-autoscaler.scale.invoke_ms</code>
196:        <code>nomad-autoscaler.scale.invoke.success_count</code>
204:        <code>nomad-autoscaler.scale.invoke.error_count</code>
230:        <code>nomad-autoscaler.plugin.manager.access_ms</code>
238:        <code>nomad-autoscaler.target.status.invoke_ms</code>
246:        <code>nomad-autoscaler.target.scale.invoke_ms</code>
254:        <code>nomad-autoscaler.apm.query.invoke_ms</code>
262:        <code>nomad-autoscaler.strategy.run.invoke_ms</code>

website/content/docs/commands/volume/create.mdx
137:- `secrets` <code>(map<string|string>:nil)</code> - An optional
141:- `parameters` <code>(map<string|string>:nil)</code> - An optional

website/content/docs/commands/volume/register.mdx
123:- `secrets` <code>(map<string|string>:nil)</code> - An optional
127:- `parameters` <code>(map<string|string>:nil)</code> - An optional
133:- `context` <code>(map<string|string>:nil)</code> - An optional
```

</details>

It looks like _most_ of the uses can be simply swapped out for single backticks. There's a few entries that have some inline HTML escaping as well, so that's worth checking as well.

**Comment by zchsh** [comment]
@tgross Oh wow, this is a big oversight on my part, thanks for catching this. I think I may be able to resolve this by replacing the `<code>` tags with backticks, to ensure each of these sections is interpreted as inline code (MDX has [a dedicated type for inline code](https://mdxjs.com/table-of-components) is which is distinct from a traditional `<code>` tag). I'll give that a shot.

**Comment by zchsh** [comment]
@tgross I think we have a fix for this - I'm testing a pre-release on this branch, and I believe [the preview](https://nomad-git-fork-zchsh-zsupgrade-code-block-hashicorp.vercel.app/docs/job-specification/network) is now fixed. Thanks again for flagging 🙇 

I think it'd still be preferable in many cases to use the [backtick syntax for inline code](https://spec.commonmark.org/0.30/#code-spans) (`` `inline-code` ``) rather than manually using the `<code>` HTML element. But also understand there are cases where this may not be feasible, so we've swapped things around so that both methods should now work as expected, even with the custom code-block ☺️

**Comment by tgross** [comment]
Much better, thanks @zchsh!

**Review by jescalan — APPROVED** [review]

**Pull request merged**
