### PR TITLE
Consul v1.7.7

### PR DESCRIPTION
**Pull request by greut**
[Nancy](https://ossindex.sonatype.org/integration/nancy) told me that consul v1.7.1 had some CVEs, hence the bump.

### CODE REVIEW

**Comment by notnoop** [comment]
Thanks for catching that. These changes look reasonable - the tests are failing though.  Mind if you take a look?  If not, we can also investigate and upgrade the dependency.

**Comment by greut** [comment]
@notnoop it should be better now :)

**Comment by shoenig** [comment]
Thanks @greut ! I'm gonna fixup the `go.sum` real quick so I can rebase https://github.com/hashicorp/nomad/pull/8709 and avoid one heck of a merge conflict.

**Comment by greut** [comment]
@shoenig perfect, thanks.

**Pull request merged**
