### PR TITLE
Sort server-members output

### PR DESCRIPTION
**Pull request by gregory-m**
Then monitoring cluster state it confusing to see "jumping" servers.

### CODE REVIEW

**Comment by dadgar** [comment]
Hey, thanks for contributing.

I think we don't want to try to do any intelligent splitting because the node name can be arbitrary (it is user specifiable). It would be great if you could just alter the PR to use lexicographic ordering which is all we can do reliably,

**Comment by gregory-m** [comment]
Thank for you input. You right and I can see potential bugs coming from spilt.

But I think its good to order hosts by region. Can I use region tag (its mandatory) to order output?

Or maybe I'am biased, because all our internal tools output server lists in such order, and its not important at all and simple lexicographic ordering its good enough?

**Comment by dadgar** [comment]
Sure you can make it ordered by DC and then within DC make it lexicographic ordering. Sounds like a good plan!

**Comment by gregory-m** [comment]
I hate timezone differences. You waiting 12 hours to answer, and then you receive the replay you recognise its night here.

Just to clarify. Nomad cluster members have "DC" and "Region" tags.

The region can be "global", "us-west" or us-east.
The DC can be "DC1", "austin" or "tampa".

So first order by region, second by DC and after this by hostname, right?

**Comment by dadgar** [comment]
Yep that sounds like the right ordering

**Comment by gregory-m** [comment]
I don't know why rebasing breaks commit list in PR. Will reopen PR.. Thanks.

**Pull request closed without merging**
