### PR TITLE
UI: Fix exec popup link for job id ≠ name

### LINKED ISSUE #7814: Exec UI failing when job.ID != job.Name
### Nomad version 
Output from `nomad version`
```
Nomad v0.11.1
```
### Operating system and Environment details
Debian buster

### Issue
I am running a job:
ID: f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd
Name: w000t.f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd

When trying to use the new Exec feature from the UI, I get on the job view:
https://server/ui/jobs/f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd

When I click on "Exec", a pop up opens with this:
nomad-not-found
URL of the popup :
https://server/ui/exec/w000t.f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd

If I manually change the URL to https://server/ui/exec/f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd , everything runs correctly, the Exec page is loaded and working

### Reproduction steps

Create a Job with an ID that is not the same as the Name ( I do it with the golang library using [this method](https://godoc.org/github.com/hashicorp/nomad/api#NewServiceJob) )
Go to the web UI, try to "Exec" in the job, you'll see that the UI is trying to load the job by its name rather than its ID

### Nomad Server logs
```
Apr 27 17:16:44 host-1 nomad[2782]:     2020-04-27T17:16:44.968+0200 [ERROR] http: request failed: method=GET path=/v1/job/w000t.f5e3edd3-deeb-46ed-a4d4-2852c3a7a5bd error="job not found" code=404
```

### PR DESCRIPTION
**Pull request by backspace**
This closes #7814. Thanks to @PouuleT for the bug report.

I’m an advocate for automated tests wherever possible, but this falls into one piece of exec that isn’t covered by tests: the opening of the popup window. Unfortunately, the use of `window.open` makes this not fit within the usual Ember environment for acceptance tests. While something like [ember-window-mock](https://github.com/kaliber5/ember-window-mock) could be of use here, or even a more minimal intervention, I’m not sure whether it’s worth it.

I could also add an acceptance test that ensures that `await Exec.visitJob({ job: this.job.id });` works for a job whose name has been changed to differ from its id, but that doesn’t actually exercise this change.

Any thoughts, @DingoEatingFuzz?

### CODE REVIEW

**Comment by PouuleT** [comment]
Thanks!
The current patch fixes the URL in the popup, but there are still broken links inside the newly opened page.
I think you'll need to switch from name to id (or plainId ?) here, in the function that opens "Exec" in another window:
https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/ui/app/components/exec/task-group-parent.js#L73
And here when opening "Exec" for a specific task in the same window:
https://github.com/hashicorp/nomad/blob/51b6ba8e70778cac1b919dee1cceda66004add53/ui/app/templates/components/exec/task-group-parent.hbs#L16
Those were the only ones that I could find, but maybe I missed some other calls

**Comment by DingoEatingFuzz** [comment]
I would typically assert the `href` of a link, but obviously that won't work here. Can you unit test the `generateUrl` method?

**Comment by backspace** [comment]
Thanks for the thoroughness, @PouuleT, I was being too brisk! I believe I’ve now covered the various places where this matters.

I did already have testing for URL-generation, @DingoEatingFuzz, I just was passing the URL components into the function instead of extracting them from the relevant objects. I think I originally settled on that to avoid constructing a bunch of container-y model-esque objects in the test, but that’s not really a good reason, as it’s preferable to contain this kind of fiddliness rather than have it spread about everywhere the function is called 😳 This is now ready for review.

**Comment by PouuleT** [comment]
@backspace Thanks! Looking good in my tests! :)

**Pull request merged**
