### PR TITLE
Propose a more structured approach to computation of backoff.

### PR DESCRIPTION
**Pull request by stswidwinski**
Proposal for a more structured and tested backoff logic.

### CODE REVIEW

**Comment by stswidwinski** [comment]
Proposal to be merged against https://github.com/hashicorp/nomad/pull/18200/files rather than to be considered in isolation

**Comment by shoenig** [comment]
Nice @stswidwinski! I was going to suggest doing something similar.

**Comment by tgross** [comment]
Yeah I like this. I'll pull this into the other PR and integrate it.

**Comment by tgross** [comment]
I've pulled this change into https://github.com/hashicorp/nomad/pull/18200

**Pull request closed without merging**
