### PR TITLE
Set a name for the container

### PR DESCRIPTION
**Pull request by achanda**

### CODE REVIEW

**Comment by achanda** [comment]
Fixes #387

**Comment by dimfeld** [comment]
Will this cause problems if two instances of a task get scheduled on the same host, since Docker container names must be unique?

**Comment by achanda** [comment]
I assumed that task names are unique, but looking at https://github.com/hashicorp/nomad/blob/master/jobspec/parse.go#L361 that does not seem to be the case. Will modify.

**Comment by dadgar** [comment]
The name should include the alloc_id which would make the name unique. Currently the drivers do not have access to the alloc_id. We will submit a PR soon to update this and then this PR can be updated.

**Comment by diptanu** [comment]
@achanda We just merged #395 which will allow you to reference the alloc id in the driver, so you could name your container after the alloc id. In the future, we should be able to pass in more information such as job name, task name, task index, etc to have more human readable container names.

**Comment by cbednarski** [comment]
@achanda Why do we need to specify this at all?

**Comment by diptanu** [comment]
@cbednarski This is useful when people use container names with metric dimensions, so a unique name which can be traced back to a Nomad object is easier to co-relate while debugging, etc.

**Comment by achanda** [comment]
@cbednarski the associated issue was asking for a name to track containers using a monitoring system. If we auto generate a name, an external agent might be able to query nomad API to get alloc id and task name and use those to monitor.

**Comment by cbednarski** [comment]
@diptanu @achanda Thanks for the background here. There is some discussion in #387 as to whether this change would achieve the desired effect.

**Comment by diptanu** [comment]
I think we need to pass the name of the task to the driver since the name might have to include more information like restarts etc to keep the task name unique through restarts.

**Comment by dadgar** [comment]
Thanks @achanda

**Pull request merged**
