### PR TITLE
changelog: fix entries for #15522 and #15819

### PR DESCRIPTION
**Pull request by lgfa29**
I noticed these while previewing the changelog from `main`.

### CODE REVIEW

**Review by jrasell — APPROVED** [review]
LGTM!

**Review by shoenig — APPROVED** [review]
We could probably get the regex in `tools/cl-entry` to exclude `"` ... @lgfa29

**Comment by lgfa29** [comment]
> We could probably get the regex in `tools/cl-entry` to exclude `"` ... @lgfa29

I fiddle around with this, but I don't think it's actually possible without false positives. We would need to detect if the entire changelog text is enclosed in quotes, but something like `^[^"][a-z0-9/\s]+: .+[^"]$` prevents ending in quotes.

Maybe just adding a caret to require the input to start with a letter or number like `^[a-z0-9/\s]+: .+` would be enough for now?

**Comment by shoenig** [comment]
We could also just do the blunt `strings.HasPrefix/Suffix`

**Comment by lgfa29** [comment]
But that removes quotes that are valid, like:

```
bug: Fix config "my_config"
```

Becomes this when trimmed:

```
bug: Fix config "my_config
```

**Comment by lgfa29** [comment]
I'm going with just the `^` for now. If we get more errors like this we can adjust it more. Thanks for the help!

**Pull request merged**
