### PR TITLE
Dynamic Host Volumes

### PR DESCRIPTION
**Pull request by tgross**
Feature integration branch for dynamic host volumes.

Closes: https://github.com/hashicorp/nomad/issues/15489
Ref: https://hashicorp.atlassian.net/browse/NET-11259

### CODE REVIEW

**Comment by tgross** [comment]
Ready for merge. All commits on this branch have been reviewed under other PRs.

**Review by philrenaud — APPROVED** [review]

**Comment by ygersie** [comment]
@tgross great to see the volume alignment here! One feature request which I hope may be added to the default built-in plugin, can it please implement two `Parameters` in the volume request for `mask` and `uid:gid`? This is going to be extremely important to move forward with adoption for us and it feels like it would be a waste to have to write a custom plugin just for this.

**Comment by gulducat** [comment]
Nice suggestion @ygersie ! Makes sense to want a chown/chmod option on the built-in `mkdir` plugin.  What do you think of this as the specification?

```hcl
type      = "host"
name      = "cool-host-vol"
plugin_id = "mkdir"
parameters = {
  mode = "0755" # default: "0700"
  uid  = 1000   # or "1000" -- default: the user running the client agent
  gid  = 1000   # or "1000"
}
```

**Comment by ygersie** [comment]
Yes that’d be great @gulducat !

**Pull request merged**
