### PR TITLE
Nomad UI first steps

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
The major components of this PR are:

1. Initializing the nomad ui codebase (built with [ember.js](https://emberjs.com/))
2. Building a basic Jobs list and detail view
3. Establishing a style guide and testing patterns
4. Updating the make commands to make it easy to build the UI and ship it in the same binary as Nomad
5. Updating the Vagrantfile to provide UI dev tools
6. Basic documentation for building the UI from source and contributing to the project

### CODE REVIEW

**Comment by lfarnell** [comment]
@DingoEatingFuzz Could you possibly post a few screenshots so we can get a feel for what the UI looks like? :smiley:

**Comment by DingoEatingFuzz** [comment]
@lfarnell Everything is still very much WIP and subject to change, but here's a sneak peak:

image

**Comment by jippi** [comment]
Ooooh I'm going to steal some of those UI ideas :P

**Comment by DingoEatingFuzz** [comment]
I'm closing this PR but continuing work on the UI. Expect more later!

**Comment by schmichael** [comment]
:soon:

**Pull request closed without merging**
