### PR TITLE
[ui] Search results are overloading filter with sorted results

### PR DESCRIPTION
**Pull request by philrenaud**
Bit of context here:
- Our Searchable mixin uses fuzzy-finding, so both my jobs "fakepy" and "fails_after_10" will show up when I type "fai" or "fak" into my search bar
image
- Last year, we addressed a [bug where sorting wouldn't apply at all if a search term was present](https://github.com/hashicorp/nomad/issues/14872) in PR #15432 
- More recently, we'd heard concerns that our search results appeared degraded from previous versions, see these screenshots showing 1.5.6 and 1.4.10 respectively: 
image
image

This PR attempts to both preserve the ability to sort after searching, and not overload results with searched-but-not-ordered filter results by creating a new getter() that checks to see if any sorting has been applied.

### CODE REVIEW

**Review by lgfa29 — APPROVED** [review]
Code changes LGTM, just missing a changelog entry and that missing property.

But I think there may be a challenge in terms of being able to get the list sorted by the original search score, since when we sort results there's no way to "unsort"  them.

One approach I though was for a search to always reset the sort order to the fuzzy score, but that could be annoying? But also, that's kind of what I expect to happen? 😅

**Comment by philrenaud** [comment]
@lgfa29 

> always reset the sort order to the fuzzy score

My worry here is that:
- search `fai`, both "fails" and "fakepy" show up, in that order
- click to sort by `priority` or something to change order
- nothing changes because fuzzy score isn't affected

I think that would break the expected experience from https://github.com/hashicorp/nomad/issues/14872, so I'm apprehensive to apply it.

**Comment by lgfa29** [comment]
Ah sorry, I think I didn't explain myself well. From your example the flow I was thinking would be like this:

1. search `fai`, `fails`, `fails-2`, and `fakepy` show up, in that order
2. click to sort by `priority` or something to change order
3. table is sorted according to selection
4. search for `fail`, only `fails` and `fails-2` show up, ordered by their fuzzy score and previous order selection is removed.

So after a search users can sort results by whichever column they would like, but changing the search term resets the ordering to fuzzy score.

**Comment by lgfa29** [comment]
Hum...I think what's missing is a listener for changes to the search term that resets `sortProperty` and `sortDescending` to their default values. Then I believe `unsortedSearchState` (or `prioritizeSearchOrder`, it does sound like a better name) and `sortedJobs` would do the flow I described.

**Comment by lgfa29** [comment]
I think we still need to clear the `sort` query param to make the arrow disappear from the table header:
image

**Comment by philrenaud** [comment]
> I think we still need to clear the sort query param to make the arrow disappear from the table header:
Only thing I'm worried about there is upon removing the search term, I expect the sort to be maintained. I could hide the arrow while the search is the most recent thing, butI'd need to re-establish it once the search term is removed.

**Comment by lgfa29** [comment]
> Only thing I'm worried about there is upon removing the search term, I expect the sort to be maintained.

Wouldn't that be a new search? I think I would expect the table to reset to its original state (sorted by `CreateIndex`) 🤔

**Comment by philrenaud** [comment]
Yeah fair enough! That's actually the state I moved it to this morning, so I think I'll move forward with this.

**Pull request merged**
