### PR TITLE
Fix goroutine leakage

### PR DESCRIPTION
**Pull request by stswidwinski**
Please see https://github.com/hashicorp/nomad/issues/15179 for a more detailed explanation. The call to `joincontext.Join` generates a `goroutine` which must be garbage collected (which means the context cleanup).

### CODE REVIEW

**Comment by shoenig** [comment]
Hi @stswidwinski, nice find and thanks for the fix! Any chance you can sign the CLA? We can't merge anything without that

**Comment by stswidwinski** [comment]
I'm working on that. Sorry, please give me a few more days to figure it out.

**Comment by stswidwinski** [comment]
@shoenig the CLA has been signed.

**Review by shoenig — APPROVED** [review]
LGTM!

**Pull request merged**
