### PR TITLE
docs: make the example for 'load' work

### PR DESCRIPTION
**Pull request by Vaelatern**
Something I ran into when trying this.

### CODE REVIEW

**Comment by the-maldridge** [comment]
s/label/load/ ?

**Comment by Amier3** [comment]
Hey @Vaelatern 

Thanks for making this PR. I tested the original load example in the docs and you're right it doesn't seem to be working as intended. This might be another manifestation of https://github.com/hashicorp/nomad/issues/2443, since the main error I was getting was:

` error="unable to open image archive: open fedora-latest/local/fedora-latest.tar: no such file or directory"`

off of this task:
```

task "fedora_latest" {
driver = "docker"

artifact {
  source = "http://localhost:8000/fedora/fedora_latest.tar.gz" # This tar file generated straight from docker save -o 
}
config {
  load = "fedora_latest.tar.gz" 
  image = "fedora:latest"
}
}

```

I'll have to ask around to figure out what the intended behavior here is, to know if this is a bug or a documentation gap. In the meantime, could you share the (sanitized) job file you used to confirm that the options stanza was needed?

**Comment by tgross** [comment]
> This might be another manifestation of https://github.com/hashicorp/nomad/issues/2443, since the main error I was getting was:
>> error="unable to open image archive: open fedora-latest/local/fedora-latest.tar: no such file or directory"

The `go-getter` library used for `artifact` automatically unarchives `.tar.gz` (and `.tar` files after the fix for #2443 in https://github.com/hashicorp/nomad/pull/11481). See https://github.com/hashicorp/go-getter#unarchiving. So once the artifact is downloaded, it's getting automatically unpacked into a pile of files and there's no image for Docker to load.

**Comment by tgross** [comment]
Reproduction (note that  `docker save -o` does _not_ compress the archive by default):

```
$ docker save -o busybox.tar busybox:1
$ file busybox.tar
busybox.tar: POSIX tar archive

$ sudo mv busybox.tar /srv/artifacts
$ nomad job run artifact-server.nomad
$ nomad job run example.nomad
```

<details><summary>artifact server jobspec</summary>

```hcl
job "artifacts" {
  datacenters = ["dc1"]
  type        = "system"

  group "artifacts" {

    network {
      mode = "bridge"
      port "www" {
        static = 15101
        to     = 8000
      }
    }

    task "httpd" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args = [
          "-v", "-f",
          "-p", "8000",
          "-u", "www-data:www-data",
          "-h", "/srv",
          "-r", "artifacts",
          "-c", "/local/httpd.conf",
        ]

        mount {
          type     = "bind"
          target   = "/srv"
          source   = "/srv/artifacts"
          readonly = true
        }

        ports = ["www"]
      }

      template {
        # HTTP Basic Auth username: "artifacts", password: "supersecret"
        data = <<EOT
/:artifacts:$1$iSV64UXs$IWot5UKWBzka6VskUSFWm0
EOT

        destination = "local/httpd.conf"
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}

```

</details>


<details><summary>jobspec using artifact</summary>

```hcl
locals {
  auth_header = base64encode("artifacts:supersecret")
}

job "example" {
  datacenters = ["dc1"]

  group "web" {

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    task "http" {

      artifact {
        source = "http://10.0.2.15:15101/busybox.tar"
        options {
          archive = false
        }
        headers {
          Authorization = "Basic ${local.auth_header}"
        }
      }

      driver = "docker"

      config {
        image   = "busybox:1"
        load    = "busybox.tar"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}

```

</details>

**Comment by Vaelatern** [comment]
@tgross Pushed doc text change.

**Review by tgross — APPROVED** [review]
LGTM! Thanks @Vaelatern!

Preview link: https://nomad-c3o2a0wot-hashicorp.vercel.app/docs/drivers/docker#load

**Pull request merged**
