### PR TITLE
UI: Escape hatch links on error pages

### LINKED ISSUE #4737: Add a "go home" page to 404 page in Nomad UI
### Nomad version
Output from `nomad version`

Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)

### Operating system and Environment details

```
vagrant@nomad:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

### Issue

It would be nice if Nomad had a "go home" link on it's 404 pages when it cannot find an allocation. I come up against this frequently when restarting my VM from scratch.

### Reproduction steps

1. Create an allocation via a deployment of any job
2. Save the link to the allocation in the ui
3. Clear out your nomad instance
4. Try to browse to the allocation again

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Just a couple simple links to provide somewhere to go after encountering an error.

Closes #4737

image

### CODE REVIEW

**Comment by joshuaogle** [comment]
We've got some very similar empty states coming in the next version of the design system. Glad you were thinking along the same lines!

Not that you need to change anything here, just wanted to give you a heads up. Here are some examples:
image

image

**Comment by johncowen** [comment]
> I'm guessing it would be relatively straightforwards to also make this page responsive while you are here?

Ignore that if you want to just wait until you revisit with these new designs!

**Comment by johncowen** [comment]
Thanks for getting this in! Tiniest nit in the world here, but has the central text alignment gone on that 'What you're looking for...' text? Is that on purpose?

**Comment by DingoEatingFuzz** [comment]
Yep. That was to make it more in line with the design system design.

**Pull request merged**
