### PR TITLE
fix website dependency issue

### PR DESCRIPTION
**Pull request by jescalan**
This should allow the website to render normally again! 🙌🏼

### CODE REVIEW

**Review by jrasell — COMMENTED** [review]
I checked this change out locally and test and get the following error even after removing the `.next` directory:
```
TypeError: attrs.matchAll(...) is not a function or its return value is not iterable
    at InlineSvg (webpack-internal:///./node_modules/@hashicorp/react-inline-svg/index.js:30:70)
    at processChild (/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/website/node_modules/next/dist/next-server/server/render.js:48:686)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:129:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.js:22:85)
    at loadGetInitialProps (/website/node_modules/next/dist/next-server/lib/utils.js:5:101)
```

Are there any additional steps or caches to clear locally which helps resolve this issue?

**Comment by notnoop** [comment]
@jrasell I hit this problem too and it looks like we no longer can run with Node.js 10: My fix is in https://github.com/hashicorp/nomad/pull/9245 .

**Comment by jescalan** [comment]
@jrasell - did you run `make build-image` then `make website-local` to test, or just `make website`? Just want to make extra sure

**Comment by jrasell** [comment]
@jescalan if I run the additional make targets the site works locally as expected. I then tested the default make target which still fails; therefore do we need to update the makefile targets to accommodate for this? As it stands the default target which is documented to run the website locally doesn't work.

**Comment by jescalan** [comment]
@jrasell yes - we have a circle workflow that will automatically update the default image when this PR merges

**Pull request merged**
