### PR TITLE
Disable PowerShell profile and simplify fingerprinting link speed on Windows

### LINKED ISSUE #11171: LinkSpeed Detection on Windows includes all PowerShell profile output for each interface
### Nomad version
Nomad v1.1.4 (acd3d7889328ad1df2895eb714e2cbe3dd9c6d82)

### Operating system and Environment details

WindowsProductName     :  Windows 10 Enterprise 
WindowsCurrentVersion   :  6.3 
WindowsVersion               :  1909 

### Issue

During agent startup (tested using the -dev option) any powershell profile output is included in the string parsed to determine link speed.  
This causes the following:
1. LinkSpeed detection fails. This may be impacting link detection in general, I'm not sure.
2. The startup logs are very cluttered. 
3. Startup is delayed by an additional 8-20 seconds 
4. It's a complicating factor if you are new to Nomad and trying to ensure you have everthing setup correctly.

### Reproduction steps

Add something to your powershell profile that outputs to the host, such as `"User: $env:USERNAME"`

Start Nomad:

```
nomad agent -dev -bind 0.0.0.0 -log-level INFO -network-interface="vEthernet (WiredNetwork)" 
```

> Note that specifiing the network speed has no impact on the result:

```
nomad agent -dev -bind 0.0.0.0 -log-level INFO -network-interface="vEthernet (WiredNetwork)" -network-speed=1024
```

#### Expected Result

Network link speed / interface fingerprint detection works, and doesn't load the powershell profile for each interface.

#### Actual Result

This is logged for each interface - obviously if I didnot have any text output in my Powershell profile this would not be a problem, but you should probably be using the `-NoProfile` option for powershell anyway to cut down on execution time, resources, and environment contamination. 

> Note that the verbose ouput is from me forcing it via `Write-Verbose -Verbose $Text`
```
2021-09-10T17:38:42.654-0400 [WARN] client.fingerprint_mgr.network: couldn't split LinkSpeed output: output="VERBOSE: Importing functions from: ***********.ps1
VERBOSE: Importing functions from: *************.ps1
VERBOSE: Importing functions from: ********.ps1
VERBOSE: Importing functions from: **************.ps1
VERBOSE: Importing functions from: ****************.ps1
VERBOSE: Importing functions from: **************.ps1


User: *******
Computer: *******


1 Gbps"

<Repeat for all 7 interfaces (docker+Hyper-V)>

    2021-09-10T17:38:42.654-0400 [DEBUG] client.fingerprint_mgr.network: link speed could not be detected, falling back to default speed: mbits=1000
    2021-09-10T17:38:46.670-0400 [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=vault period=15s
```

### Nomad Server logs 

I can produce the full logs if needed, but I'll need to actually read and possibly sanitize them before hand so I wanted to be sure it was required first.

### PR DESCRIPTION
**Pull request by lgfa29**
Fingerprinting link speed on Windows relies on running a PowerShell command and parsing its output. 

If the user has any [PowerShell profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1) that outputs anything to the console, this process will fail. This PR adds the [`-NoProfile` parameter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1#the-noprofile-parameter) to avoid loading user profile when running the command.

~Link speeds are also not always integers, such as in the case of WiFi network cards, so this PRs changes the value parsing to use `ParseFloat`.~

`Get-NetAdapter` returns a property called `Speed`, which always returns the link speed in bytes/s, making parsing the command output easier.

Closes #11171

### CODE REVIEW

**Comment by randomchance** [comment]
Thanks!

Couple of things that may be helpful, although my experience is all PowerShell/C#, not go.
You can avoid parsing it as a float if you use the `Speed` property instead of `LinkSpeed`, `Speed` is the raw bytes per second value. 

> If you want to check for other places you may have a better option, you can pipe any object to `Get-Member` for it's definition. 
  You can also use `Select-Object *`  to dump all the values (except hidden properties), bypassing object-specific formatting that normally hides the non-human readable stuff.

Since the Where-Object clause is an explicit equals (not `-like` or `-match` ) you can skip it by requesting the adapter directly by name:

```powershelll
PS> Get-NetAdapter -Name 'vEthernet (WiredNetwork)' -ErrorAction Ignore | Select-Object -ExpandProperty 'Speed'
1000000000
```
I used ` -ErrorAction Ignore` so that any errors, such as not finding an adapter by that name, are silent.

Slightly related note, I would love if this could log the names it's looking for at a debug level; then a new user would be able to see what values are allowed if they need to specify the adapter manually. Alternatively, you could explicitly say to use the "Interface Alias on Windows, not the "Interface Name". I fully admit that this was probably me overthinking things, because the InterfaceName is normally something like `ethernet_32778`.

**Comment by lgfa29** [comment]
Oh thank you so much for the tips. My knowledge of PowerShell is quite limited, so always good to learn new things 🙂 

> Slightly related note, I would love if this could log the names it's looking for at a debug level;

Yup, I noticed this too while working on this, so I also opened https://github.com/hashicorp/nomad/pull/11184 😄 

That PR adds a new field to log messages to display the device name during fingerprinting. Is this what you were looking for?

**Review by DerekStrickland — APPROVED** [review]
Nice job simplifying this!

**Comment by lgfa29** [comment]
> Nice job simplifying this!

100% of the credit goes to @randomchance. I just typed words 🙃

**Pull request merged**
