### PR TITLE
Update go getter

### LINKED ISSUE #9050: Artifact stanza doesn't support AWS S3 virtual host style paths
Related to https://github.com/hashicorp/go-getter/issues/263 and https://github.com/hashicorp/nomad/issues/8454, valid S3 paths fail when used in the [`artifact`](https://www.nomadproject.io/docs/job-specification/artifact#artifact-stanza) stanza. This is a real pain to spot, due to the _slight_ difference in newer S3 paths. Moreover, new S3 buckets now **[must](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)** be referenced using the new format.

### PR DESCRIPTION
**Pull request by cgbaker**
replay of #9349 

resolves #9050 and #8454

### CODE REVIEW

**Comment by cgbaker** [comment]
i locally ran `go clean -modcache` and `go mod tidy` and I'm seeing a consistent `go.sum`. it's possible that the module cache on the circleci instance is poisoned with a bad checksum.

**Review by picatz — APPROVED** [review]

**Comment by picatz** [comment]
Hmmm. For context, I had minor trouble with that release. IIRC the tag I pushed was reverted since the CI workflow failed and @mdeggies fixed it. 

 🤔 Maybe that is related or the cause of the `go.mod` error?

**Comment by tgross** [comment]
I didn't realize we had a second PR open for it, but I think I have the build issues resolved now in https://github.com/hashicorp/nomad/pull/9349 by bumping up to the 1.5.2 tag.

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/9349

**Pull request closed without merging**
