### PR TITLE
CSI Listsnapshot secrets support

### LINKED ISSUE #10640: CSI Volume Snapshot List: support secrets in the request
### Proposal
CSI List Snapshots supports secrets in the request:
https://github.com/container-storage-interface/spec/blob/master/csi.proto#L1173-L1176

However, when using `nomad volume snapshot list`, there is no way to pass this secret into the request (unless I'm missing something).

A possible solution could be the following workflow:
```
nomad volume snapshot list --secrets=key1=val1,key2=val2
```

This secrets map would be passed down to the CSI driver as mentioned in the CSI spec.

Alternatively, once #7978 is implemented:
```
nomad volume snapshot list --vault-secret=mysecret
```

### Use-cases
For CSI drivers that require a secret for a successful `nomad volume snapshot list`, this would be very helpful.

### Attempted Solutions
n/a - besides altering our CSI driver rules to allow for ListSnapshots without secrets.

I am happy to work on this issue if the above proposal is accepted.

### PR DESCRIPTION
**Pull request by ggriffiths**
Fixes #10640 
Signed-off-by: Grant Griffiths <ggriffiths@purestorage.com>

### CODE REVIEW

**Comment by ggriffiths** [comment]
Still working on this one, getting a WIP PR out first.

**Comment by ggriffiths** [comment]
Tested with Portworx CSI Driver:
```
[root@ip-70-0-177-133 nomadspecs]# nomad volume snapshot create pxvol1 snap4
Snapshot ID         Volume ID     Size    Create Time           Ready?
833182824418993564  670065376975  10 GiB  1970-01-01T00:00:01Z  true
[root@ip-70-0-177-133 nomadspecs]# nomad volume snapshot list --secrets=auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYW50QG9wZW5zdG9yYWdlLmlvIiwiZXhwIjoxNjI2OTMzODc0LCJncm91cHMiOlsiKiJdLCJpYXQiOjE2MjY4NDc0NzQsImlzcyI6Im9wZW5zdG9yYWdlLmlvIiwibmFtZSI6IkdyYW50Iiwicm9sZXMiOlsic3lzdGVtLmFkbWluIl0sInN1YiI6ImdyYW50QG9wZW5zdG9yYWdlLmlvIn0.Tvz8ZjXLvXb8Z5JCg4UEfbfYb2MFo3CLBRBXxqZ22yE
Snapshot ID          Volume ID     Size    Create Time  Ready?
833182824418993564   670065376975  10 GiB  <none>       true
523181979236462009   670065376975  10 GiB  <none>       true
1102101751991941593  670065376975  10 GiB  <none>       true
788455741817460122   670065376975  10 GiB  <none>       true
[root@ip-70-0-177-133 nomadspecs]# nomad volume snapshot list --secrets=auth-token=bad
Error querying CSI external snapshots for plugin "": Unexpected response code: 500 (controller list snapshots: CSI.ControllerListSnapshots: controller plugin returned an internal error, check the plugin allocation logs for more information: rpc error: code = Internal desc = Unable to get all snapshots: rpc error: code = Unauthenticated desc = Unable to obtain token issuer from authorization token: Token is invalid: bad)
```

**Comment by ggriffiths** [comment]
Added a small unit test addition. Ready for review.

**Review by schmichael — APPROVED** [review]
Looks great @ggriffiths! Thanks for contributing!

There's a few other steps. I can take care of them if you don't want to! Just let me know.

- [ ] Changelog entry (create a file `.changelog/10848.txt` and see https://github.com/hashicorp/nomad/blob/main/contributing/CHANGELOG.md#developer-guide)
- [ ] CLI docs - [website](https://www.nomadproject.io/docs/commands/volume/snapshot-list) / [code](https://github.com/hashicorp/nomad/blob/main/website/content/docs/commands/volume/snapshot-list.mdx)
- [ ] API docs [website](https://www.nomadproject.io/api-docs/volumes#list-snapshots) / [code](https://github.com/hashicorp/nomad/blob/main/website/content/api-docs/volumes.mdx)

https://github.com/hashicorp/nomad/blob/main/contributing/checklist-command.md is hopefully helpful, but we don't do a good job of pointing people to it. Sorry!

**Comment by ggriffiths** [comment]
Cool, I'll work on those steps. Thanks for taking a look!

**Comment by ggriffiths** [comment]
Added the docs and changelog @schmichael

**Comment by ggriffiths** [comment]
@schmichael / @tgross, let me know if anything else is needed here. Hoping to get this in for the next minor release.

**Comment by schmichael** [comment]
Fantastic. Thanks for sticking with this @ggriffiths! It will ship in our next release!

**Pull request merged**
