### PR TITLE
Add pending_time client metric for allocations

### LINKED ISSUE #5686: Feature Request: Add metrics for evaluation/allocation/task events
It would be great if there were metrics to track the different states an evaluation/allocation/task goes through. In particular I'm interested in tracking how long it takes for tasks to start running once a job is submitted, how long an evaluation takes to complete, how many times an allocation has been restarted.
I'd like to contribute the feature if you think it make a good addition.

### PR DESCRIPTION
**Pull request by joshcc3**
Fixes #5686

### CODE REVIEW

**Comment by joshcc3** [comment]
Ideally I'd like to capture the pending time for some percentiles of allocation pending time instead of the average, not sure which percentiles are appropriate?
Also, it's not clear to me when allocations are garbage collected, so I generally

**Comment by cgbaker** [comment]
> Also, it's not clear to me when allocations are garbage collected, is it just when resources are scarce or do they have a ttl as well?

The allocation runners are not GC'd until the associated allocation is GC'd on the servers.

**Comment by notnoop** [comment]
Have you considered using go-metrics' Samples support that's meant for tracking timing metrics: https://godoc.org/github.com/armon/go-metrics#MetricSink .  Backend metrics collectors can interpret timing metrics appropriately and do aggregation and quintiles over user defined spans, e.g. in statsd https://github.com/statsd/statsd/blob/master/docs/metric_types.md#timing .

**Comment by joshcc3** [comment]
Interesting, I'll take a look

**Comment by notnoop** [comment]
thank you so much for your contribution.  I'm closing this PR as part of an effort to prune our open PRs.  We have a couple of outstanding items, e.g. using MetricSink, and potentially taking the GC behavior into account.  We will welcome a new PR (or re-open this) with the suggestions applied.  Thank you so much and sorry for the slow response.

**Pull request closed without merging**
