### PR TITLE
CSI: Snapshot volume create should use vol.Secrets

### LINKED ISSUE #10639: nomad snapshot create does use persisted secrets
### Nomad version
```
Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)
```

### Operating system and Environment details
CentOS-7

### Issue
Nomad volume create does not seem to persist any values from the `secrets` block. The secrets are passed to the CSI Driver, as I'm able to use `auth-token` in the Portworx CSI Driver create call, however when creating a snapshot, I'm not seeing these secrets propagated to the snapshot create call. I'm not sure if this is by design or not. If this is by design, is there a way to have secrets passed to `nomad volume snapshot create/delete`?

The `nomad volume status --json` command shows null secrets:
```
[root@grantdev nomadspecs]# nomad volume status --json pxvol2 | grep Secrets
    "Secrets": null,
```

### Reproduction steps
1. Create a typical volume with secrets
```
id           = "pxvol2"
name         = "database2"
type         = "csi"
plugin_id    = "portworx"
capacity_min = "5G"
capacity_max = "5G"

capability {
  access_mode     = "single-node-reader-only"
  attachment_mode = "file-system"
}

capability {
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
}

secrets {
  auth-token = "eyJhbGciOiJIUzI1NiIsIn..."
  test = "123"
}

parameters {
  abc = "def"
}
```

2. Check for secrets in volume, it will be null:
```
# nomad volume status --json pxvol2 | grep Secrets
    "Secrets": null,
```

3. Attempt to create volume snapshot with secrets from volume create, command will fail if it requires a secret:
```
# nomad volume snapshot create pxvol1 snap6
Error snapshotting volume: Unexpected response code: 500 (1 error occurred:
	* could not create snapshot: controller create snapshot: rpc error: controller create snapshot: CSI.ControllerCreateSnapshot: controller plugin returned an internal error, check the plugin allocation logs for more information: rpc error: code = Internal desc = Failed to create snapshot: rpc error: code = PermissionDenied desc = Access denied without authentication token

)
```

#### Expected Result
Secrets should be persisted during volume create

#### Actual Result
Secrets are not persisted during volume create

### Job file (if appropriate)
n/a

### Nomad Server logs (if appropriate)
n/a

### Nomad Client logs (if appropriate)
n/a

### PR DESCRIPTION
**Pull request by ggriffiths**
Signed-off-by: Grant Griffiths <ggriffiths@purestorage.com>

Fixes #10639

### CODE REVIEW

**Comment by ggriffiths** [comment]
tested on my dev cluster 
```
[root@ip-70-0-76-58 ~]# nomad version
Nomad v1.1.3-dev (1eff6fd07e2908b495f97b30a95034e331c1b1b6+CHANGES)
[root@ip-70-0-76-58 ~]# nomad volume snapshot create pxvol2 snap4
Snapshot ID         Volume ID     Size    Create Time           Ready?
800687039846414825  283728768536  10 GiB  1970-01-01T00:00:01Z  true
```

**Review by tgross — APPROVED** [review]
LGTM

I think in the future it's worth considering if we want to let the user provide snapshot-specific secrets via the API (or from Vault, see https://github.com/hashicorp/nomad/issues/7978), but this will fix the bug at hand and doesn't close off that path for us.

**Comment by tgross** [comment]
The fix for this will ship in Nomad 1.1.3. Snapshots are new for 1.1.0, so no backport required.

**Comment by ggriffiths** [comment]
> I think in the future it's worth considering if we want to let the user provide snapshot-specific secrets via the API

Agreed, that would also make sense too.

**Pull request merged**
