### PR TITLE
Run format as a part of test

### PR DESCRIPTION
**Pull request by achanda**

### CODE REVIEW

**Comment by dadgar** [comment]
Its a bit weird for test to rewrite your code?

**Comment by achanda** [comment]
I hear you. My rationale was that, I've broken gofmt compatibility a number of times. Was looking for a way to gate that in the repo. Maybe a better way is to run `make format` in travis and mark as failed if gofmt does not report compliance? That'd require gofmt not re-write files and just report error.

**Comment by sethvargo** [comment]
@achanda I think the general pattern is that you should have your editor or editor plugin run the formatter for you. Most of the go devs I know use go-sublime or the go-vundle which will automatically format on save for you.

**Comment by achanda** [comment]
I finally got a configured vim to run gofmt for me automatically on save. Closing this.

**Comment by cbednarski** [comment]
> I finally configured vim to run gofmt for me automatically on save. Closing this.

Woo! :tada: :grinning: Welcome to the good life!

**Pull request closed without merging**
