### PR TITLE
Add mount propagation to protobuf definition of mounts

### PR DESCRIPTION
**Pull request by stswidwinski**
A simple fix for https://github.com/hashicorp/nomad/issues/15014 and the related https://github.com/hashicorp/nomad-driver-podman/issues/192.

Tests pass for the `drivers` package.

### CODE REVIEW

**Comment by stswidwinski** [comment]
cc: @tgross @ejweber

**Review by lgfa29 — CHANGES_REQUESTED** [review]
Thanks for the contribution @stswidwinski 🙂 

Would you mind add tests for this change? I think adding `PropagationMode` to [`TestTaskConfigRoundTrip`](https://github.com/hashicorp/nomad/blob/v1.4.2/plugins/drivers/utils_test.go#L77-L82) may be a good one, but feel free to add other tests if you see fit.

We also require contributors to sing our CLA before merging work, so you could you this as well?

**Comment by stswidwinski** [comment]
Sure thing! I'll do that on Monday -- I was looking for related roundtrip
tests but didn't find them before. Thanks for the pointer!

**Comment by stswidwinski** [comment]
The CLA has been signed. Thanks for your patience @lgfa29

**Review by lgfa29 — APPROVED** [review]
I just pushed a commit to add a changelog entry for this. Thank you for the contribution and for taking care of the CLA 🙂

**Pull request merged**
