### PR TITLE
Implement task log streaming

### LINKED ISSUE #277: HTTP endpoint to tail job logs, stdout, and stderr
Would be a nice addition for easy debugging

I realise non-nomad version of this would be to pipe everything to syslog or similar, but it requires a few more moving parts

### PR DESCRIPTION
**Pull request by diptanu**
This PR is still a **Work In Progress**. Opened this for the team to follow along the work and play with the feature and provide feedback.

This allows users to stream logs from tasks whose allocations aren't dead and purged.
Currently the following drivers support streaming: ```raw_exec```, ```docker```, ```exec``` and ```java```
This has been tested on only Linux and OSX(only the ```raw_exec``` driver has been tested on OSX).

The following command can be used to stream the logs 

```nomad logs --alloc [alloc-id] --task [task-name] --lines [offset from the end] --stdout --stderr --follow```

Fixes #277 and #475

### CODE REVIEW

**Comment by skozin** [comment]
@diptanu, could you please explain why this was closed?

**Comment by dadgar** [comment]
@skozin: We are still doing this, we are just taking a different approach so we are closing this PR but expect follow up PRs around logging.

**Comment by skozin** [comment]
@dadgar: ah, that makes sense, thanks.

**Comment by blalor** [comment]
What was the resolution to this?  Any followup PRs?

**Comment by dadgar** [comment]
@blalor there will be eventually, we decided to go with a different API and as such closed this. There is cat, ls and stat currently

**Pull request closed without merging**
