### PR TITLE
Don't rely on CpuStats.Percent

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Just do the math client-side with TotalTicks and Reserved

### CODE REVIEW

**Comment by jippi** [comment]
is Percent broken since it can't be used?

**Comment by DingoEatingFuzz** [comment]
Unsure if it's broken or reporting something different than TotalTicks / Reserved. @dadgar and I chatted and landed on this.

**Comment by jippi** [comment]
sounds like a hack to something broken, which everyone is using? ;)

**Comment by dadgar** [comment]
Not broken, percent is total but doing it via the total ticks will show percent as a function of the reserved where the other is overall on machine.

**Pull request merged**
