### PR TITLE
Add ReadonlyRootfs option to the Docker driver

### PR DESCRIPTION
**Pull request by filipochnik**

### CODE REVIEW

**Comment by alxark** [comment]
damn i'm waiting for this commit in next release =) have you checked tmpfs mount in docker api ? it will be cool to have it with readonly root

**Comment by filipochnik** [comment]
Maybe I'm missing something but can't you just use the `mounts` option? https://docs.docker.com/engine/admin/volumes/tmpfs/#use-a-tmpfs-mount-in-a-container

**Comment by alxark** [comment]
TmpFs in docker API works a little bit different, it will copy content to tmpfs mount, while mount -t tmpfs will overwrite directory with empty tmpfs storage.

**Comment by dadgar** [comment]
Thanks @filipochnik

**Comment by filipochnik** [comment]
@alxark 
Doesn't seem to be the case for me
```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
$ docker run busybox ls /var
spool
www
$ docker run --tmpfs /var busybox ls /var
$ docker run --mount type=tmpfs,target=/var busybox ls /var
$
```
Docs don't mention that either AFAICT.

**Pull request merged**
