### PR TITLE
driver.rkt: support network configuration [waiting]

### PR DESCRIPTION
**Pull request by schmichael**
Thanks to @nak3 for the original PR! #1616 

I rebased on master, fixed the test, and changed the docs to include an example that should Just Work for anyone with rkt installed.

@nak3 I'd love if you could verify my changes. I'm new to rkt networking and having to specify port names that are defined either in the image or on the system was a little confusing to me.

### CODE REVIEW

**Comment by schmichael** [comment]
Not planning on merging this in for 0.5 unless someone shows up who really needs it.

**Comment by blalor** [comment]
That's definitely a feature I'm missing in the current rkt driver.  I won't need it for a couple of weeks, but I'll be looking for it soon after that.

**Comment by schmichael** [comment]
@blalor @salehe Thanks for responding! We're about to cut a release candidate for the 0.5 release. If I merge this in do you think you'd be able to test it in the next few days?

I've verified it works, but I don't know if the configuration is the best way to expose rkt port mapping. It seems to require the image or system rkt config have the port map defined before you can use it in the `port_map` task config in nomad.

If it looks like it fits your needs I'll happily merge it!

**Comment by schmichael** [comment]
@blalor @salehe Sorry for the noise: we merged as-is. Please let me know if this works for you.

**Comment by blalor** [comment]
This has been working great for me.  Thank you!

**Pull request merged**
