### PR TITLE
Fix DevicesSets being removed when cpusets are reloaded with cgroup v2

### LINKED ISSUE #12877: nomad 1.3.0-rc.1 cgroupsv2 /dev/ strangeness
### Nomad version
Nomad v1.3.0-rc.1 (31b0a1841cb6d3c7aa64bb2162f50798ba3b3d6e)

### Operating system and Environment details
Ubuntu 22.04 Jammy Jellyfish  5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Issue
Something funky happens when using cgroups v2 where (at the very least) the ability to read /dev/zero and write to /dev/null is lost. Using a raw_exec job and `dd if=/dev/zero of=/dev/null count=1` I get `dd: failed to open '/dev/zero': Operation not permitted` fairly randomly but consistently. The original jobs are actually python/java, not that it seems to matter.

If I disable cgroupsv2 with the following, the problem disappears.
```diff --git a/client/lib/cgutil/cgutil_linux.go b/client/lib/cgutil/cgutil_linux.go
index 1333d0cc1..5f8d8fc68 100644
--- a/client/lib/cgutil/cgutil_linux.go
+++ b/client/lib/cgutil/cgutil_linux.go
@@ -18,7 +18,7 @@ import (
 // cgroups.v1
 //
 // This is a read-only value.
-var UseV2 = cgroups.IsCgroup2UnifiedMode()
+var UseV2 = false //cgroups.IsCgroup2UnifiedMode()

 // GetCgroupParent returns the mount point under the root cgroup in which Nomad
 // will create cgroups. If parent is not set, an appropriate name for the version
 ```

Output from a failed run, I'll note it seems to always work on the "first" run, only seems to be restarts under the same allocation id.
```
+0 records in
1+0 records out
512 bytes copied, 0.000455007 s, 1.1 MB/s
1+0 records in
1+0 records out
512 bytes copied, 0.000992872 s, 516 kB/s
1+0 records in
1+0 records out
512 bytes copied, 0.000578372 s, 885 kB/s
1+0 records in
1+0 records out
512 bytes copied, 0.000302934 s, 1.7 MB/s
1+0 records in
1+0 records out
512 bytes copied, 0.000195964 s, 2.6 MB/s
dd: failed to open '/dev/zero': Operation not permitted

File: /alloc/logs/env.stdout.0
busted
total 124K
lrwxrwxrwx   1 root root     7 Apr 23 02:08 bin -> usr/bin
lrwxrwxrwx   1 root root     8 Apr 23 02:08 sbin -> usr/sbin
lrwxrwxrwx   1 root root    10 Apr 23 02:08 libx32 -> usr/libx32
lrwxrwxrwx   1 root root     9 Apr 23 02:08 lib64 -> usr/lib64
lrwxrwxrwx   1 root root     9 Apr 23 02:08 lib32 -> usr/lib32
lrwxrwxrwx   1 root root     7 Apr 23 02:08 lib -> usr/lib
drwxr-xr-x   2 root root  4.0K Apr 23 02:08 srv
drwxr-xr-x   2 root root  4.0K Apr 23 02:08 media
drwxr-xr-x  14 root root  4.0K Apr 23 02:08 usr
drwxr-xr-x   6 root root  4.0K Apr 23 02:09 snap
drwx------   2 root root   16K Apr 23 02:09 lost+found
drwxr-xr-x   4 root root  4.0K May  5 01:44 boot
drwxr-xr-x   2 root root  4.0K May  5 01:49 mnt
drwxr-xr-x   5 root wheel 4.0K May  5 01:49 nfs
drwxr-xr-x 158 root root  4.0K May  5 01:50 home
drwxr-xr-x  14 root root  4.0K May  5 01:51 var
dr-xr-xr-x  13 root root     0 May  5 02:03 sys
dr-xr-xr-x 539 root root     0 May  5 02:03 proc
drwxr-xr-x  20 root root  4.0K May  5 02:03 ..
drwxr-xr-x  20 root root  4.0K May  5 02:03 .
drwxr-xr-x  19 root root  4.1K May  5 02:03 dev
drwxr-xr-x 141 root root   12K May  5 03:01 etc
drwxr-xr-x  48 root root  4.0K May  5 04:58 opt
drwx------   6 root root  4.0K May  5 05:14 root
drwxr-xr-x  39 root root  1.3K May  5 05:35 run
drwxrwxrwt  15 root root   40K May  5 05:36 tmp
crw-rw-rw- 1 root root 1, 5 May  5 02:03 /dev/zero
uid=0(root) gid=0(root) groups=0(root)
Current: =ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
Ambient set =
Current IAB:
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 3182
max locked memory           (kbytes, -l) unlimited
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited

### Job file (if appropriate)
```
job "test-devnull" {
	datacenters = ["..."]
	type = "service"

	constraint {
		attribute = "${attr.unique.hostname}"
		value = "..."
	}

       reschedule {
	    delay = "5s"
	    delay_function = "constant"
	    unlimited = true
       }

	group "group" {
		restart {
			attempts = 5
			mode = "fail"
			delay = "0s"
			interval = "30s"
		}
	
               count = 10

		task "env" {
			driver = "raw_exec"
			config {
				command = "/usr/bin/bash"
				args = [ "-c", "dd if=/dev/zero of=/dev/null count=1 || (echo \"busted\"; ls -ltrha /; ls -ltrha /dev/zero; id; capsh --print; ulimit -a; sleep 1000)"]
			}
			resources {
				memory = "10"
			}
		}

	}
}```

### PR DESCRIPTION
**Pull request by TrueBrain**
This meant that if any allocation was created or removed, all active DevicesSets were removed from all cgroups of all tasks.

This was most noticeable with "exec" and "raw_exec", as it meant they no longer had access to `/dev` files.

Fixes #12877, and possibly a bunch of other related but different reports in the issue tracker. See https://github.com/hashicorp/nomad/issues/12877#issuecomment-1591666774 for steps how to reproduce this problem, and validate it is actually fixed with this change. Most important piece of context: https://github.com/opencontainers/runc/blob/5cf9bb229feed19a767cbfdf9702f6487341e29e/libcontainer/cgroups/devices/v2.go#L55-L57

Few warnings:
- 4 hours ago I had no idea how cgroups worked, nor how BPF and DevicesSets interacted with cgroups
- 1 hour ago I never touched a Go project in my life (but a long history of other languages, so "its fine")

PS: I checked if there were any e2e tests this could be part of; but it seems there is nothing there yet, neither for cgroup or cpuset. If I missed it, please let me know.

### CODE REVIEW

**Comment by shoenig** [comment]
This is great @TrueBrain! 

On your branch, can you run `make cl` to generate a changelog entry? 

I turned your repro steps into an e2e test in https://github.com/hashicorp/nomad/pull/17546, can confirm it seems to work. Most cgroups tests are in the `drivers/` packages but just following the repro steps in the e2e environment is pretty effective.


before (main)

```
➜ go test -v -run TestCgroup
=== RUN   TestCgroupDevices
=== RUN   TestCgroupDevices/testDevicesUsable
    assert.go:11:
        devices_test.go:53: expected nil error
        ↪ error: command nomad [alloc exec 9f0e235a-3cb2-db10-a5ac-3450cad63cda dd if=/dev/zero of=/dev/null count=1] failed: exit status 1
        Output: dd: failed to open '/dev/zero': Operation not permitted
--- FAIL: TestCgroupDevices (1.58s)
    --- FAIL: TestCgroupDevices/testDevicesUsable (1.46s)
FAIL
exit status 1
FAIL    github.com/hashicorp/nomad/e2e/isolation        1.587s
```

after with (7bdde48851)

```
➜ go test -v -run TestCgroup
=== RUN   TestCgroupDevices
=== RUN   TestCgroupDevices/testDevicesUsable
--- PASS: TestCgroupDevices (1.64s)
    --- PASS: TestCgroupDevices/testDevicesUsable (1.52s)
PASS
ok      github.com/hashicorp/nomad/e2e/isolation        1.644s
```

**Comment by TrueBrain** [comment]
Shall I also cherry-pick your e2e in this PR?

And awesome, happy there is a place for some e2e for this :D

**Comment by shoenig** [comment]
> Shall I also cherry-pick your e2e in this PR?

Go for it!

**Review by shoenig — APPROVED** [review]
LGTM!

**Pull request merged**
