### PR TITLE
Add nomad env to envoy bootstrap

### PR DESCRIPTION
**Pull request by jorgemarey**
Just saw #12543 .We are doing things a bit different in a fork we have. This PR takes a different aproach and adds enviroment variables to the envoy boostrap hook. This along with https://github.com/hashicorp/consul/pull/13049 allow us to configure things like the following in the consul configuration:

```
kind = "proxy-defaults"
name = "global"

Config {
      envoy_dogstatsd_url = "udp://172.26.64.1:9125"
      envoy_stats_tags = [
        "alloc_id=${NOMAD_ALLOC_ID}",
        "nomad_group=${NOMAD_GROUP_NAME}",
        "nomad_job=${NOMAD_JOB_NAME}",
        "nomad_namespace=${NOMAD_NAMESPACE}",
      ]
}
```
This can also be set on the nomad sidecar configuration.

### CODE REVIEW

**Comment by Amier3** [comment]
We might want to put a hold on this pending the changes in https://github.com/hashicorp/consul/pull/13049

**Comment by shoenig** [comment]
Unless I'm mistaken, closed by https://github.com/hashicorp/nomad/pull/14311

**Comment by jorgemarey** [comment]
Hi @shoenig. I guess that this specific case presented in the issue (adding the stats tags to envoy) is solved by https://github.com/hashicorp/nomad/pull/14311, but I don't think it's the only use case for passing the NOMAD_ environment variables to the envoy task. I think that providing those values to envoy could allow users to better modify their escape-hatchs if necesary. What do you think?

**Comment by shoenig** [comment]
Sounds reasonable enough to me ~

**Review by shoenig — COMMENTED** [review]
LGTM

**Pull request merged**
