### PR TITLE
Reregister Client on failed heartbeat

### LINKED ISSUE #1590: Unable to update list of servers after replacing servers
### Nomad version

v0.4.0

### Operating system and Environment details

* CoreOS stable 1068.8.0
* AWS

### Issue

Nomad clients are unable to register with servers configured via `nomad client-config -update-servers` after replacing all servers.

### Reproduction steps

I have a working Nomad cluster setup consisting of 3 clients and these these 3 server nodes:

```
$ nomad server-members
Name                                            Address    Port  Status  Leader  Protocol  Build  Datacenter  Region
ip-10-8-3-95.eu-west-1.compute.internal.global  10.8.3.95  4648  alive   true    2         0.4.0  eu-west-1   global
ip-10-8-3-96.eu-west-1.compute.internal.global  10.8.3.96  4648  alive   false   2         0.4.0  eu-west-1   global
ip-10-8-4-30.eu-west-1.compute.internal.global  10.8.4.30  4648  alive   false   2         0.4.0  eu-west-1   global
```

Afterwards I terminate the 3 cluster nodes and recreate them from scratch:

```
$ nomad server-members
Name                                             Address     Port  Status  Leader  Protocol  Build  Datacenter  Region
ip-10-8-3-123.eu-west-1.compute.internal.global  10.8.3.123  4648  alive   true    2         0.4.0  eu-west-1   global
ip-10-8-4-93.eu-west-1.compute.internal.global   10.8.4.93   4648  alive   false   2         0.4.0  eu-west-1   global
ip-10-8-4-94.eu-west-1.compute.internal.global   10.8.4.94   4648  alive   false   2         0.4.0  eu-west-1   global
```

However, now I cannot get the clients to register with the new servers, even after running `nomad client-config -update-servers`. In fact, the agent still tries to contact the old/dead server nodes:

```
$ nomad client-config -update-servers 10.8.3.123:4647 10.8.4.93:4647 10.8.4.94:4647
Updated server list
$ nomad client-config -servers
10.8.3.123:4647
10.8.4.30:4647
10.8.3.96:4647
10.8.4.93:4647
10.8.3.95:4647
10.8.4.94:4647
```

### Nomad Client logs

From what I can see in the client logs, the agent still tries to connect to the old/dead cluster leader:

```
Aug 15 14:43:38 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:37.889545 [DEBUG] client.rpcproxy: pinging server "10.8.3.95:4647 (tcp:10.8.3.95:4647)" failed: failed to get conn: dial tcp 10.8.3.95:4647: getsockopt: no route to host
Aug 15 14:43:41 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:40.895560 [DEBUG] client.rpcproxy: pinging server "10.8.3.95:4647 (tcp:10.8.3.95:4647)" failed: failed to get conn: dial tcp 10.8.3.95:4647: getsockopt: no route to host
Aug 15 14:43:44 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:43.901578 [DEBUG] client.rpcproxy: pinging server "10.8.3.95:4647 (tcp:10.8.3.95:4647)" failed: failed to get conn: dial tcp 10.8.3.95:4647: getsockopt: no route to host
Aug 15 14:43:47 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:46.907597 [DEBUG] client.rpcproxy: pinging server "10.8.3.95:4647 (tcp:10.8.3.95:4647)" failed: failed to get conn: dial tcp 10.8.3.95:4647: getsockopt: no route to host
Aug 15 14:43:50 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:49.913596 [DEBUG] client.rpcproxy: pinging server "10.8.3.95:4647 (tcp:10.8.3.95:4647)" failed: failed to get conn: dial tcp 10.8.3.95:4647: getsockopt: no route to host
Aug 15 14:43:53 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:52.919560 [DEBUG] client.rpcproxy: pinging server "10.8.3.95:4647 (tcp:10.8.3.95:4647)" failed: failed to get conn: dial tcp 10.8.3.95:4647: getsockopt: no route to host
Aug 15 14:43:53 ip-10-8-3-165.eu-west-1.compute.internal nomad-client:      2016/08/15 12:43:52.919592 [DEBUG] client.rpcproxy: No healthy servers during rebalance, aborting
```

It appears that the agent does not even attempt to connect to all servers returned by `nomad client-config -servers`.

### Background

We want our infrastructure to be self-healing. While Nomad provides `retry_join` on the server side, there's no such thing for clients. I know that servers will push the current list of healthy servers to clients. However, this does not work if all server nodes are replaced at once or if the client nodes are bootstrapped before any server. That's why we want to periodically push discovered servers via the `/v1/agent/servers` endpoint on clients.

/cc @denderello

### PR DESCRIPTION
**Pull request by dadgar**
If the client detects that a heartbeat has failed because it is not registered, reregister the client

Fixes #1590

### CODE REVIEW

**Comment by mlafeldt** [comment]
We're going to test this tomorrow (see https://github.com/hashicorp/nomad/issues/1590#issuecomment-240144464).

@dadgar Wondering if this would make the 0.4.1 release if it gets merged soon?

**Comment by diptanu** [comment]
LGTM, would have been nice to have a test.

**Comment by dadgar** [comment]
Will wait for @mlafeldt to test

**Comment by mlafeldt** [comment]
Works fine. See https://github.com/hashicorp/nomad/issues/1590#issuecomment-240371597

**Pull request merged**
