### PR TITLE
Prepare website for 0.11.0-beta1 release

### PR DESCRIPTION
**Pull request by notnoop**
Also, update latest release to 0.10.5

### CODE REVIEW

**Comment by notnoop** [comment]
The netlifi website with prerelease header is ready for view in https://deploy-preview-7489--nomad-website.netlify.com/downloads/ .

**Comment by drewbailey** [comment]
looks good! (assuming the link should still be 403ing)

**Comment by notnoop** [comment]
correct - it should 403 until the beta release is published.

**Comment by jescalan** [comment]
Looks great! 🎉

**Pull request merged**
