### PR TITLE
Graceful shutdown (ctrl-c interrupt) support for windows console tasks.

### PR DESCRIPTION
**Pull request by capone212**
- Run windows tasks with separate console (instead of inheriting parent console)
- Add "nomad shutdown-task <pid>" command to send ctr-c interrupt to windows process

### CODE REVIEW

**Comment by dadgar** [comment]
@capone212 Would you mind describing the problem you are trying to solve?

**Comment by capone212** [comment]
Hi @dad' , sure!
We are very excited about nomad (and consul) because it has windows support out of the box. This is something unique and powerful. 
Unfortunately Nomad has some limitation under windows platform and I am trying to work around most serious one here: Nomad terminates jobs on "nomad stop", I mean, it kills job without leaving any chance to save some data and so on. 
That is not acceptable in production, for obvious reasons . 
Nomad has this problem because winapi has some limitations and golang opted to not support sending Interrupt signal to over process on Windows. See for more info https://github.com/golang/go/issues/6720 .

While it is not easy to implement send interrupt in general case, it is relatively easy for nomad to interrupt child jobs. Implemented in this pull request approach is most simple and durable one.

However there is one limitation: to handle interrupt job should have console. So GUI application will be terminated, because sending  console interrupt is going to fail. 

GUI apps we can be handled by sending WM_CLOSE message, but I think nobody would try to start GUI apps using nomad in production.

**Comment by dadgar** [comment]
Hey going to close this as it was mainly kept to refer to but it is very out dated at this point. We'd still like this functionality and with some work happening to refactor the driver/executor it will be much easier to specialize the windows implementation. This is a few months away.

**Comment by pkellychnct** [comment]
I know this is old, but is there any movement on this functionality? We're going to production in a few weeks with Nomad on Windows Server and would very much like to see this by the time we get there. :grin:
Thanks!

**Comment by dadgar** [comment]
@pkellychnct Hey, it isn't quite there yet. In the mean time you may want to take advantage of https://www.nomadproject.io/docs/job-specification/task.html#shutdown_delay. This lets you deregister from Consul and then wait before killing the service. This allows you to stop routing traffic to the application that is about to be killed.

**Comment by pkellychnct** [comment]
Thanks for taking the time to reply. Thanks for the suggestion. We'll take a look at doing that in the interim.

**Pull request closed without merging**
